/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12077 $ of $ 
 *
 * $Id:$
 */
#ifndef DOT11STATICROUTETABLE_DATA_SET_H
#define DOT11STATICROUTETABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11StaticRouteTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * DOT11-AC-MIB::dot11StaticRouteTable is subid 1 of dot11RouteGroup.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.32.1, length: 12
*/


int dot11StaticRouteTable_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx);
int dot11StaticRouteTable_undo_cleanup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx);
int dot11StaticRouteTable_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx);
int dot11StaticRouteTable_commit( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx);
int dot11StaticRouteTable_undo_commit( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx);


int ipRouteStaticDest_check_value( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticDest_val);
int ipRouteStaticDest_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );
int ipRouteStaticDest_set( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticDest_val );
int ipRouteStaticDest_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );

int ipRouteStaticMask_check_value( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticMask_val);
int ipRouteStaticMask_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );
int ipRouteStaticMask_set( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticMask_val );
int ipRouteStaticMask_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );

int ipRouteStaticMode_check_value( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticMode_val);
int ipRouteStaticMode_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );
int ipRouteStaticMode_set( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticMode_val );
int ipRouteStaticMode_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );

int ipRouteStaticSubnet_check_value( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticSubnet_val);
int ipRouteStaticSubnet_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );
int ipRouteStaticSubnet_set( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticSubnet_val );
int ipRouteStaticSubnet_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );

int ipRouteStaticInterface_check_value( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, char *ipRouteStaticInterface_val_ptr,  size_t ipRouteStaticInterface_val_ptr_len);
int ipRouteStaticInterface_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );
int ipRouteStaticInterface_set( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, char *ipRouteStaticInterface_val_ptr,  size_t ipRouteStaticInterface_val_ptr_len );
int ipRouteStaticInterface_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );

int ipRouteStaticActive_check_value( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticActive_val);
int ipRouteStaticActive_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );
int ipRouteStaticActive_set( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticActive_val );
int ipRouteStaticActive_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );

int ipRouteStaticMetric_check_value( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, long ipRouteStaticMetric_val);
int ipRouteStaticMetric_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );
int ipRouteStaticMetric_set( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, long ipRouteStaticMetric_val );
int ipRouteStaticMetric_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );

int ipRouteStaticRowStatus_check_value( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticRowStatus_val);
int ipRouteStaticRowStatus_undo_setup( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );
int ipRouteStaticRowStatus_set( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx, u_long ipRouteStaticRowStatus_val );
int ipRouteStaticRowStatus_undo( dot11StaticRouteTable_rowreq_ctx *rowreq_ctx );


int dot11StaticRouteTable_check_dependencies(dot11StaticRouteTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* DOT11STATICROUTETABLE_DATA_SET_H */
