/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef DOT11LEGALDEVICETABLE_DATA_ACCESS_H
#define DOT11LEGALDEVICETABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "autelanWtpGroup.h"

/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11LegalDeviceTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * DOT11-AC-MIB::dot11LegalDeviceTable is subid 1 of dot11WhiteBlackList.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.8.1, length: 12
*/


    int dot11LegalDeviceTable_init_data(dot11LegalDeviceTable_registration * dot11LegalDeviceTable_reg);


    /*
     * TODO:180:o: Review dot11LegalDeviceTable cache timeout.
     * The number of seconds before the cache times out
     */
#define DOT11LEGALDEVICETABLE_CACHE_TIMEOUT   DOT1DTPFDBTABLE_CACHE_TIMEOUT

void dot11LegalDeviceTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void dot11LegalDeviceTable_container_shutdown(netsnmp_container *container_ptr);

int dot11LegalDeviceTable_container_load(netsnmp_container *container);
void dot11LegalDeviceTable_container_free(netsnmp_container *container);

int dot11LegalDeviceTable_cache_load(netsnmp_container *container);
void dot11LegalDeviceTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int dot11LegalDeviceTable_row_prep( dot11LegalDeviceTable_rowreq_ctx *rowreq_ctx);

int dot11LegalDeviceTable_validate_index( dot11LegalDeviceTable_registration * dot11LegalDeviceTable_reg,
                               dot11LegalDeviceTable_rowreq_ctx *rowreq_ctx);
int legalMacID_check_index( dot11LegalDeviceTable_rowreq_ctx *rowreq_ctx ); /* internal */


#ifdef __cplusplus
}
#endif

#endif /* DOT11LEGALDEVICETABLE_DATA_ACCESS_H */
