#ifndef _WS_EAG_WISPR_H_
#define _WS_EAG_WISPR_H_


#define MAX_EAG_WISPR_VERSION_LEN 8
#define MAX_EAG_WISPR_USERNAME_LEN	253
#define MAX_EAG_WISPR_PASSWORD_LEN	128


#define DEFAULT_PORTAL_REQ_TIMEOUT	10
#define MIN_PORTAL_REQ_TIMEOUT		3
#define MAX_PORTAL_REQ_TIMEOUT		10

#endif

