/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18.2.1 $ of : mfd-data-get.m2c,v $
 *
 * $Id:$
 *
 * @file dot11DistinguishTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT11DISTINGUISHTABLE_DATA_GET_H
#define DOT11DISTINGUISHTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11DistinguishTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11DistinguishTable is subid 3 of wtpLink.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.1.6.3, length: 12
*/
    /*
     * indexes
     */
    int wtpMacAddr_dot11DistinguishTable_map(char **mib_wtpMacAddr_val_ptr_ptr, size_t *mib_wtpMacAddr_val_ptr_len_ptr, char *raw_wtpMacAddr_val_ptr, size_t raw_wtpMacAddr_val_ptr_len, int allow_realloc);

    int wtpTryDistinguishTimes_map(u_long *mib_wtpTryDistinguishTimes_val_ptr, u_long raw_wtpTryDistinguishTimes_val);
    int wtpTryDistinguishTimes_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpTryDistinguishTimes_val_ptr );
    int wtpDistinguishSuccessTimes_map(u_long *mib_wtpDistinguishSuccessTimes_val_ptr, u_long raw_wtpDistinguishSuccessTimes_val);
    int wtpDistinguishSuccessTimes_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpDistinguishSuccessTimes_val_ptr );
    int wtpReasonErrKeyFailDistinguishTimes_map(u_long *mib_wtpReasonErrKeyFailDistinguishTimes_val_ptr, u_long raw_wtpReasonErrKeyFailDistinguishTimes_val);
    int wtpReasonErrKeyFailDistinguishTimes_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpReasonErrKeyFailDistinguishTimes_val_ptr );
    int wtpReasonInvalidFailDistinguishTimes_map(u_long *mib_wtpReasonInvalidFailDistinguishTimes_val_ptr, u_long raw_wtpReasonInvalidFailDistinguishTimes_val);
    int wtpReasonInvalidFailDistinguishTimes_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpReasonInvalidFailDistinguishTimes_val_ptr );
    int wtpReasonTimeOutFailDistinguishTimes_map(u_long *mib_wtpReasonTimeOutFailDistinguishTimes_val_ptr, u_long raw_wtpReasonTimeOutFailDistinguishTimes_val);
    int wtpReasonTimeOutFailDistinguishTimes_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpReasonTimeOutFailDistinguishTimes_val_ptr );
    int wtpReasonRefuseFailDistinguishTimes_map(u_long *mib_wtpReasonRefuseFailDistinguishTimes_val_ptr, u_long raw_wtpReasonRefuseFailDistinguishTimes_val);
    int wtpReasonRefuseFailDistinguishTimes_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpReasonRefuseFailDistinguishTimes_val_ptr );
    int wtpReasonOthersFailDistinguishTimes_map(u_long *mib_wtpReasonOthersFailDistinguishTimes_val_ptr, u_long raw_wtpReasonOthersFailDistinguishTimes_val);
    int wtpReasonOthersFailDistinguishTimes_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpReasonOthersFailDistinguishTimes_val_ptr );
    int wtpUserRequestTimes_map(u_long *mib_wtpUserRequestTimes_val_ptr, u_long raw_wtpUserRequestTimes_val);
    int wtpUserRequestTimes_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpUserRequestTimes_val_ptr );
    int wtpAssociatedUserNum_map(u_long *mib_wtpAssociatedUserNum_val_ptr, u_long raw_wtpAssociatedUserNum_val);
    int wtpAssociatedUserNum_get( dot11DistinguishTable_rowreq_ctx *rowreq_ctx, u_long * wtpAssociatedUserNum_val_ptr );


int dot11DistinguishTable_indexes_set_tbl_idx(dot11DistinguishTable_mib_index *tbl_idx, char *wtpMacAddr_val_ptr,  size_t wtpMacAddr_val_ptr_len);
int dot11DistinguishTable_indexes_set(dot11DistinguishTable_rowreq_ctx *rowreq_ctx, char *wtpMacAddr_val_ptr,  size_t wtpMacAddr_val_ptr_len);




#ifdef __cplusplus
}
#endif

#endif /* DOT11DISTINGUISHTABLE_DATA_GET_H */
/** @} */
