#ifndef __DCLI_HBIP_H__
#define __DCLI_HBIP_H__
#include "command.h"

#define HANSI_STR "High-Available Network Access Service Instance Configuration\n"

#define MAX_IFNAME_LEN        20
#define MAX_IPADDR_LEN        20

#define DCLI_HBIP_RETURN_CODE_BASE                 (0x180000)
#define DCLI_HBIP_RETURN_CODE_OK		              (DCLI_HBIP_RETURN_CODE_BASE + 1)
#define DCLI_HBIP_RETURN_CODE_ERR		          (DCLI_HBIP_RETURN_CODE_BASE + 2)
#define DCLI_HBIP_RETURN_CODE_PROFILE_OUT_OF_RANGE (DCLI_HBIP_RETURN_CODE_BASE + 3)
#define DCLI_HBIP_RETURN_CODE_PROFILE_EXIST        (DCLI_HBIP_RETURN_CODE_BASE + 4)
#define DCLI_HBIP_RETURN_CODE_PROFILE_NOTEXIST        (DCLI_HBIP_RETURN_CODE_BASE + 5)
#define DCLI_HBIP_RETURN_CODE_MALLOC_FAILED        (DCLI_HBIP_RETURN_CODE_BASE + 6)
#define DCLI_HBIP_RETURN_CODE_BAD_PARAM            (DCLI_HBIP_RETURN_CODE_BASE + 7)
#define DCLI_HBIP_RETURN_CODE_PROFILE_NOT_PREPARE  (DCLI_HBIP_RETURN_CODE_BASE + 8)  
#define DCLI_HBIP_RETURN_CODE_SERVICE_NOT_PREPARE  (DCLI_HBIP_RETURN_CODE_BASE + 9)  

#define HBIP_DEBUG_FLAG_ALL       0xFF
#define HBIP_DEBUG_FLAG_DBG       0x1
#define HBIP_DEBUG_FLAG_WAR       0x2
#define HBIP_DEBUG_FLAG_ERR       0x4
#define HBIP_DEBUG_FLAG_EVT       0x8
#define HBIP_DEBUG_FLAG_PKT_REV   0x10
#define HBIP_DEBUG_FLAG_PKT_SED   0x20
#define HBIP_DEBUG_FLAG_PKT_ALL   0x30
#define HBIP_DEBUG_FLAG_PROTOCOL  0x40

#endif

