/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.12 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
#ifndef DOT11CONFIGTRAPSWITCHTABLE_DATA_ACCESS_H
#define DOT11CONFIGTRAPSWITCHTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif
#include "autelanWtpGroup.h"


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11ConfigTrapSwitchTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11ConfigTrapSwitchTable is subid 2 of dot11AlarmConfiguration.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.18.2, length: 12
*/


    int dot11ConfigTrapSwitchTable_init_data(dot11ConfigTrapSwitchTable_registration_ptr dot11ConfigTrapSwitchTable_reg);


/*
 * TODO:180:o: Review dot11ConfigTrapSwitchTable cache timeout.
 * The number of seconds before the cache times out
 */
#define DOT11CONFIGTRAPSWITCHTABLE_CACHE_TIMEOUT   DOT1DTPFDBTABLE_CACHE_TIMEOUT

void dot11ConfigTrapSwitchTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
int dot11ConfigTrapSwitchTable_cache_load(netsnmp_container *container);
void dot11ConfigTrapSwitchTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int dot11ConfigTrapSwitchTable_row_prep( dot11ConfigTrapSwitchTable_rowreq_ctx *rowreq_ctx);


#ifdef __cplusplus
}
#endif

#endif /* DOT11CONFIGTRAPSWITCHTABLE_DATA_ACCESS_H */
