/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef DOT11ACINTERFACETABLE_H
#define DOT11ACINTERFACETABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(DOT11-AC-MIB)
config_require(DOT11-AC-MIB/dot11AcInterfaceTable/dot11AcInterfaceTable_interface)
config_require(DOT11-AC-MIB/dot11AcInterfaceTable/dot11AcInterfaceTable_data_access)
config_require(DOT11-AC-MIB/dot11AcInterfaceTable/dot11AcInterfaceTable_data_get)
config_require(DOT11-AC-MIB/dot11AcInterfaceTable/dot11AcInterfaceTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for dot11AcInterfaceTable */
#include "dot11AcInterfaceTable_oids.h"

/* enum definions */
#include "dot11AcInterfaceTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_dot11AcInterfaceTable(void);
void shutdown_dot11AcInterfaceTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11AcInterfaceTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * DOT11-AC-MIB::dot11AcInterfaceTable is subid 4 of dot11AcInterface.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.4.4, length: 12
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review dot11AcInterfaceTable registration context.
     */
typedef netsnmp_data_list dot11AcInterfaceTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review dot11AcInterfaceTable data context structure.
 * This structure is used to represent the data for dot11AcInterfaceTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * dot11AcInterfaceTable.
 */
typedef struct dot11AcInterfaceTable_data_s {
    
        /*
         * AcInterfaceName(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   AcInterfaceName[255];
size_t      AcInterfaceName_len; /* # of char elements, not bytes */
    
        /*
         * AcInterfaceIP(2)/IPADDR/ASN_IPADDRESS/u_long(u_long)//l/A/W/e/r/d/h
         */
   u_long   AcInterfaceIP;
    
        /*
         * AcInterfaceNetMask(3)/IPADDR/ASN_IPADDRESS/u_long(u_long)//l/A/W/e/r/d/h
         */
   u_long   AcInterfaceNetMask;
    
        /*
         * AcInterfaceIPV6(4)/InetAddressIPv6/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
   char   AcInterfaceIPV6[50];
size_t      AcInterfaceIPV6_len; /* # of char elements, not bytes */
    
        /*
         * AcInterfaceIPV6prefix(5)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/r/d/h
         */
   u_long   AcInterfaceIPV6prefix;
    
} dot11AcInterfaceTable_data;


/* *********************************************************************
 * TODO:115:o: |-> Review dot11AcInterfaceTable undo context.
 * We're just going to use the same data structure for our
 * undo_context. If you want to do something more efficent,
 * define your typedef here.
 */
typedef dot11AcInterfaceTable_data dot11AcInterfaceTable_undo_data;

/*
 * TODO:120:r: |-> Review dot11AcInterfaceTable mib index.
 * This structure is used to represent the index for dot11AcInterfaceTable.
 */
typedef struct dot11AcInterfaceTable_mib_index_s {

        /*
         * ifIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   ifIndex;


} dot11AcInterfaceTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review dot11AcInterfaceTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_dot11AcInterfaceTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review dot11AcInterfaceTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * dot11AcInterfaceTable_rowreq_ctx pointer.
 */
typedef struct dot11AcInterfaceTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_dot11AcInterfaceTable_IDX_LEN];
    
    dot11AcInterfaceTable_mib_index        tbl_idx;
    
    dot11AcInterfaceTable_data              data;
    dot11AcInterfaceTable_undo_data       * undo;
    unsigned int                column_set_flags; /* flags for set columns */


    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to dot11AcInterfaceTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *dot11AcInterfaceTable_data_list;

} dot11AcInterfaceTable_rowreq_ctx;

typedef struct dot11AcInterfaceTable_ref_rowreq_ctx_s {
    dot11AcInterfaceTable_rowreq_ctx *rowreq_ctx;
} dot11AcInterfaceTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int dot11AcInterfaceTable_pre_request(dot11AcInterfaceTable_registration * user_context);
    int dot11AcInterfaceTable_post_request(dot11AcInterfaceTable_registration * user_context,
        int rc);

    int dot11AcInterfaceTable_rowreq_ctx_init(dot11AcInterfaceTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void dot11AcInterfaceTable_rowreq_ctx_cleanup(dot11AcInterfaceTable_rowreq_ctx *rowreq_ctx);

    int dot11AcInterfaceTable_check_dependencies(dot11AcInterfaceTable_rowreq_ctx * rowreq_ctx); 
    int dot11AcInterfaceTable_commit(dot11AcInterfaceTable_rowreq_ctx * rowreq_ctx);

    dot11AcInterfaceTable_rowreq_ctx *
                  dot11AcInterfaceTable_row_find_by_mib_index(dot11AcInterfaceTable_mib_index *mib_idx);

extern oid dot11AcInterfaceTable_oid[];
extern int dot11AcInterfaceTable_oid_size;


#include "dot11AcInterfaceTable_interface.h"
#include "dot11AcInterfaceTable_data_access.h"
#include "dot11AcInterfaceTable_data_get.h"
#include "dot11AcInterfaceTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* DOT11ACINTERFACETABLE_H */
/** @} */
