#ifndef _BSD_DBUS_DEF_H
#define _BSD_DBUS_DEF_H

#ifndef PATH_LEN
#define PATH_LEN 64
#endif

extern char BSD_DBUS_BUSNAME[PATH_LEN];
extern char BSD_DBUS_OBJPATH[PATH_LEN];
extern char BSD_DBUS_INTERFACE[PATH_LEN];


extern char BSD_COPY_FILES_BETEWEEN_BORADS[PATH_LEN];
extern char BSD_COPY_FILES_BETEWEEN_BORADS_V2[PATH_LEN];
extern char BSD_COPY_FILES_BETEWEEN_DEVICES[PATH_LEN];
extern char BSD_SYNCHRONIZE_FILES_TO_OTHER_BOARDS[PATH_LEN];
extern char BSD_SYNCHRONIZE_FILES_TO_OTHER_BOARDS_V2[PATH_LEN];
extern char BSD_GET_ALIVE_SLOT_IDS[PATH_LEN];
extern char BSD_SET_BSD_DAEMONLOG_LEVEL[PATH_LEN];
extern char BSD_CHECK_DETINATION_BOARD_INFORMATION[PATH_LEN];
extern char BSD_CHECK_DETINATION_DEVICE_INFORMATION[PATH_LEN];
extern char BSD_CLOSE_TCP_SOCKET[PATH_LEN];


enum bsd_dbus_result_no_e {
	BSD_DBUS_SUCCESS,
	BSD_DBUS_ERROR, /* general use, no detail error information*/
	BSD_DBUS_ID_NO_EXIST,
	BSD_DBUS_UNKNOWN_ID_FORMAT,
	BSD_DBUS_LOCAL_HANSI_ID_NOT_EXIST,
	BSD_DBUS_HANSI_ID_NOT_EXIST,	
	BSD_DBUS_SLOT_ID_NOT_EXIST,
	BSD_DBUS_NUM_OVER_MAX,
	BSD_DBUS_WARNNING,
	BSD_DBUS_NOCONFIG_UPLINK,
	BSD_DBUS_NOCONFIG_DOWNLINK,
	BSD_DBUS_COMMAND_NOT_SUPPORT,
	BSD_DBUS_LICENSE_TYPE_NOT_EXIST,	
	BSD_DBUS_LICENSE_NUM_NOT_ENOUGH,
	BSD_DBUS_PERMISSION_DENIAL
};
#define DCLI_BSD_CHECK_FAILED	(-1)
#define DCLI_BSD_CREATED		(1)		/* BSD have created.		*/
#define DCLI_BSD_NO_CREATED	(0)		/* BSD have not created.	*/


#endif

