/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-set.m2c,v $
 *
 * $Id:$
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "autelanWtpGroup.h"
#include "ws_dhcp_conf.h"
#include "ws_log_conf.h"
#include "ws_dcli_dhcp.h"
/* include our parent header */
#include "dot11DHCPIpAddressPoolTable.h"


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11DHCPIpAddressPoolTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11DHCPIpAddressPoolTable is subid 4 of dot11Service.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.4, length: 12
*/
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     *                        +==============+
     *       +----------------||  object    ||
     *       |              E ||  lookup    ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                        +--------------+
     *                        |    post      |
     *                        |   request    |
     *                        +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (dot11DHCPIpAddressPoolTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
dot11DHCPIpAddressPoolTable_undo_setup( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:dot11DHCPIpAddressPoolTable_undo_setup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> Setup dot11DHCPIpAddressPoolTable undo.
     * set up dot11DHCPIpAddressPoolTable undo information, in preparation for a set.
     */

    return rc;
} /* dot11DHCPIpAddressPoolTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (dot11DHCPIpAddressPoolTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
dot11DHCPIpAddressPoolTable_undo_cleanup( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:dot11DHCPIpAddressPoolTable_undo_cleanup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:452:M: |-> Cleanup dot11DHCPIpAddressPoolTable undo.
     */

    return rc;
} /* dot11DHCPIpAddressPoolTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the FLAG_* bits can be found in
 * dot11DHCPIpAddressPoolTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param dot11DHCPIpAddressPoolTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
dot11DHCPIpAddressPoolTable_commit( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    int             save_flags;

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:dot11DHCPIpAddressPoolTable_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * save flags, then clear until we actually do something
     */
    save_flags = rowreq_ctx->column_set_flags;
    rowreq_ctx->column_set_flags = 0;

    /*
     * commit dot11DHCPIpAddressPoolTable data
     * 1) check the column's flag in save_flags to see if it was set.
     * 2) clear the flag when you handle that column
     * 3) set the column's flag in column_set_flags if it needs undo
     *    processing in case of a failure.
     */
    if (save_flags & FLAG_IPADDPOOLSTARTADD) {
       save_flags &= ~FLAG_IPADDPOOLSTARTADD; /* clear IPAddpoolStartAdd */
       /*
        * TODO:482:o: |-> commit column IPAddpoolStartAdd.
        */
       //rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"dot11DHCPIpAddressPoolTable column IPAddpoolStartAdd commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo IPAddpoolStartAdd
             */
            rowreq_ctx->column_set_flags |= FLAG_IPADDPOOLSTARTADD;
       }
    }

    if (save_flags & FLAG_IPADDPOOLENDADD) {
       save_flags &= ~FLAG_IPADDPOOLENDADD; /* clear IPAddpoolEndAdd */
       /*
        * TODO:482:o: |-> commit column IPAddpoolEndAdd.
        */
       //rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"dot11DHCPIpAddressPoolTable column IPAddpoolEndAdd commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo IPAddpoolEndAdd
             */
            rowreq_ctx->column_set_flags |= FLAG_IPADDPOOLENDADD;
       }
    }

    if (save_flags & FLAG_GATEWAYADDRESS) {
       save_flags &= ~FLAG_GATEWAYADDRESS; /* clear GatewayAddress */
       /*
        * TODO:482:o: |-> commit column GatewayAddress.
        */
       //rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"dot11DHCPIpAddressPoolTable column GatewayAddress commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo GatewayAddress
             */
            rowreq_ctx->column_set_flags |= FLAG_GATEWAYADDRESS;
       }
    }

    if (save_flags & FLAG_IPADDLEASEPERIOD) {
       save_flags &= ~FLAG_IPADDLEASEPERIOD; /* clear IPAddLeasePeriod */
       /*
        * TODO:482:o: |-> commit column IPAddLeasePeriod.
        */
       //rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"dot11DHCPIpAddressPoolTable column IPAddLeasePeriod commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo IPAddLeasePeriod
             */
            rowreq_ctx->column_set_flags |= FLAG_IPADDLEASEPERIOD;
       }
    }

    if (save_flags) {
       snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n", save_flags);
       return MFD_ERROR;
    }

    return rc;
} /* dot11DHCPIpAddressPoolTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the FLAG_* bits can be found in
 * dot11DHCPIpAddressPoolTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param dot11DHCPIpAddressPoolTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
dot11DHCPIpAddressPoolTable_undo_commit( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:dot11DHCPIpAddressPoolTable_undo_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:485:M: |-> Undo dot11DHCPIpAddressPoolTable commit.
     * check the column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & FLAG_) {}
     */

    return rc;
} /* dot11DHCPIpAddressPoolTable_undo_commit */

/*
 * TODO:420:r: Implement dot11DHCPIpAddressPoolTable index validation.
 */
/*
 * TODO:440:M: Implement dot11DHCPIpAddressPoolTable node value checks.
 * TODO:450:M: Implement dot11DHCPIpAddressPoolTable undo functions.
 * TODO:460:M: Implement dot11DHCPIpAddressPoolTable set functions.
 * TODO:480:M: Implement dot11DHCPIpAddressPoolTable commit functions.
 */
/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpAddressPoolEntry.IPAddpoolStartAdd
 * IPAddpoolStartAdd is subid 2 of dot11DHCPIpAddressPoolEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.4.1.2
 * Description:
IP Address pool starting address.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param IPAddpoolStartAdd_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * dot11DHCPIpAddressPoolTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_IPADDRESS
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
IPAddpoolStartAdd_check_value( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx, u_long IPAddpoolStartAdd_val)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddpoolStartAdd_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid IPAddpoolStartAdd value.
     */

    return MFD_SUCCESS; /* IPAddpoolStartAdd value not illegal */
} /* IPAddpoolStartAdd_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (dot11DHCPIpAddressPoolTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * dot11DHCPIpAddressPoolTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
IPAddpoolStartAdd_undo_setup( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddpoolStartAdd_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup IPAddpoolStartAdd undo.
     */
    /*
     * copy IPAddpoolStartAdd data
     * set rowreq_ctx->undo->IPAddpoolStartAdd from rowreq_ctx->data.IPAddpoolStartAdd
     */
    rowreq_ctx->undo->IPAddpoolStartAdd = rowreq_ctx->data.IPAddpoolStartAdd;


    return MFD_SUCCESS;
} /* IPAddpoolStartAdd_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param IPAddpoolStartAdd_val
 *        A u_long containing the new value.
 */
int
IPAddpoolStartAdd_set( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx, u_long IPAddpoolStartAdd_val )
{

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddpoolStartAdd_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:245:o: |-> Implement IPAddpoolStartAdd reverse mapping.
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them here.
 */
    /*
     * TODO:461:M: |-> Set IPAddpoolStartAdd value.
     * set IPAddpoolStartAdd value in rowreq_ctx->data
     */
	int ret = -1;
	int ip_addr = 0;
	char start_ip[32] = { 0 };
	memset(start_ip,0,32);
	char end_ip[32] = { 0 };
	memset(end_ip,0,32);
	char defip[32] = { 0 };
	memset(defip,0,32);

	ip_addr = rowreq_ctx->data.IPAddpoolStartAdd;
	INET_NTOA( ip_addr, defip );

	ip_addr = IPAddpoolStartAdd_val;
	INET_NTOA( ip_addr, start_ip );

	ip_addr = rowreq_ctx->data.IPAddpoolEndAdd;
	INET_NTOA( ip_addr, end_ip );
	unsigned int index = 0,mode = 1;

	config_ip_pool_name(rowreq_ctx->data.PoolName, &index, rowreq_ctx->data.slot_id);
	add_dhcp_pool_ip_range("delete", defip,end_ip, rowreq_ctx->data.PoolMask,index, rowreq_ctx->data.slot_id);
	ret=add_dhcp_pool_ip_range("add", start_ip,end_ip, rowreq_ctx->data.PoolMask,index, rowreq_ctx->data.slot_id);

	if(ret == 1) {
   		rowreq_ctx->data.IPAddpoolStartAdd = IPAddpoolStartAdd_val;
	}
	else {
	    add_dhcp_pool_ip_range("add", defip, end_ip, rowreq_ctx->data.PoolMask,index, rowreq_ctx->data.slot_id);
	    return MFD_ERROR;
	}					

    return MFD_SUCCESS;
} /* IPAddpoolStartAdd_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
IPAddpoolStartAdd_undo( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddpoolStartAdd_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up IPAddpoolStartAdd undo.
     */
    /*
     * copy IPAddpoolStartAdd data
     * set rowreq_ctx->data.IPAddpoolStartAdd from rowreq_ctx->undo->IPAddpoolStartAdd
     */
    rowreq_ctx->data.IPAddpoolStartAdd = rowreq_ctx->undo->IPAddpoolStartAdd;

    
    return MFD_SUCCESS;
} /* IPAddpoolStartAdd_undo */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpAddressPoolEntry.IPAddpoolEndAdd
 * IPAddpoolEndAdd is subid 3 of dot11DHCPIpAddressPoolEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.4.1.3
 * Description:
IP Address pool ending address.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param IPAddpoolEndAdd_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * dot11DHCPIpAddressPoolTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_IPADDRESS
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
IPAddpoolEndAdd_check_value( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx, u_long IPAddpoolEndAdd_val)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddpoolEndAdd_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid IPAddpoolEndAdd value.
     */

    return MFD_SUCCESS; /* IPAddpoolEndAdd value not illegal */
} /* IPAddpoolEndAdd_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (dot11DHCPIpAddressPoolTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * dot11DHCPIpAddressPoolTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
IPAddpoolEndAdd_undo_setup( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddpoolEndAdd_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup IPAddpoolEndAdd undo.
     */
    /*
     * copy IPAddpoolEndAdd data
     * set rowreq_ctx->undo->IPAddpoolEndAdd from rowreq_ctx->data.IPAddpoolEndAdd
     */
    rowreq_ctx->undo->IPAddpoolEndAdd = rowreq_ctx->data.IPAddpoolEndAdd;


    return MFD_SUCCESS;
} /* IPAddpoolEndAdd_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param IPAddpoolEndAdd_val
 *        A u_long containing the new value.
 */
int
IPAddpoolEndAdd_set( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx, u_long IPAddpoolEndAdd_val )
{

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddpoolEndAdd_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:245:o: |-> Implement IPAddpoolEndAdd reverse mapping.
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them here.
 */
    /*
     * TODO:461:M: |-> Set IPAddpoolEndAdd value.
     * set IPAddpoolEndAdd value in rowreq_ctx->data
     */
	int ret = -1;
	int ip_addr = 0;
	char start_ip[32] = { 0 };
	memset(start_ip,0,32);
	char end_ip[32] = { 0 };
	memset(end_ip,0,32);
	char defip[32] = { 0 };
	memset(defip,0,32);

	ip_addr = rowreq_ctx->data.IPAddpoolEndAdd;
	INET_NTOA( ip_addr, defip );

	ip_addr = rowreq_ctx->data.IPAddpoolStartAdd;
	INET_NTOA( ip_addr, start_ip );

	ip_addr = IPAddpoolEndAdd_val;
	INET_NTOA( ip_addr, end_ip );
	unsigned int index = 0,mode = 1;

	config_ip_pool_name(rowreq_ctx->data.PoolName, &index, rowreq_ctx->data.slot_id);
	add_dhcp_pool_ip_range("delete", start_ip, defip, rowreq_ctx->data.PoolMask,index, rowreq_ctx->data.slot_id);
	ret=add_dhcp_pool_ip_range("add", start_ip, end_ip, rowreq_ctx->data.PoolMask,index, rowreq_ctx->data.slot_id);

	if(ret == 1) {
    	rowreq_ctx->data.IPAddpoolEndAdd = IPAddpoolEndAdd_val;
	}
	else {
		add_dhcp_pool_ip_range("add", start_ip, defip, rowreq_ctx->data.PoolMask, index, rowreq_ctx->data.slot_id);
		return MFD_ERROR;
	}					

    return MFD_SUCCESS;
} /* IPAddpoolEndAdd_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
IPAddpoolEndAdd_undo( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddpoolEndAdd_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up IPAddpoolEndAdd undo.
     */
    /*
     * copy IPAddpoolEndAdd data
     * set rowreq_ctx->data.IPAddpoolEndAdd from rowreq_ctx->undo->IPAddpoolEndAdd
     */
    rowreq_ctx->data.IPAddpoolEndAdd = rowreq_ctx->undo->IPAddpoolEndAdd;

    
    return MFD_SUCCESS;
} /* IPAddpoolEndAdd_undo */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpAddressPoolEntry.GatewayAddress
 * GatewayAddress is subid 4 of dot11DHCPIpAddressPoolEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.4.1.4
 * Description:
Gateway Address.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param GatewayAddress_val
 *        A u_long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * dot11DHCPIpAddressPoolTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_IPADDRESS
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
GatewayAddress_check_value( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx, u_long GatewayAddress_val)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:GatewayAddress_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid GatewayAddress value.
     */

    return MFD_SUCCESS; /* GatewayAddress value not illegal */
} /* GatewayAddress_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (dot11DHCPIpAddressPoolTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * dot11DHCPIpAddressPoolTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
GatewayAddress_undo_setup( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:GatewayAddress_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup GatewayAddress undo.
     */
    /*
     * copy GatewayAddress data
     * set rowreq_ctx->undo->GatewayAddress from rowreq_ctx->data.GatewayAddress
     */
    rowreq_ctx->undo->GatewayAddress = rowreq_ctx->data.GatewayAddress;


    return MFD_SUCCESS;
} /* GatewayAddress_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param GatewayAddress_val
 *        A u_long containing the new value.
 */
int
GatewayAddress_set( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx, u_long GatewayAddress_val )
{

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:GatewayAddress_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:245:o: |-> Implement GatewayAddress reverse mapping.
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them here.
 */
    /*
     * TODO:461:M: |-> Set GatewayAddress value.
     * set GatewayAddress value in rowreq_ctx->data
     */
	int ret = -1;
	int ip_addr = 0;
	char set_ip[32];
	memset(set_ip,0,32);
	unsigned int index = 0,mode = 1;

	ip_addr = GatewayAddress_val;
	INET_NTOA( ip_addr, set_ip );

	config_ip_pool_name(rowreq_ctx->data.PoolName, &index, rowreq_ctx->data.slot_id);
	ret = ip_dhcp_server_routers_ip(set_ip, index, mode, rowreq_ctx->data.slot_id);

	if(ret == 1) {
		rowreq_ctx->data.GatewayAddress = GatewayAddress_val;
	}
	else {
	    return MFD_ERROR;
	}		
    return MFD_SUCCESS;
} /* GatewayAddress_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
GatewayAddress_undo( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:GatewayAddress_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up GatewayAddress undo.
     */
    /*
     * copy GatewayAddress data
     * set rowreq_ctx->data.GatewayAddress from rowreq_ctx->undo->GatewayAddress
     */
    rowreq_ctx->data.GatewayAddress = rowreq_ctx->undo->GatewayAddress;

    
    return MFD_SUCCESS;
} /* GatewayAddress_undo */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpAddressPoolEntry.IPAddLeasePeriod
 * IPAddLeasePeriod is subid 5 of dot11DHCPIpAddressPoolEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.4.1.5
 * Description:
IP Address Lease Periods.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param IPAddLeasePeriod_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * dot11DHCPIpAddressPoolTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
IPAddLeasePeriod_check_value( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx, long IPAddLeasePeriod_val)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddLeasePeriod_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid IPAddLeasePeriod value.
     */

    return MFD_SUCCESS; /* IPAddLeasePeriod value not illegal */
} /* IPAddLeasePeriod_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (dot11DHCPIpAddressPoolTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * dot11DHCPIpAddressPoolTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
IPAddLeasePeriod_undo_setup( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddLeasePeriod_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup IPAddLeasePeriod undo.
     */
    /*
     * copy IPAddLeasePeriod data
     * set rowreq_ctx->undo->IPAddLeasePeriod from rowreq_ctx->data.IPAddLeasePeriod
     */
    rowreq_ctx->undo->IPAddLeasePeriod = rowreq_ctx->data.IPAddLeasePeriod;


    return MFD_SUCCESS;
} /* IPAddLeasePeriod_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param IPAddLeasePeriod_val
 *        A long containing the new value.
 */
int
IPAddLeasePeriod_set( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx, long IPAddLeasePeriod_val )
{

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddLeasePeriod_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:245:o: |-> Implement IPAddLeasePeriod reverse mapping.
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them here.
 */
    /*
     * TODO:461:M: |-> Set IPAddLeasePeriod value.
     * set IPAddLeasePeriod value in rowreq_ctx->data
     */
	int ret = -1;
	int leasenum = 0;
	char leasestr[30] = { 0 };
	leasenum = IPAddLeasePeriod_val;
	unsigned int index = 0,mode =1;
	snprintf(leasestr, sizeof(leasestr)-1, "%d", leasenum);

	config_ip_pool_name(rowreq_ctx->data.PoolName, &index, rowreq_ctx->data.slot_id);
	ret = ip_dhcp_server_lease_default(leasestr, mode, index, rowreq_ctx->data.slot_id);

	if(ret == 1) {
    	rowreq_ctx->data.IPAddLeasePeriod = IPAddLeasePeriod_val;
	}
	else {
	    return MFD_ERROR;
	}
    return MFD_SUCCESS;
} /* IPAddLeasePeriod_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
IPAddLeasePeriod_undo( dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:dot11DHCPIpAddressPoolTable:IPAddLeasePeriod_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up IPAddLeasePeriod undo.
     */
    /*
     * copy IPAddLeasePeriod data
     * set rowreq_ctx->data.IPAddLeasePeriod from rowreq_ctx->undo->IPAddLeasePeriod
     */
    rowreq_ctx->data.IPAddLeasePeriod = rowreq_ctx->undo->IPAddLeasePeriod;

    
    return MFD_SUCCESS;
} /* IPAddLeasePeriod_undo */

/**
 * check dependencies
 *
 * This is useful for for tables which have dependencies between columns
 * (or rows, or tables). For example, two columns allocating a percentage
 * of something add up 100%.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the FLAG_* bits can be found in
 * dot11DHCPIpAddressPoolTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @retval MFD_SUCCESS all the changes to the row are legal
 * @retval MFD_ERROR   one or more changes are not legal
 *
 * (see README-table-dot11DHCPIpAddressPoolTable if you don't have dependencies)
 */
int
dot11DHCPIpAddressPoolTable_check_dependencies(dot11DHCPIpAddressPoolTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    
    DEBUGMSGTL(("internal:dot11DHCPIpAddressPoolTable:dot11DHCPIpAddressPoolTable_check_dependencies","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:470:o: Check dot11DHCPIpAddressPoolTable row dependencies.
     * check that all new value are legal and consistent with each other
     */
    return rc;
} /* dot11DHCPIpAddressPoolTable_check_dependencies */

/** @} */
