/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef DOT11CONFIGTRAPGROUPTABLE_H
#define DOT11CONFIGTRAPGROUPTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(DOT11-AC-MIB)
config_require(DOT11-AC-MIB/dot11ConfigTrapGroupTable/dot11ConfigTrapGroupTable_interface)
config_require(DOT11-AC-MIB/dot11ConfigTrapGroupTable/dot11ConfigTrapGroupTable_data_access)
config_require(DOT11-AC-MIB/dot11ConfigTrapGroupTable/dot11ConfigTrapGroupTable_data_get)
config_require(DOT11-AC-MIB/dot11ConfigTrapGroupTable/dot11ConfigTrapGroupTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for dot11ConfigTrapGroupTable */
#include "dot11ConfigTrapGroupTable_oids.h"

/* enum definions */
#include "dot11ConfigTrapGroupTable_enums.h"
#include "ws_dbus_list_interface.h"

/* *********************************************************************
 * function declarations
 */
void init_dot11ConfigTrapGroupTable(void);
void shutdown_dot11ConfigTrapGroupTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11ConfigTrapGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * DOT11-AC-MIB::dot11ConfigTrapGroupTable is subid 1 of dot11ConfigTrapGroup.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.19.1, length: 12
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review dot11ConfigTrapGroupTable registration context.
     */
typedef netsnmp_data_list dot11ConfigTrapGroupTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review dot11ConfigTrapGroupTable data context structure.
 * This structure is used to represent the data for dot11ConfigTrapGroupTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * dot11ConfigTrapGroupTable.
 */
typedef struct dot11ConfigTrapGroupTable_data_s {

   dbus_parameter parameter;
    
        /*
         * TrapName(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
   char   TrapName[30];
size_t      TrapName_len; /* # of char elements, not bytes */
    
        /*
         * TrapVersion(3)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   TrapVersion;
    
        /*
         * TrapSourIPAddress(4)/IPADDR/ASN_IPADDRESS/u_long(u_long)//l/A/W/e/r/d/h
         */
   u_long   TrapSourIPAddress;
    
        /*
         * TrapDestIPAddress(5)/IPADDR/ASN_IPADDRESS/u_long(u_long)//l/A/W/e/r/d/h
         */
   u_long   TrapDestIPAddress;
    
        /*
         * TrapCommunity(6)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
   char   TrapCommunity[20];
size_t      TrapCommunity_len; /* # of char elements, not bytes */
    
        /*
         * TrapState(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   TrapState;
    
        /*
         * TrapDestPort(8)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
         */
   long   TrapDestPort;
    
        /*
         * TrapRowStatus(9)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
   u_long   TrapRowStatus;
    
} dot11ConfigTrapGroupTable_data;


/* *********************************************************************
 * TODO:115:o: |-> Review dot11ConfigTrapGroupTable undo context.
 * We're just going to use the same data structure for our
 * undo_context. If you want to do something more efficent,
 * define your typedef here.
 */
typedef dot11ConfigTrapGroupTable_data dot11ConfigTrapGroupTable_undo_data;

/*
 * TODO:120:r: |-> Review dot11ConfigTrapGroupTable mib index.
 * This structure is used to represent the index for dot11ConfigTrapGroupTable.
 */
typedef struct dot11ConfigTrapGroupTable_mib_index_s {

        /*
         * TrapID(1)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/r/d/h
         */
   long   TrapID;


} dot11ConfigTrapGroupTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review dot11ConfigTrapGroupTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_dot11ConfigTrapGroupTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review dot11ConfigTrapGroupTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * dot11ConfigTrapGroupTable_rowreq_ctx pointer.
 */
typedef struct dot11ConfigTrapGroupTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_dot11ConfigTrapGroupTable_IDX_LEN];
    
    dot11ConfigTrapGroupTable_mib_index        tbl_idx;
    
    dot11ConfigTrapGroupTable_data              data;
    dot11ConfigTrapGroupTable_undo_data       * undo;
    unsigned int                column_set_flags; /* flags for set columns */


    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to dot11ConfigTrapGroupTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *dot11ConfigTrapGroupTable_data_list;

} dot11ConfigTrapGroupTable_rowreq_ctx;

typedef struct dot11ConfigTrapGroupTable_ref_rowreq_ctx_s {
    dot11ConfigTrapGroupTable_rowreq_ctx *rowreq_ctx;
} dot11ConfigTrapGroupTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int dot11ConfigTrapGroupTable_pre_request(dot11ConfigTrapGroupTable_registration * user_context);
    int dot11ConfigTrapGroupTable_post_request(dot11ConfigTrapGroupTable_registration * user_context,
        int rc);

    int dot11ConfigTrapGroupTable_rowreq_ctx_init(dot11ConfigTrapGroupTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void dot11ConfigTrapGroupTable_rowreq_ctx_cleanup(dot11ConfigTrapGroupTable_rowreq_ctx *rowreq_ctx);

    int dot11ConfigTrapGroupTable_check_dependencies(dot11ConfigTrapGroupTable_rowreq_ctx * rowreq_ctx); 
    int dot11ConfigTrapGroupTable_commit(dot11ConfigTrapGroupTable_rowreq_ctx * rowreq_ctx);

    dot11ConfigTrapGroupTable_rowreq_ctx *
                  dot11ConfigTrapGroupTable_row_find_by_mib_index(dot11ConfigTrapGroupTable_mib_index *mib_idx);

extern oid dot11ConfigTrapGroupTable_oid[];
extern int dot11ConfigTrapGroupTable_oid_size;


#include "dot11ConfigTrapGroupTable_interface.h"
#include "dot11ConfigTrapGroupTable_data_access.h"
#include "dot11ConfigTrapGroupTable_data_get.h"
#include "dot11ConfigTrapGroupTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* DOT11CONFIGTRAPGROUPTABLE_H */
/** @} */
