/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.32.2.3 $ of : mfd-top.m2c,v $
 *
 * $Id:$
 */
#ifndef DOT11NEWNEIGHBORAPTABLE_H
#define DOT11NEWNEIGHBORAPTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @defgroup misc misc: Miscelaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_require(DOT11-WTP-MIB/dot11NewNeighborAPTable/dot11NewNeighborAPTable_interface);
config_require(DOT11-WTP-MIB/dot11NewNeighborAPTable/dot11NewNeighborAPTable_data_access);
config_require(DOT11-WTP-MIB/dot11NewNeighborAPTable/dot11NewNeighborAPTable_data_get);
config_require(DOT11-WTP-MIB/dot11NewNeighborAPTable/dot11NewNeighborAPTable_data_set);
    /* *INDENT-ON*  */

/* OID and column number definitions for  */
#include "dot11NewNeighborAPTable_oids.h"

/* enum definions */
#include "dot11NewNeighborAPTable_enums.h"
#include "ws_dbus_list_interface.h"

/* *********************************************************************
 * function declarations
 */
void init_dot11NewNeighborAPTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11NewNeighborAPTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11NewNeighborAPTable is subid 2 of wtpNeighbor.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.1.15.2, length: 12
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review dot11NewNeighborAPTable registration context.
     */
typedef netsnmp_data_list * dot11NewNeighborAPTable_registration_ptr;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review dot11NewNeighborAPTable data context structure.
 * This structure is used to represent the data for dot11NewNeighborAPTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * dot11NewNeighborAPTable.
 */
typedef struct dot11NewNeighborAPTable_data_s {
    
        /*
         * NewneighborAPMac(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   NewneighborAPMac[255];
size_t      NewneighborAPMac_len; /* # of char elements, not bytes */
    
        /*
         * NewneighborAPRate(2)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   NewneighborAPRate;
    
        /*
         * NewneighborAPChannel(3)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   NewneighborAPChannel;
    
        /*
         * NewneighborAPRssi(4)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   NewneighborAPRssi;
    
        /*
         * NewneighborAPNoise(5)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   NewneighborAPNoise;
    
        /*
         * NewneighborAPBeaconInterval(6)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   NewneighborAPBeaconInterval;
    
        /*
         * NewneighborAPCapability(7)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   NewneighborAPCapability;
    
        /*
         * NewneighborAPEssid(8)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   NewneighborAPEssid[255];
size_t      NewneighborAPEssid_len; /* # of char elements, not bytes */
    
        /*
         * NewneighborAPElemInfo(9)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   NewneighborAPElemInfo[255];
size_t      NewneighborAPElemInfo_len; /* # of char elements, not bytes */
    
        /*
         * NewneighborAPSignalIntensity(10)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   NewneighborAPSignalIntensity;
    
} dot11NewNeighborAPTable_data;


/*
 * TODO:120:r: |-> Review dot11NewNeighborAPTable mib index.
 * This structure is used to represent the index for dot11NewNeighborAPTable.
 */
typedef struct dot11NewNeighborAPTable_mib_index_s {

        /*
         * wtpMacAddr(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        /** 128 - 2(other indexes) - oid length(14) = 111 */
   char   wtpMacAddr[111];
   size_t      wtpMacAddr_len;

        /*
         * wtpWirelessIfIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   wtpWirelessIfIndex;

        /*
         * neighborAPIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   neighborAPIndex;


} dot11NewNeighborAPTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review dot11NewNeighborAPTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     *
     * BE VERY CAREFUL TO TAKE INTO ACCOUNT THE MAXIMUM
     * POSSIBLE LENGHT FOR EVERY VARIABLE LENGTH INDEX!
     * Guessing 128 - col/entry(2)  - oid len(12)
*/
#define MAX_dot11NewNeighborAPTable_IDX_LEN     114


/* *********************************************************************
 * TODO:130:o: |-> Review dot11NewNeighborAPTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * dot11NewNeighborAPTable_rowreq_ctx pointer.
 */
typedef struct dot11NewNeighborAPTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_dot11NewNeighborAPTable_IDX_LEN];
    
    dot11NewNeighborAPTable_mib_index        tbl_idx;
    
    dot11NewNeighborAPTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * implementor's context pointer (provided during registration)
     */
    dot11NewNeighborAPTable_registration_ptr dot11NewNeighborAPTable_reg;

    /*
     * TODO:131:o: |   |-> Add useful data to dot11NewNeighborAPTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *dot11NewNeighborAPTable_data_list;

} dot11NewNeighborAPTable_rowreq_ctx;

typedef struct dot11NewNeighborAPTable_ref_rowreq_ctx_s {
    dot11NewNeighborAPTable_rowreq_ctx *rowreq_ctx;
} dot11NewNeighborAPTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int dot11NewNeighborAPTable_pre_request(dot11NewNeighborAPTable_registration_ptr user_context);
    int dot11NewNeighborAPTable_post_request(dot11NewNeighborAPTable_registration_ptr user_context);


extern oid dot11NewNeighborAPTable_oid[];
extern int dot11NewNeighborAPTable_oid_size;


#include "dot11NewNeighborAPTable_interface.h"
#include "dot11NewNeighborAPTable_data_access.h"
#include "dot11NewNeighborAPTable_data_get.h"
#include "dot11NewNeighborAPTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* DOT11NEWNEIGHBORAPTABLE_H */
