#ifndef WBMD_MIB_DEF_H
#define WBMD_MIB_DEF_H
extern char WBRIDGE_RM_PROPERTY_INFO_OID[PATH_LEN];
extern char WBRIDGE_IF_INFO_BASIC_OID[PATH_LEN];
extern char WBRIDGE_IF_NUM_OID[PATH_LEN];
extern char WBRIDGE_MINT_INFO_OID[PATH_LEN];
#endif
