/*******************************************************************************
Copyright (C) Autelan Technology


This software file is owned and distributed by Autelan Technology 
********************************************************************************


THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR 
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
********************************************************************************
* nm_errcode.h
*
*
* CREATOR:
* autelan.software.xxx. team
*
* DESCRIPTION:
* xxx module main routine
*
*
*******************************************************************************/

#ifndef _NM_ERRCODE_H
#define _NM_ERRCODE_H

#define NM_TRUE		1
#define NM_FALSE	0

#define NM_RETURN_OK			(0)

#define NM_ERR_BASE			(0)

#define NM_ERR_PBULIC_BASE		(NM_ERR_BASE)
#define NM_BLKMEM_ERR_BASE		(NM_ERR_BASE-500)
#define NM_LOG_ERR_BASE			(NM_ERR_BASE-800)
#define NM_THREAD_ERR_BASE		(NM_ERR_BASE-1500)
#define NM_VRRP_ERR_BASE		(NM_ERR_BASE-5000)
#define NM_HASH_ERR_BASE		(NM_ERR_BASE-6000)
#define NM_DBUS_ERR_BASE		(NM_ERR_BASE-10000)

/*public error!*/
#define NM_ERR_UNKNOWN			(NM_ERR_PBULIC_BASE-1)
#define NM_ERR_INPUT_PARAM_ERR		(NM_ERR_PBULIC_BASE-2)
#define NM_ERR_MALLOC_FAILED		(NM_ERR_PBULIC_BASE-3)
#define NM_ERR_NULL_POINTER		(NM_ERR_PBULIC_BASE-4)
#define NM_ERR_SOCKET_FAILED		(NM_ERR_PBULIC_BASE-5)
#define NM_ERR_SOCKET_BIND_FAILED	(NM_ERR_PBULIC_BASE-6)
#define NM_ERR_SOCKET_SEND_FAILED	(NM_ERR_PBULIC_BASE-7)
#define NM_ERR_SOCKET_RECV_FAILED	(NM_ERR_PBULIC_BASE-8)
#define NM_ERR_SOCKET_OPT_FAILED	(NM_ERR_PBULIC_BASE-9)
#define NM_ERR_FILE_OPEN_FAILED		(NM_ERR_PBULIC_BASE-10)
#define NM_ERR_FILE_READ_FAILED		(NM_ERR_PBULIC_BASE-11)
#define NM_ERR_FILE_WRITE_FAILED	(NM_ERR_PBULIC_BASE-12)
#define NM_ERR_DBUS_FAILED			(NM_ERR_PBULIC_BASE-13)
#define NM_ERR_REG_ERR				(NM_ERR_PBULIC_BASE-14)

/*nm blk mem error!*/
#define NM_BLKMEM_ERR_ITEM_NOT_IN_BLK			(NM_BLKMEM_ERR_BASE-1)
#define NM_BLKMEM_ERR_ILLEGAL_ITEM_POINTER		(NM_BLKMEM_ERR_BASE-2)
#define NM_BLKMEM_ERR_ITEM_NUM_OVER_LIMIT		(NM_BLKMEM_ERR_BASE-3)
#define NM_BLKMEM_ERR_HAS_MAX_BLK_NUM			(NM_BLKMEM_ERR_BASE-4)
#define NM_BLKMEM_ERR_MALLOC_FAILED				(NM_BLKMEM_ERR_BASE-5)
#define NM_BLKMEM_ERR_HAS_ITEM_NOT_FREE			(NM_BLKMEM_ERR_BASE-6)

/*nm log error!*/
#define NM_LOG_ERR_INIT_BLKMEM_FAILED					(NM_LOG_ERR_BASE-1)
#define NM_LOG_ERR_ADD_FILTER_OVER_LENGTH				(NM_LOG_ERR_BASE-2)
#define NM_LOG_ERR_ADD_FILTER_BLK_MALLOC_FAILED			(NM_LOG_ERR_BASE-3)
#define NM_LOG_ERR_ADD_FILTER_ALREADY_HAVE				(NM_LOG_ERR_BASE-4)
#define NM_LOG_ERR_FILER_NOT_FIND						(NM_LOG_ERR_BASE-5)
#define NM_LOG_ERR_ALREADY_SET							(NM_LOG_ERR_BASE-6)
#define NM_LOG_ERR_LEVEL_NOT_MATCH						(NM_LOG_ERR_BASE-7)

/*nm thread error!*/
#define NM_ERR_THREAD_CREATE_FAILED				(NM_THREAD_ERR_BASE-1)

#define NM_ERR_HANSI_IS_BACKUP		(NM_VRRP_ERR_BASE-1)

const char *nm_errcode_content(int errcode);

#endif

