/* drp_def.h */
#ifndef _DRP_DEF_H
#define _DRP_DEF_H

#ifdef  __cplusplus
extern "C" {
#endif


#define DRP_SUCCESS		(0)
#define DRP_FAILURE		(1)

#define DRP_RETURN_OK		(0)
#define DRP_RETURN_ERR		(-1)

#define DRP_ERR_BASE			(0)

#define DRP_PBULIC_ERR_BASE							(DRP_ERR_BASE-100)
#define DRP_DBUS_ERR_BASE							(DRP_ERR_BASE-500)
#define DRP_OPXML_ERR_BASE						(DRP_ERR_BASE-1000)
#define DRP_HANDLE_ERR_BASE						(DRP_ERR_BASE-1500)
#define DRP_DNS_RESOLVE_ERR_BASE					(DRP_ERR_BASE-2000)


/*public error!*/
#define DRP_ERR_UNKNOWN							(DRP_PBULIC_ERR_BASE-1)
#define DRP_ERR_INPUT_PARAM_ERR					(DRP_PBULIC_ERR_BASE-2)
#define DRP_ERR_MALLOC_FAILED						(DRP_PBULIC_ERR_BASE-3)
#define DRP_ERR_NULL_POINTER						(DRP_PBULIC_ERR_BASE-4)
#define DRP_ERR_SOCKET_FAILED						(DRP_PBULIC_ERR_BASE-5)
#define DRP_ERR_SOCKET_BIND_FAILED					(DRP_PBULIC_ERR_BASE-6)
#define DRP_ERR_SOCKET_SEND_FAILED				(DRP_PBULIC_ERR_BASE-7)
#define DRP_ERR_SOCKET_RECV_FAILED					(DRP_PBULIC_ERR_BASE-8)
#define DRP_ERR_SOCKET_OPT_FAILED					(DRP_PBULIC_ERR_BASE-9)
#define DRP_ERR_FILE_OPEN_FAILED					(DRP_PBULIC_ERR_BASE-10)
#define DRP_ERR_FILE_READ_FAILED					(DRP_PBULIC_ERR_BASE-11)
#define DRP_ERR_FILE_WRITE_FAILED					(DRP_PBULIC_ERR_BASE-12)
#define DRP_ERR_DBUS_FAILED						(DRP_PBULIC_ERR_BASE-13)
#define DRP_ERR_REG_ERR								(DRP_PBULIC_ERR_BASE-14)
#define DRP_ERR_REMOTE_DBUS_CONNECT_FAILED		(DRP_PBULIC_ERR_BASE-15)




#define DRP_ERR_OPXML_FILE_NOT_EXIST				(DRP_OPXML_ERR_BASE-1)
#define DRP_ERR_OPXML_FILE_FORMAT_WRONG			(DRP_OPXML_ERR_BASE-2)

#define DRP_ERR_HANDLE_XML_DOMAIN_IP_EMPTY		(DRP_HANDLE_ERR_BASE-1)

#define DRP_ERR_DNS_RESOLVE_PARAM_INPUT			(DRP_DNS_RESOLVE_ERR_BASE-1)
#define DRP_ERR_DNS_RESOLVE_DOMAIN_EXIST			(DRP_DNS_RESOLVE_ERR_BASE-2)
#define DRP_ERR_DNS_SERVER_NOT_CONFIGED			(DRP_DNS_RESOLVE_ERR_BASE-3)
#define DRP_ERR_DNS_RESOLVE_FAILED					(DRP_DNS_RESOLVE_ERR_BASE-4)
#define DRP_ERR_DNS_RESULT_WRITE_XML_FAILED		(DRP_DNS_RESOLVE_ERR_BASE-5)
#define DRP_ERR_DNS_DOMAIN_NOT_EXIST				(DRP_DNS_RESOLVE_ERR_BASE-6)
#define DRP_ERR_DNS_DOMAIN_IP_NOT_EXIST			(DRP_DNS_RESOLVE_ERR_BASE-7)
#define DRP_ERR_DNS_RESOLVE_IP_FORMAT_WRONG	(DRP_DNS_RESOLVE_ERR_BASE-8)
#define DRP_ERR_DNS_RESULT_XML_FORMAT_WRIONG	(DRP_DNS_RESOLVE_ERR_BASE-9)


#ifdef  __cplusplus
}
#endif
#endif				/* _DRP_DEF_H */
