/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18.2.1 $ of : mfd-data-get.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot11SSIDRateStatsTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dot11SSIDRateStatsTable get routines.
 * TODO:240:M: Implement dot11SSIDRateStatsTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11SSIDRateStatsTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11SSIDRateStatsTable is subid 8 of wtpWlan.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.1.5.8, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement dot11SSIDRateStatsTable data context functions.
 */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11ConfigTrapSwitchEntry.wtpMacAddr
 * wtpMacAddr is subid 1 of dot11ConfigTrapSwitchEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.2.18.2.1.1
 * Description:
AP Mac  Address Group.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-wtpMacAddr.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
wtpMacAddr_dot11SSIDRateStatsTable_map(char **mib_wtpMacAddr_val_ptr_ptr, size_t *mib_wtpMacAddr_val_ptr_len_ptr, char *raw_wtpMacAddr_val_ptr, size_t raw_wtpMacAddr_val_ptr_len, int allow_realloc)
{
    int converted_len;

    netsnmp_assert(NULL != raw_wtpMacAddr_val_ptr);
    netsnmp_assert((NULL != mib_wtpMacAddr_val_ptr_ptr) && (NULL != mib_wtpMacAddr_val_ptr_len_ptr));
    
    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:wtpMacAddr_map","called\n"));
    
    /*
     * TODO:241:r: |-> Implement wtpMacAddr non-integer mapping
     * it is hard to autogenerate code for mapping types that are not simple
     * integers, so here is an idea of what you might need to do. It will
     * probably need some tweaking to get right.
     */
    /*
     * if the length of the raw data doesn't directly correspond with
     * the length of the mib data, set converted_len to the
     * space required.
     */
    converted_len = raw_wtpMacAddr_val_ptr_len; /* assume equal */
    if((NULL == *mib_wtpMacAddr_val_ptr_ptr) || (*mib_wtpMacAddr_val_ptr_len_ptr < converted_len)) {
        if(! allow_realloc) {
            snmp_log(LOG_ERR,"not enough space for value mapping\n");
            return SNMP_ERR_GENERR;
        }
        *mib_wtpMacAddr_val_ptr_ptr = realloc( *mib_wtpMacAddr_val_ptr_ptr, converted_len * sizeof(**mib_wtpMacAddr_val_ptr_ptr));
        if(NULL == *mib_wtpMacAddr_val_ptr_ptr) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return SNMP_ERR_GENERR;
        }
    }
    *mib_wtpMacAddr_val_ptr_len_ptr = converted_len;
    memcpy( *mib_wtpMacAddr_val_ptr_ptr, raw_wtpMacAddr_val_ptr, converted_len );

    return MFD_SUCCESS;
} /* wtpMacAddr_map */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11WtpWlanStatsEntry.wlanCurrID
 * wlanCurrID is subid 1 of dot11WtpWlanStatsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.5.3.1.1
 * Description:
The wlan's ID.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-wlanCurrID.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
wlanCurrID_dot11SSIDRateStatsTable_map(long *mib_wlanCurrID_val_ptr, long raw_wlanCurrID_val)
{
    netsnmp_assert(NULL != mib_wlanCurrID_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:wlanCurrID_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement wlanCurrID mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_wlanCurrID_val_ptr) = raw_wlanCurrID_val;

    return MFD_SUCCESS;
} /* wlanCurrID_map */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dot11SSIDRateStatsTable_indexes_set_tbl_idx(dot11SSIDRateStatsTable_mib_index *tbl_idx, char *wtpMacAddr_val_ptr,  size_t wtpMacAddr_val_ptr_len, long wlanCurrID_val)
{
    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:dot11SSIDRateStatsTable_indexes_set_tbl_idx","called\n"));

    /* wtpMacAddr(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
     tbl_idx->wtpMacAddr_len = sizeof(tbl_idx->wtpMacAddr);
    /*
     * make sure there is enough space for wtpMacAddr data
     */
    if ((NULL == tbl_idx->wtpMacAddr) ||
        (tbl_idx->wtpMacAddr_len < (wtpMacAddr_val_ptr_len * sizeof(tbl_idx->wtpMacAddr[0])))) {
        snmp_log(LOG_ERR,"not enough space for value\n");
        return MFD_ERROR;
    }
    tbl_idx->wtpMacAddr_len = wtpMacAddr_val_ptr_len * sizeof(tbl_idx->wtpMacAddr[0]);
    memcpy( tbl_idx->wtpMacAddr, wtpMacAddr_val_ptr, tbl_idx->wtpMacAddr_len );
    
    /* wlanCurrID(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    tbl_idx->wlanCurrID = wlanCurrID_val;
    

    return MFD_SUCCESS;
} /* dot11SSIDRateStatsTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dot11SSIDRateStatsTable_indexes_set(dot11SSIDRateStatsTable_rowreq_ctx *rowreq_ctx, char *wtpMacAddr_val_ptr,  size_t wtpMacAddr_val_ptr_len, long wlanCurrID_val)
{
    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:dot11SSIDRateStatsTable_indexes_set","called\n"));

    if(MFD_SUCCESS != dot11SSIDRateStatsTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , wtpMacAddr_val_ptr, wtpMacAddr_val_ptr_len
                                   , wlanCurrID_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != dot11SSIDRateStatsTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* dot11SSIDRateStatsTable_indexes_set */


/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11SSIDRateStatsEntry.SSIDInDropRate
 * SSIDInDropRate is subid 1 of dot11SSIDRateStatsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.5.8.1.1
 * Description:
The total number of in Drop Rate.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-SSIDInDropRate.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
SSIDInDropRate_map(char **mib_SSIDInDropRate_val_ptr_ptr, size_t *mib_SSIDInDropRate_val_ptr_len_ptr, char *raw_SSIDInDropRate_val_ptr, size_t raw_SSIDInDropRate_val_ptr_len, int allow_realloc)
{
    int converted_len;

    netsnmp_assert(NULL != raw_SSIDInDropRate_val_ptr);
    netsnmp_assert((NULL != mib_SSIDInDropRate_val_ptr_ptr) && (NULL != mib_SSIDInDropRate_val_ptr_len_ptr));
    
    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:SSIDInDropRate_map","called\n"));
    
    /*
     * TODO:241:r: |-> Implement SSIDInDropRate non-integer mapping
     * it is hard to autogenerate code for mapping types that are not simple
     * integers, so here is an idea of what you might need to do. It will
     * probably need some tweaking to get right.
     */
    /*
     * if the length of the raw data doesn't directly correspond with
     * the length of the mib data, set converted_len to the
     * space required.
     */
    converted_len = raw_SSIDInDropRate_val_ptr_len; /* assume equal */
    if((NULL == *mib_SSIDInDropRate_val_ptr_ptr) || (*mib_SSIDInDropRate_val_ptr_len_ptr < converted_len)) {
        if(! allow_realloc) {
            snmp_log(LOG_ERR,"not enough space for value mapping\n");
            return SNMP_ERR_GENERR;
        }
        *mib_SSIDInDropRate_val_ptr_ptr = realloc( *mib_SSIDInDropRate_val_ptr_ptr, converted_len * sizeof(**mib_SSIDInDropRate_val_ptr_ptr));
        if(NULL == *mib_SSIDInDropRate_val_ptr_ptr) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return SNMP_ERR_GENERR;
        }
    }
    *mib_SSIDInDropRate_val_ptr_len_ptr = converted_len;
    memcpy( *mib_SSIDInDropRate_val_ptr_ptr, raw_SSIDInDropRate_val_ptr, converted_len );

    return MFD_SUCCESS;
} /* SSIDInDropRate_map */

/**
 * Extract the current value of the SSIDInDropRate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param SSIDInDropRate_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param SSIDInDropRate_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by SSIDInDropRate.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*SSIDInDropRate_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update SSIDInDropRate_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
SSIDInDropRate_get( dot11SSIDRateStatsTable_rowreq_ctx *rowreq_ctx, char **SSIDInDropRate_val_ptr_ptr, size_t *SSIDInDropRate_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != SSIDInDropRate_val_ptr_ptr) && (NULL != *SSIDInDropRate_val_ptr_ptr));
   netsnmp_assert( NULL != SSIDInDropRate_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:SSIDInDropRate_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the SSIDInDropRate data.
 * set (* SSIDInDropRate_val_ptr_ptr ) and (* SSIDInDropRate_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for SSIDInDropRate data
     */
    if ((NULL == (* SSIDInDropRate_val_ptr_ptr )) ||
        ((* SSIDInDropRate_val_ptr_len_ptr ) < (rowreq_ctx->data.SSIDInDropRate_len * sizeof((* SSIDInDropRate_val_ptr_ptr )[0])))) {
        /*
         * allocate space for SSIDInDropRate data
         */
        (* SSIDInDropRate_val_ptr_ptr ) = malloc(rowreq_ctx->data.SSIDInDropRate_len * sizeof((* SSIDInDropRate_val_ptr_ptr )[0]));
        if(NULL == (* SSIDInDropRate_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* SSIDInDropRate_val_ptr_len_ptr ) = rowreq_ctx->data.SSIDInDropRate_len * sizeof((* SSIDInDropRate_val_ptr_ptr )[0]);
    memcpy( (* SSIDInDropRate_val_ptr_ptr ), rowreq_ctx->data.SSIDInDropRate, (* SSIDInDropRate_val_ptr_len_ptr ) );

    return MFD_SUCCESS;
} /* SSIDInDropRate_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11SSIDRateStatsEntry.SSIDOutDropRate
 * SSIDOutDropRate is subid 2 of dot11SSIDRateStatsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.5.8.1.2
 * Description:
The total number of out drop  Rate.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-SSIDOutDropRate.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
SSIDOutDropRate_map(char **mib_SSIDOutDropRate_val_ptr_ptr, size_t *mib_SSIDOutDropRate_val_ptr_len_ptr, char *raw_SSIDOutDropRate_val_ptr, size_t raw_SSIDOutDropRate_val_ptr_len, int allow_realloc)
{
    int converted_len;

    netsnmp_assert(NULL != raw_SSIDOutDropRate_val_ptr);
    netsnmp_assert((NULL != mib_SSIDOutDropRate_val_ptr_ptr) && (NULL != mib_SSIDOutDropRate_val_ptr_len_ptr));
    
    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:SSIDOutDropRate_map","called\n"));
    
    /*
     * TODO:241:r: |-> Implement SSIDOutDropRate non-integer mapping
     * it is hard to autogenerate code for mapping types that are not simple
     * integers, so here is an idea of what you might need to do. It will
     * probably need some tweaking to get right.
     */
    /*
     * if the length of the raw data doesn't directly correspond with
     * the length of the mib data, set converted_len to the
     * space required.
     */
    converted_len = raw_SSIDOutDropRate_val_ptr_len; /* assume equal */
    if((NULL == *mib_SSIDOutDropRate_val_ptr_ptr) || (*mib_SSIDOutDropRate_val_ptr_len_ptr < converted_len)) {
        if(! allow_realloc) {
            snmp_log(LOG_ERR,"not enough space for value mapping\n");
            return SNMP_ERR_GENERR;
        }
        *mib_SSIDOutDropRate_val_ptr_ptr = realloc( *mib_SSIDOutDropRate_val_ptr_ptr, converted_len * sizeof(**mib_SSIDOutDropRate_val_ptr_ptr));
        if(NULL == *mib_SSIDOutDropRate_val_ptr_ptr) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return SNMP_ERR_GENERR;
        }
    }
    *mib_SSIDOutDropRate_val_ptr_len_ptr = converted_len;
    memcpy( *mib_SSIDOutDropRate_val_ptr_ptr, raw_SSIDOutDropRate_val_ptr, converted_len );

    return MFD_SUCCESS;
} /* SSIDOutDropRate_map */

/**
 * Extract the current value of the SSIDOutDropRate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param SSIDOutDropRate_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param SSIDOutDropRate_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by SSIDOutDropRate.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*SSIDOutDropRate_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update SSIDOutDropRate_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
SSIDOutDropRate_get( dot11SSIDRateStatsTable_rowreq_ctx *rowreq_ctx, char **SSIDOutDropRate_val_ptr_ptr, size_t *SSIDOutDropRate_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != SSIDOutDropRate_val_ptr_ptr) && (NULL != *SSIDOutDropRate_val_ptr_ptr));
   netsnmp_assert( NULL != SSIDOutDropRate_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:SSIDOutDropRate_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the SSIDOutDropRate data.
 * set (* SSIDOutDropRate_val_ptr_ptr ) and (* SSIDOutDropRate_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for SSIDOutDropRate data
     */
    if ((NULL == (* SSIDOutDropRate_val_ptr_ptr )) ||
        ((* SSIDOutDropRate_val_ptr_len_ptr ) < (rowreq_ctx->data.SSIDOutDropRate_len * sizeof((* SSIDOutDropRate_val_ptr_ptr )[0])))) {
        /*
         * allocate space for SSIDOutDropRate data
         */
        (* SSIDOutDropRate_val_ptr_ptr ) = malloc(rowreq_ctx->data.SSIDOutDropRate_len * sizeof((* SSIDOutDropRate_val_ptr_ptr )[0]));
        if(NULL == (* SSIDOutDropRate_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* SSIDOutDropRate_val_ptr_len_ptr ) = rowreq_ctx->data.SSIDOutDropRate_len * sizeof((* SSIDOutDropRate_val_ptr_ptr )[0]);
    memcpy( (* SSIDOutDropRate_val_ptr_ptr ), rowreq_ctx->data.SSIDOutDropRate, (* SSIDOutDropRate_val_ptr_len_ptr ) );

    return MFD_SUCCESS;
} /* SSIDOutDropRate_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11SSIDRateStatsEntry.SSIDDownBandWidthRate
 * SSIDDownBandWidthRate is subid 3 of dot11SSIDRateStatsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.5.8.1.3
 * Description:
The total number of Down BandWidth Rate .
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-SSIDDownBandWidthRate.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
SSIDDownBandWidthRate_map(char **mib_SSIDDownBandWidthRate_val_ptr_ptr, size_t *mib_SSIDDownBandWidthRate_val_ptr_len_ptr, char *raw_SSIDDownBandWidthRate_val_ptr, size_t raw_SSIDDownBandWidthRate_val_ptr_len, int allow_realloc)
{
    int converted_len;

    netsnmp_assert(NULL != raw_SSIDDownBandWidthRate_val_ptr);
    netsnmp_assert((NULL != mib_SSIDDownBandWidthRate_val_ptr_ptr) && (NULL != mib_SSIDDownBandWidthRate_val_ptr_len_ptr));
    
    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:SSIDDownBandWidthRate_map","called\n"));
    
    /*
     * TODO:241:r: |-> Implement SSIDDownBandWidthRate non-integer mapping
     * it is hard to autogenerate code for mapping types that are not simple
     * integers, so here is an idea of what you might need to do. It will
     * probably need some tweaking to get right.
     */
    /*
     * if the length of the raw data doesn't directly correspond with
     * the length of the mib data, set converted_len to the
     * space required.
     */
    converted_len = raw_SSIDDownBandWidthRate_val_ptr_len; /* assume equal */
    if((NULL == *mib_SSIDDownBandWidthRate_val_ptr_ptr) || (*mib_SSIDDownBandWidthRate_val_ptr_len_ptr < converted_len)) {
        if(! allow_realloc) {
            snmp_log(LOG_ERR,"not enough space for value mapping\n");
            return SNMP_ERR_GENERR;
        }
        *mib_SSIDDownBandWidthRate_val_ptr_ptr = realloc( *mib_SSIDDownBandWidthRate_val_ptr_ptr, converted_len * sizeof(**mib_SSIDDownBandWidthRate_val_ptr_ptr));
        if(NULL == *mib_SSIDDownBandWidthRate_val_ptr_ptr) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return SNMP_ERR_GENERR;
        }
    }
    *mib_SSIDDownBandWidthRate_val_ptr_len_ptr = converted_len;
    memcpy( *mib_SSIDDownBandWidthRate_val_ptr_ptr, raw_SSIDDownBandWidthRate_val_ptr, converted_len );

    return MFD_SUCCESS;
} /* SSIDDownBandWidthRate_map */

/**
 * Extract the current value of the SSIDDownBandWidthRate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param SSIDDownBandWidthRate_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param SSIDDownBandWidthRate_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by SSIDDownBandWidthRate.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*SSIDDownBandWidthRate_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update SSIDDownBandWidthRate_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
SSIDDownBandWidthRate_get( dot11SSIDRateStatsTable_rowreq_ctx *rowreq_ctx, char **SSIDDownBandWidthRate_val_ptr_ptr, size_t *SSIDDownBandWidthRate_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != SSIDDownBandWidthRate_val_ptr_ptr) && (NULL != *SSIDDownBandWidthRate_val_ptr_ptr));
   netsnmp_assert( NULL != SSIDDownBandWidthRate_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:SSIDDownBandWidthRate_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the SSIDDownBandWidthRate data.
 * set (* SSIDDownBandWidthRate_val_ptr_ptr ) and (* SSIDDownBandWidthRate_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for SSIDDownBandWidthRate data
     */
    if ((NULL == (* SSIDDownBandWidthRate_val_ptr_ptr )) ||
        ((* SSIDDownBandWidthRate_val_ptr_len_ptr ) < (rowreq_ctx->data.SSIDDownBandWidthRate_len * sizeof((* SSIDDownBandWidthRate_val_ptr_ptr )[0])))) {
        /*
         * allocate space for SSIDDownBandWidthRate data
         */
        (* SSIDDownBandWidthRate_val_ptr_ptr ) = malloc(rowreq_ctx->data.SSIDDownBandWidthRate_len * sizeof((* SSIDDownBandWidthRate_val_ptr_ptr )[0]));
        if(NULL == (* SSIDDownBandWidthRate_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* SSIDDownBandWidthRate_val_ptr_len_ptr ) = rowreq_ctx->data.SSIDDownBandWidthRate_len * sizeof((* SSIDDownBandWidthRate_val_ptr_ptr )[0]);
    memcpy( (* SSIDDownBandWidthRate_val_ptr_ptr ), rowreq_ctx->data.SSIDDownBandWidthRate, (* SSIDDownBandWidthRate_val_ptr_len_ptr ) );

    return MFD_SUCCESS;
} /* SSIDDownBandWidthRate_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11SSIDRateStatsEntry.SSIDUpBandWidthRate
 * SSIDUpBandWidthRate is subid 4 of dot11SSIDRateStatsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.5.8.1.4
 * Description:
The total number of up BandWidth Rate .
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-SSIDUpBandWidthRate.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
SSIDUpBandWidthRate_map(char **mib_SSIDUpBandWidthRate_val_ptr_ptr, size_t *mib_SSIDUpBandWidthRate_val_ptr_len_ptr, char *raw_SSIDUpBandWidthRate_val_ptr, size_t raw_SSIDUpBandWidthRate_val_ptr_len, int allow_realloc)
{
    int converted_len;

    netsnmp_assert(NULL != raw_SSIDUpBandWidthRate_val_ptr);
    netsnmp_assert((NULL != mib_SSIDUpBandWidthRate_val_ptr_ptr) && (NULL != mib_SSIDUpBandWidthRate_val_ptr_len_ptr));
    
    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:SSIDUpBandWidthRate_map","called\n"));
    
    /*
     * TODO:241:r: |-> Implement SSIDUpBandWidthRate non-integer mapping
     * it is hard to autogenerate code for mapping types that are not simple
     * integers, so here is an idea of what you might need to do. It will
     * probably need some tweaking to get right.
     */
    /*
     * if the length of the raw data doesn't directly correspond with
     * the length of the mib data, set converted_len to the
     * space required.
     */
    converted_len = raw_SSIDUpBandWidthRate_val_ptr_len; /* assume equal */
    if((NULL == *mib_SSIDUpBandWidthRate_val_ptr_ptr) || (*mib_SSIDUpBandWidthRate_val_ptr_len_ptr < converted_len)) {
        if(! allow_realloc) {
            snmp_log(LOG_ERR,"not enough space for value mapping\n");
            return SNMP_ERR_GENERR;
        }
        *mib_SSIDUpBandWidthRate_val_ptr_ptr = realloc( *mib_SSIDUpBandWidthRate_val_ptr_ptr, converted_len * sizeof(**mib_SSIDUpBandWidthRate_val_ptr_ptr));
        if(NULL == *mib_SSIDUpBandWidthRate_val_ptr_ptr) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return SNMP_ERR_GENERR;
        }
    }
    *mib_SSIDUpBandWidthRate_val_ptr_len_ptr = converted_len;
    memcpy( *mib_SSIDUpBandWidthRate_val_ptr_ptr, raw_SSIDUpBandWidthRate_val_ptr, converted_len );

    return MFD_SUCCESS;
} /* SSIDUpBandWidthRate_map */

/**
 * Extract the current value of the SSIDUpBandWidthRate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param SSIDUpBandWidthRate_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param SSIDUpBandWidthRate_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by SSIDUpBandWidthRate.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*SSIDUpBandWidthRate_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update SSIDUpBandWidthRate_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
SSIDUpBandWidthRate_get( dot11SSIDRateStatsTable_rowreq_ctx *rowreq_ctx, char **SSIDUpBandWidthRate_val_ptr_ptr, size_t *SSIDUpBandWidthRate_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != SSIDUpBandWidthRate_val_ptr_ptr) && (NULL != *SSIDUpBandWidthRate_val_ptr_ptr));
   netsnmp_assert( NULL != SSIDUpBandWidthRate_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11SSIDRateStatsTable:SSIDUpBandWidthRate_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the SSIDUpBandWidthRate data.
 * set (* SSIDUpBandWidthRate_val_ptr_ptr ) and (* SSIDUpBandWidthRate_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for SSIDUpBandWidthRate data
     */
    if ((NULL == (* SSIDUpBandWidthRate_val_ptr_ptr )) ||
        ((* SSIDUpBandWidthRate_val_ptr_len_ptr ) < (rowreq_ctx->data.SSIDUpBandWidthRate_len * sizeof((* SSIDUpBandWidthRate_val_ptr_ptr )[0])))) {
        /*
         * allocate space for SSIDUpBandWidthRate data
         */
        (* SSIDUpBandWidthRate_val_ptr_ptr ) = malloc(rowreq_ctx->data.SSIDUpBandWidthRate_len * sizeof((* SSIDUpBandWidthRate_val_ptr_ptr )[0]));
        if(NULL == (* SSIDUpBandWidthRate_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* SSIDUpBandWidthRate_val_ptr_len_ptr ) = rowreq_ctx->data.SSIDUpBandWidthRate_len * sizeof((* SSIDUpBandWidthRate_val_ptr_ptr )[0]);
    memcpy( (* SSIDUpBandWidthRate_val_ptr_ptr ), rowreq_ctx->data.SSIDUpBandWidthRate, (* SSIDUpBandWidthRate_val_ptr_len_ptr ) );

    return MFD_SUCCESS;
} /* SSIDUpBandWidthRate_get */



/** @} */
