/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-IEs"
 * 	found in "RUA-IEs.asn"
 */

#ifndef	_CN_DomainIndicator_H_
#define	_CN_DomainIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CN_DomainIndicator {
	CN_DomainIndicator_cs_domain	= 0,
	CN_DomainIndicator_ps_domain	= 1
} e_CN_DomainIndicator;

/* CN-DomainIndicator */
typedef ENUMERATED_t	 CN_DomainIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CN_DomainIndicator;
asn_struct_free_f CN_DomainIndicator_free;
asn_struct_print_f CN_DomainIndicator_print;
asn_constr_check_f CN_DomainIndicator_constraint;
ber_type_decoder_f CN_DomainIndicator_decode_ber;
der_type_encoder_f CN_DomainIndicator_encode_der;
xer_type_decoder_f CN_DomainIndicator_decode_xer;
xer_type_encoder_f CN_DomainIndicator_encode_xer;
per_type_decoder_f CN_DomainIndicator_decode_uper;
per_type_encoder_f CN_DomainIndicator_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CN_DomainIndicator_H_ */
#include <asn_internal.h>
