/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RUA-PDU-Descriptions"
 * 	found in "RUA-PDU-Descriptions.asn"
 */

#ifndef	_RUA_PDU_H_
#define	_RUA_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitiatingMessage.h"
#include "SuccessfulOutcome.h"
#include "UnsuccessfulOutcome.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RUA_PDU_PR {
	RUA_PDU_PR_NOTHING,	/* No components present */
	RUA_PDU_PR_initiatingMessage,
	RUA_PDU_PR_successfulOutcome,
	RUA_PDU_PR_unsuccessfulOutcome,
	/* Extensions may appear below */
	
} RUA_PDU_PR;

/* RUA-PDU */
typedef struct RUA_PDU {
	RUA_PDU_PR present;
	union RUA_PDU_u {
		InitiatingMessage_t	 initiatingMessage;
		SuccessfulOutcome_t	 successfulOutcome;
		UnsuccessfulOutcome_t	 unsuccessfulOutcome;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RUA_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RUA_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _RUA_PDU_H_ */
#include <asn_internal.h>
