/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-IEs"
 * 	found in "../asn/HNBAP-IEs.asn"
 */

#include "PTMSIRAI.h"

static asn_TYPE_member_t asn_MBR_PTMSIRAI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PTMSIRAI, pTMSI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PTMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"pTMSI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PTMSIRAI, rAI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rAI"
		},
};
static ber_tlv_tag_t asn_DEF_PTMSIRAI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PTMSIRAI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pTMSI at 316 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rAI at 317 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PTMSIRAI_specs_1 = {
	sizeof(struct PTMSIRAI),
	offsetof(struct PTMSIRAI, _asn_ctx),
	asn_MAP_PTMSIRAI_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PTMSIRAI = {
	"PTMSIRAI",
	"PTMSIRAI",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PTMSIRAI_tags_1,
	sizeof(asn_DEF_PTMSIRAI_tags_1)
		/sizeof(asn_DEF_PTMSIRAI_tags_1[0]), /* 1 */
	asn_DEF_PTMSIRAI_tags_1,	/* Same as above */
	sizeof(asn_DEF_PTMSIRAI_tags_1)
		/sizeof(asn_DEF_PTMSIRAI_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PTMSIRAI_1,
	2,	/* Elements count */
	&asn_SPC_PTMSIRAI_specs_1	/* Additional specs */
};

