/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "HNBAP-Containers"
 * 	found in "../asn/HNBAP-Containers.asn"
 */

#ifndef	_HNBAP_ProtocolIE_Container_H_
#define	_HNBAP_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "ProtocolIE-ID.h"
#include "Criticality.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Member_ProtocolIE_Container {
		ProtocolIE_ID_t	 id;
		Criticality_t	 criticality;
		ANY_t	 value;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
}Member_ProtocolIE_Container_t;

#if 0
/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_110P0 {
	A_SEQUENCE_OF(Member_ProtocolIE_Container_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_110P0_t;
#endif
/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_110P0 {
	struct {
		Member_ProtocolIE_Container_t **array;
		int count;/* Meaningful size */
		int size; /* Allocated size */
		void (*free)(Member_ProtocolIE_Container_t *);
	}list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_110P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_110P0;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
