/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef DOT11SSIDVLANTABLE_OIDS_H
#define DOT11SSIDVLANTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot11SSIDVlanTable */
//#define DOT11SSIDVLANTABLE_OID              1,3,6,1,4,1,31656,6,1,2,12,3

#define COLUMN_WTPID         1
#define COLUMN_WTPID_FLAG    (0x1 << 0)
    
#define COLUMN_WLANID         2
#define COLUMN_WLANID_FLAG    (0x1 << 1)
    
#define COLUMN_VLANID         3
#define COLUMN_VLANID_FLAG    (0x1 << 2)
    
#define COLUMN_VLANROWSTATUS         4
#define COLUMN_VLANROWSTATUS_FLAG    (0x1 << 3)
    
#define COLUMN_WTPMACADDRESS         5
    
#define COLUMN_WLANSSID         6
    

#define DOT11SSIDVLANTABLE_MIN_COL   COLUMN_WTPID
#define DOT11SSIDVLANTABLE_MAX_COL   COLUMN_WLANSSID
    

    /*
     * TODO:405:r: Review DOT11SSIDVLANTABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define DOT11SSIDVLANTABLE_SETTABLE_COLS (COLUMN_WTPID_FLAG | COLUMN_WLANID_FLAG | COLUMN_VLANID_FLAG | COLUMN_VLANROWSTATUS_FLAG)
    /*
     * TODO:405:r: Review DOT11SSIDVLANTABLE_REQUIRED_COLS macro.
     * OR together all the required rows for row creation.
     * default is writable cols w/out defaults.
     */
#define DOT11SSIDVLANTABLE_REQUIRED_COLS (COLUMN_WTPID_FLAG | COLUMN_WLANID_FLAG | COLUMN_VLANID_FLAG | COLUMN_VLANROWSTATUS_FLAG)
    

#ifdef __cplusplus
}
#endif

#endif /* DOT11SSIDVLANTABLE_OIDS_H */
