/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18.2.1 $ of : mfd-data-get.m2c,v $
 *
 * $Id:$
 *
 * @file dot11WlanStationTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT11WLANSTATIONTABLE_DATA_GET_H
#define DOT11WLANSTATIONTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11WlanStationTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11WlanStationTable is subid 3 of dot11wlanConfig.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.13.3, length: 12
*/
    /*
     * indexes
     */
    int wlanID_map(long *mib_wlanID_val_ptr, long raw_wlanID_val);
    int StaMacAddr_map(char **mib_StaMacAddr_val_ptr_ptr, size_t *mib_StaMacAddr_val_ptr_len_ptr, char *raw_StaMacAddr_val_ptr, size_t raw_StaMacAddr_val_ptr_len, int allow_realloc);

    int StaOnlineTime_map(u_long *mib_StaOnlineTime_val_ptr, u_long raw_StaOnlineTime_val);
    int StaOnlineTime_get( dot11WlanStationTable_rowreq_ctx *rowreq_ctx, u_long * StaOnlineTime_val_ptr );
    int StaAccessTime_map(char **mib_StaAccessTime_val_ptr_ptr, size_t *mib_StaAccessTime_val_ptr_len_ptr, char *raw_StaAccessTime_val_ptr, size_t raw_StaAccessTime_val_ptr_len, int allow_realloc);
    int StaAccessTime_get( dot11WlanStationTable_rowreq_ctx *rowreq_ctx, char **StaAccessTime_val_ptr_ptr, size_t *StaAccessTime_val_ptr_len_ptr );
    int StaUplinkTrafficLimitThreshold_map(long *mib_StaUplinkTrafficLimitThreshold_val_ptr, long raw_StaUplinkTrafficLimitThreshold_val);
    int StaUplinkTrafficLimitThreshold_get( dot11WlanStationTable_rowreq_ctx *rowreq_ctx, long * StaUplinkTrafficLimitThreshold_val_ptr );
    int StaDownlinkTrafficLimitThreshold_map(long *mib_StaDownlinkTrafficLimitThreshold_val_ptr, long raw_StaDownlinkTrafficLimitThreshold_val);
    int StaDownlinkTrafficLimitThreshold_get( dot11WlanStationTable_rowreq_ctx *rowreq_ctx, long * StaDownlinkTrafficLimitThreshold_val_ptr );
    int StaUplinkBitRate_map(unsigned long long *mib_StaUplinkBitRate_val_ptr, unsigned long long raw_StaUplinkBitRate_val);
    int StaUplinkBitRate_get( dot11WlanStationTable_rowreq_ctx *rowreq_ctx, unsigned long long * StaUplinkBitRate_val_ptr );
    int StaDownlinkBitRate_map(unsigned long long *mib_StaDownlinkBitRate_val_ptr, unsigned long long raw_StaDownlinkBitRate_val);
    int StaDownlinkBitRate_get( dot11WlanStationTable_rowreq_ctx *rowreq_ctx, unsigned long long * StaDownlinkBitRate_val_ptr );


int dot11WlanStationTable_indexes_set_tbl_idx(dot11WlanStationTable_mib_index *tbl_idx, long wlanID_val, char *StaMacAddr_val_ptr,  size_t StaMacAddr_val_ptr_len);
int dot11WlanStationTable_indexes_set(dot11WlanStationTable_rowreq_ctx *rowreq_ctx, long wlanID_val, char *StaMacAddr_val_ptr,  size_t StaMacAddr_val_ptr_len);




#ifdef __cplusplus
}
#endif

#endif /* DOT11WLANSTATIONTABLE_DATA_GET_H */
/** @} */
