/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef DOT11DHCPUSEAGETABLE_OIDS_H
#define DOT11DHCPUSEAGETABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot11DHCPUseageTable */
//#define DOT11DHCPUSEAGETABLE_OID              1,3,6,1,4,1,31656,6,1,2,6,6

#define COLUMN_DHCPUSEID         1
    
#define COLUMN_DHCPOOLNAME         2
    
#define COLUMN_DHCPOOLUSEAGE         3
    
#define COLUMN_DHCPMAXLIMIT         4
#define COLUMN_DHCPMAXLIMIT_FLAG    (0x1 << 3)
    
#define COLUMN_DHCPREQNUM         5
    
#define COLUMN_DHCPRESPONSE         6
    
#define COLUMN_DHCPDISCOVERYNUM         7
    
#define COLUMN_DHCPOFFERNUM         8
    

#define DOT11DHCPUSEAGETABLE_MIN_COL   COLUMN_DHCPUSEID
#define DOT11DHCPUSEAGETABLE_MAX_COL   COLUMN_DHCPOFFERNUM
    

    /*
     * TODO:405:r: Review DOT11DHCPUSEAGETABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define DOT11DHCPUSEAGETABLE_SETTABLE_COLS (COLUMN_DHCPMAXLIMIT_FLAG)

#ifdef __cplusplus
}
#endif

#endif /* DOT11DHCPUSEAGETABLE_OIDS_H */
