/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.12 $ of : mfd-data-access.m2c,v $
 *
 * $Id:$
 */
#ifndef DOT11BSSIDWAPIPROTOCOLCONFIGTABLE_DATA_ACCESS_H
#define DOT11BSSIDWAPIPROTOCOLCONFIGTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "autelanWtpGroup.h"

/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11BSSIDWAPIProtocolConfigTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11BSSIDWAPIProtocolConfigTable is subid 2 of wtpWAPI.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.1.10.2, length: 12
*/


    int dot11BSSIDWAPIProtocolConfigTable_init_data(dot11BSSIDWAPIProtocolConfigTable_registration_ptr dot11BSSIDWAPIProtocolConfigTable_reg);


/*
 * TODO:180:o: Review dot11BSSIDWAPIProtocolConfigTable cache timeout.
 * The number of seconds before the cache times out
 */
#define DOT11BSSIDWAPIPROTOCOLCONFIGTABLE_CACHE_TIMEOUT   DOT1DTPFDBTABLE_CACHE_TIMEOUT

void dot11BSSIDWAPIProtocolConfigTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
int dot11BSSIDWAPIProtocolConfigTable_cache_load(netsnmp_container *container);
void dot11BSSIDWAPIProtocolConfigTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int dot11BSSIDWAPIProtocolConfigTable_row_prep( dot11BSSIDWAPIProtocolConfigTable_rowreq_ctx *rowreq_ctx);


#ifdef __cplusplus
}
#endif

#endif /* DOT11BSSIDWAPIPROTOCOLCONFIGTABLE_DATA_ACCESS_H */
