#ifndef _SIGTRAN_DBUS_DEF_H_
#define _SIGTRAN_DBUS_DEF_H_

#ifndef PATH_LEN
#define PATH_LEN (64)
#endif

extern char UDP_IU_DBUS_BUSNAME[PATH_LEN];
extern char UDP_IU_DBUS_OBJPATH[PATH_LEN];
extern char UDP_IU_DBUS_INTERFACE[PATH_LEN];

extern char UDP_IU_SET_SELF_POINT_CODE[PATH_LEN];
extern char UDP_IU_SET_MSC[PATH_LEN];
extern char UDP_IU_SET_SGSN[PATH_LEN];
extern char UDP_IU_DBUS_METHOD_SET_DEBUG_STATE[PATH_LEN];
extern char UDP_IU_DBUS_METHOD_SHOW_RUNNING_CFG[PATH_LEN];
extern char UDP_IU_DBUS_METHOD_SET_SIGTRAN_ENABLE[PATH_LEN];

#endif
