/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.12 $ of : mfd-data-access.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "mibs_public.h"
#include "wcpss/asd/asd.h"
#include "wcpss/wid/WID.h"
#include "dbus/wcpss/dcli_wid_wtp.h"
#include "dbus/wcpss/dcli_wid_wlan.h"
#include "ws_dcli_wlans.h"
#include "ws_sysinfo.h"
#include "ws_init_dbus.h"
#include <stdlib.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "ws_init_dbus.h"
#include <dbus/dbus.h>
#include "sysdef/npd_sysdef.h"
#include "dbus/npd/npd_dbus_def.h"
#include "autelanWtpGroup.h"
#include "ws_security.h"
/* include our parent header */
#include "dot11WtpWAPIConfigTable.h"


#include "dot11WtpWAPIConfigTable_data_access.h"

/** @defgroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11WtpWAPIConfigTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11WtpWAPIConfigTable is subid 10 of wtpWAPI.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.1.10.10, length: 12
*/

/**
 * initialization for dot11WtpWAPIConfigTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param dot11WtpWAPIConfigTable_reg
 *        Pointer to dot11WtpWAPIConfigTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
dot11WtpWAPIConfigTable_init_data(dot11WtpWAPIConfigTable_registration_ptr dot11WtpWAPIConfigTable_reg)
{
    DEBUGMSGTL(("verbose:dot11WtpWAPIConfigTable:dot11WtpWAPIConfigTable_init_data","called\n"));

    /*
     * TODO:303:o: Initialize dot11WtpWAPIConfigTable data.
     */
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    return MFD_SUCCESS;
} /* dot11WtpWAPIConfigTable_init_data */

/**
 * container-cached overview
 *
 */

/***********************************************************************
 *
 * cache
 *
 ***********************************************************************/
/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
dot11WtpWAPIConfigTable_container_init(netsnmp_container **container_ptr_ptr,
                        netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:dot11WtpWAPIConfigTable:dot11WtpWAPIConfigTable_container_init","called\n"));
    
    if((NULL == cache) || (NULL == container_ptr_ptr)) {
        snmp_log(LOG_ERR,"bad params to dot11WtpWAPIConfigTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    /*
     * TODO:345:A: Set up dot11WtpWAPIConfigTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = DOT11WTPWAPICONFIGTABLE_CACHE_TIMEOUT; /* seconds */
} /* dot11WtpWAPIConfigTable_container_init */

/**
 * load cache data
 *
 * TODO:350:M: Implement dot11WtpWAPIConfigTable cache load
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to cache the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the cache, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  dot11WtpWAPIConfigTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
dot11WtpWAPIConfigTable_cache_load(netsnmp_container *container)
{
	snmp_log(LOG_DEBUG, "enter dot11WtpWAPIConfigTable_cache_load\n");

    dot11WtpWAPIConfigTable_rowreq_ctx *rowreq_ctx;
    size_t                 count = 0;
    
    /*
     * this example code is based on a data source that is a
     * text file to be read and parsed.
     */
	long   WapiWlanID;

	char wtpWapiAuthSuiteSelected[20] = { 0 };		
	char wtpWapiBKIDUsed[64] = { 0 };
	char wtpWapiAuthSuiteRequested[20] = { 0 };

    DEBUGMSGTL(("verbose:dot11WtpWAPIConfigTable:dot11WtpWAPIConfigTable_cache_load","called\n"));

	
	
    snmpd_dbus_message *messageHead = NULL, *messageNode = NULL;
    
    snmp_log(LOG_DEBUG, "enter list_connection_call_dbus_method:show_all_wlan_wapi_extend_config_information_cmd\n");
    messageHead = list_connection_call_dbus_method(show_all_wlan_wapi_extend_config_information_cmd, SHOW_ALL_WTP_TABLE_METHOD);
	snmp_log(LOG_DEBUG, "exit list_connection_call_dbus_method:show_all_wlan_wapi_extend_config_information_cmd,messageHead=%p\n", messageHead);

	
	if(messageHead)
	{
		for(messageNode = messageHead; NULL != messageNode; messageNode = messageNode->next)
		{
		    struct WtpWAPIExtendConfigInfo *WlanHead = messageNode->message;
		    if(WlanHead)
		    {
		        struct WtpWAPIExtendConfigInfo *WlanShowNode = NULL;
	/*
     * TODO:351:M: |-> Load/update data in the dot11WtpWAPIConfigTable container.
     * loop over your dot11WtpWAPIConfigTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
        /*
         * TODO:352:M: |   |-> set indexes in new dot11WtpWAPIConfigTable rowreq context.
         */
         for (WlanShowNode = WlanHead->WtpWAPIExtendConfigInfo_list; WlanShowNode != NULL; WlanShowNode = WlanShowNode->next)
		 {	

	        rowreq_ctx = dot11WtpWAPIConfigTable_allocate_rowreq_ctx();
	        if (NULL == rowreq_ctx)
			{
	            snmp_log(LOG_ERR, "memory allocation failed\n");
                free_dbus_message_list(&messageHead, Free_show_all_wlan_wapi_extend_config_information_cmd);
	            return MFD_RESOURCE_UNAVAILABLE;
	        }
	        unsigned long WapiWlanID = local_to_global_ID(messageNode->parameter, WlanShowNode->WapiWlanID, WIRELESS_MAX_NUM);
	        if(MFD_SUCCESS != dot11WtpWAPIConfigTable_indexes_set(rowreq_ctx
	                               , WapiWlanID
	               )) 
	        {
	            snmp_log(LOG_ERR,"error setting index while loading "
	                     "dot11WtpWAPIConfigTable cache.\n");
	            dot11WtpWAPIConfigTable_release_rowreq_ctx(rowreq_ctx);
	            continue;
	        }
		memcpy(&rowreq_ctx->data.parameter, &messageNode->parameter, sizeof(dbus_parameter));
		rowreq_ctx->data.SecurityID = WlanShowNode->SecurityID;
		rowreq_ctx->data.localWlanID = WlanShowNode->WapiWlanID;
	        /*
	         * TODO:352:r: |   |-> populate dot11WtpWAPIConfigTable data context.
	         * Populate data context here. (optionally, delay until row prep)
	         */
	    /*
	     * TRANSIENT or semi-TRANSIENT data:
	     * copy data or save any info needed to do it in row_prep.
	     */
	    /*
	     * setup/save data for wtpWapiConfigVersion
	     * wtpWapiConfigVersion(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiConfigVersion mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiConfigVersion = WlanShowNode->wtpWapiConfigVersion;
	    
	    /*
	     * setup/save data for wtpWapiControlledAuthenControlenabled
	     * wtpWapiControlledAuthenControlenabled(3)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiControlledAuthenControlenabled mapping.
	     * Map values between raw/native values and MIB values
	     *
	    * enums usually need mapping.
	    */
		rowreq_ctx->data.wtpWapiControlledAuthenControlenabled = WlanShowNode->wtpWapiControlledAuthenControlenabled;
	    
	    /*
	     * setup/save data for wtpWapiControlledPortControl
	     * wtpWapiControlledPortControl(4)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiControlledPortControl mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiControlledPortControl_map(&rowreq_ctx->data.wtpWapiControlledPortControl, &rowreq_ctx->data.wtpWapiControlledPortControl_len,
	     *                wtpWapiControlledPortControl, wtpWapiControlledPortControl_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiControlledPortControl data
	     */
	    int  wtpWapiControlledPortControl_len = 0;
		wtpWapiControlledPortControl_len = MIN(strlen("auto"),sizeof(rowreq_ctx->data.wtpWapiControlledPortControl));
	    rowreq_ctx->data.wtpWapiControlledPortControl_len = wtpWapiControlledPortControl_len * sizeof(rowreq_ctx->data.wtpWapiControlledPortControl[0]);
	    memcpy( rowreq_ctx->data.wtpWapiControlledPortControl, "auto", rowreq_ctx->data.wtpWapiControlledPortControl_len );
	    
	    /*
	     * setup/save data for wtpWapiWPIOptionImplement
	     * wtpWapiWPIOptionImplement(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiWPIOptionImplement mapping.
	     * Map values between raw/native values and MIB values
	     *
	    * enums usually need mapping.
	    */
	    rowreq_ctx->data.wtpWapiWPIOptionImplement = WlanShowNode->wtpWapiWPIOptionImplement;
	    
	    /*
	     * setup/save data for wtpWapiWPIPreauthImplemented
	     * wtpWapiWPIPreauthImplemented(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiWPIPreauthImplemented mapping.
	     * Map values between raw/native values and MIB values
	     *
	    * enums usually need mapping.
	    */
	   rowreq_ctx->data.wtpWapiWPIPreauthImplemented = WlanShowNode->wtpWapiWPIPreauthImplemented ;
	    
	    /*
	     * setup/save data for wtpWapiEnabled
	     * wtpWapiEnabled(7)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiEnabled mapping.
	     * Map values between raw/native values and MIB values
	     *
	    * enums usually need mapping.
	    */
	  	rowreq_ctx->data.wtpWapiEnabled = WlanShowNode->wtpWapiEnabled ;
	    
	    /*
	     * setup/save data for wtpWapiPreauthEnabled
	     * wtpWapiPreauthEnabled(8)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiPreauthEnabled mapping.
	     * Map values between raw/native values and MIB values
	     *
	    * enums usually need mapping.
	    */
	    rowreq_ctx->data.wtpWapiPreauthEnabled = WlanShowNode->wtpWapiPreauthEnabled;
	    
	    /*
	     * setup/save data for wtpWapiUnicastKeysSupported
	     * wtpWapiUnicastKeysSupported(9)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiUnicastKeysSupported mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiUnicastKeysSupported = WlanShowNode->wtpWapiUnicastKeysSupported;
	    
	    /*
	     * setup/save data for wtpWapiUnicastRekeyMethod
	     * wtpWapiUnicastRekeyMethod(10)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiUnicastRekeyMethod mapping.
	     * Map values between raw/native values and MIB values
	     *
	    * enums usually need mapping.
	    */
	     rowreq_ctx->data.wtpWapiUnicastRekeyMethod = WlanShowNode->wtpWapiUnicastRekeyMethod;
	    
	    /*
	     * setup/save data for wtpWapiUnicastRekeyTime
	     * wtpWapiUnicastRekeyTime(11)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiUnicastRekeyTime mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiUnicastRekeyTime = WlanShowNode->wtpWapiUnicastRekeyTime;
	    
	    /*
	     * setup/save data for wtpWapiUnicastRekeyPackets
	     * wtpWapiUnicastRekeyPackets(12)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiUnicastRekeyPackets mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiUnicastRekeyPackets = WlanShowNode->wtpWapiUnicastRekeyPackets;
	    
	    /*
	     * setup/save data for wtpWapiMulticastCipher
	     * wtpWapiMulticastCipher(13)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastCipher mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiMulticastCipher_map(&rowreq_ctx->data.wtpWapiMulticastCipher, &rowreq_ctx->data.wtpWapiMulticastCipher_len,
	     *                wtpWapiMulticastCipher, wtpWapiMulticastCipher_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiMulticastCipher data
	     */
	    char wtpWapiMulticastCipher[20];
		memset(wtpWapiMulticastCipher,0,sizeof(wtpWapiMulticastCipher));
	    int wtpWapiMulticastCipher_len = 0;
		snprintf(wtpWapiMulticastCipher, sizeof(wtpWapiMulticastCipher) - 1, "%02X:%02X:%02X:%02X",
	                WlanShowNode->wtpWapiMulticastCipher[0],WlanShowNode->wtpWapiMulticastCipher[1],
					WlanShowNode->wtpWapiMulticastCipher[2],WlanShowNode->wtpWapiMulticastCipher[3]);

		wtpWapiMulticastCipher_len =  MIN(strlen(wtpWapiMulticastCipher),sizeof(rowreq_ctx->data.wtpWapiMulticastCipher));
	    rowreq_ctx->data.wtpWapiMulticastCipher_len = wtpWapiMulticastCipher_len * sizeof(rowreq_ctx->data.wtpWapiMulticastCipher[0]);
	    memcpy( rowreq_ctx->data.wtpWapiMulticastCipher, wtpWapiMulticastCipher, rowreq_ctx->data.wtpWapiMulticastCipher_len );
	    
	    /*
	     * setup/save data for wtpWapiMulticastRekeyMethod
	     * wtpWapiMulticastRekeyMethod(14)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastRekeyMethod mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiMulticastRekeyMethod = WlanShowNode->wtpWapiMulticastRekeyMethod;
	    
	    /*
	     * setup/save data for wtpWapiMulticastRekeyTime
	     * wtpWapiMulticastRekeyTime(15)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastRekeyTime mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiMulticastRekeyTime = WlanShowNode->wtpWapiMulticastRekeyTime;
	    
	    /*
	     * setup/save data for wtpWapiMulticastRekeyPackets
	     * wtpWapiMulticastRekeyPackets(16)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastRekeyPackets mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiMulticastRekeyPackets = WlanShowNode->wtpWapiMulticastRekeyPackets;
	    
	    /*
	     * setup/save data for wtpWapiMulticastRekeyStrict
	     * wtpWapiMulticastRekeyStrict(17)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastRekeyStrict mapping.
	     * Map values between raw/native values and MIB values
	     *
	    * enums usually need mapping.
	    */
	     rowreq_ctx->data.wtpWapiMulticastRekeyStrict = WlanShowNode->wtpWapiMulticastRekeyStrict;
	    
	    /*
	     * setup/save data for wtpWapiPSKValue
	     * wtpWapiPSKValue(18)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiPSKValue mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiPSKValue_map(&rowreq_ctx->data.wtpWapiPSKValue, &rowreq_ctx->data.wtpWapiPSKValue_len,
	     *                wtpWapiPSKValue, wtpWapiPSKValue_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiPSKValue data
	     */
        if(WlanShowNode->wtpWapiPSKValue) {
    	    int wtpWapiPSKValue_len = 0;
    		wtpWapiPSKValue_len = MIN(strlen(WlanShowNode->wtpWapiPSKValue),sizeof(rowreq_ctx->data.wtpWapiPSKValue));
    	    rowreq_ctx->data.wtpWapiPSKValue_len = wtpWapiPSKValue_len * sizeof(rowreq_ctx->data.wtpWapiPSKValue[0]);
    	    memcpy( rowreq_ctx->data.wtpWapiPSKValue, WlanShowNode->wtpWapiPSKValue, rowreq_ctx->data.wtpWapiPSKValue_len );
	    }
	    
	    /*
	     * setup/save data for wtpWapiPSKPassPhrase
	     * wtpWapiPSKPassPhrase(19)/DisplayString/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiPSKPassPhrase mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiPSKPassPhrase_map(&rowreq_ctx->data.wtpWapiPSKPassPhrase, &rowreq_ctx->data.wtpWapiPSKPassPhrase_len,
	     *                wtpWapiPSKPassPhrase, wtpWapiPSKPassPhrase_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiPSKPassPhrase data
	     */
	    if(WlanShowNode->wtpWapiPSKPassPhrase) {
    	    int wtpWapiPSKPassPhrase_len = 0;
    		wtpWapiPSKPassPhrase_len = MIN(strlen(WlanShowNode->wtpWapiPSKPassPhrase),sizeof(rowreq_ctx->data.wtpWapiPSKPassPhrase));
    	    rowreq_ctx->data.wtpWapiPSKPassPhrase_len = wtpWapiPSKPassPhrase_len * sizeof(rowreq_ctx->data.wtpWapiPSKPassPhrase[0]);
    	    memcpy( rowreq_ctx->data.wtpWapiPSKPassPhrase, WlanShowNode->wtpWapiPSKPassPhrase, rowreq_ctx->data.wtpWapiPSKPassPhrase_len );
	    }
	    
	    /*
	     * setup/save data for wtpWapiCertificateUpdateCount
	     * wtpWapiCertificateUpdateCount(20)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiCertificateUpdateCount mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiCertificateUpdateCount = WlanShowNode->wtpWapiCertificateUpdateCount;
	    
	    /*
	     * setup/save data for wtpWapiMulticastUpdateCount
	     * wtpWapiMulticastUpdateCount(21)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastUpdateCount mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiMulticastUpdateCount = WlanShowNode->wtpWapiMulticastUpdateCount;
	    
	    /*
	     * setup/save data for wtpWapiUnicastUpdateCount
	     * wtpWapiUnicastUpdateCount(22)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiUnicastUpdateCount mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiUnicastUpdateCount = WlanShowNode->wtpWapiUnicastUpdateCount;
	    
	    /*
	     * setup/save data for wtpWapiMulticastCipherSize
	     * wtpWapiMulticastCipherSize(23)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastCipherSize mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiMulticastCipherSize = WlanShowNode->wtpWapiMulticastCipherSize;
	    
	    /*
	     * setup/save data for wtpWapiBKLifetime
	     * wtpWapiBKLifetime(24)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiBKLifetime mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiBKLifetime = WlanShowNode->wtpWapiBKLifetime;
	    
	    /*
	     * setup/save data for wtpWapiBKReauthThreshold
	     * wtpWapiBKReauthThreshold(25)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiBKReauthThreshold mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiBKReauthThreshold = WlanShowNode->wtpWapiBKReauthThreshold;
	    
	    /*
	     * setup/save data for wtpWapiSATimeout
	     * wtpWapiSATimeout(26)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/d/h
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiSATimeout mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * Integer based value can usually just do a direct copy.
	     */
	    rowreq_ctx->data.wtpWapiSATimeout = WlanShowNode->wtpWapiSATimeout;
	    
	    /*
	     * setup/save data for wtpWapiAuthSuiteSelected
	     * wtpWapiAuthSuiteSelected(27)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiAuthSuiteSelected mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiAuthSuiteSelected_map(&rowreq_ctx->data.wtpWapiAuthSuiteSelected, &rowreq_ctx->data.wtpWapiAuthSuiteSelected_len,
	     *                wtpWapiAuthSuiteSelected, wtpWapiAuthSuiteSelected_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiAuthSuiteSelected data
	     */
	    int wtpWapiAuthSuiteSelected_len = 0;			
		memset(wtpWapiAuthSuiteSelected, 0, sizeof(wtpWapiAuthSuiteSelected));
		snprintf(wtpWapiAuthSuiteSelected, sizeof(wtpWapiAuthSuiteSelected) - 1, "%02X-%02X-%02X-%02X",
		            WlanShowNode->wtpWapiAuthSuiteSelected[0],WlanShowNode->wtpWapiAuthSuiteSelected[1],
		            WlanShowNode->wtpWapiAuthSuiteSelected[2],WlanShowNode->wtpWapiAuthSuiteSelected[3]);

		wtpWapiAuthSuiteSelected_len = MIN(strlen(wtpWapiAuthSuiteSelected),sizeof(rowreq_ctx->data.wtpWapiAuthSuiteSelected));
	    rowreq_ctx->data.wtpWapiAuthSuiteSelected_len = wtpWapiAuthSuiteSelected_len * sizeof(rowreq_ctx->data.wtpWapiAuthSuiteSelected[0]);
	    memcpy( rowreq_ctx->data.wtpWapiAuthSuiteSelected, wtpWapiAuthSuiteSelected, rowreq_ctx->data.wtpWapiAuthSuiteSelected_len );
	    
	    /*
	     * setup/save data for wtpWapiUnicastCipherSelected
	     * wtpWapiUnicastCipherSelected(28)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiUnicastCipherSelected mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiUnicastCipherSelected_map(&rowreq_ctx->data.wtpWapiUnicastCipherSelected, &rowreq_ctx->data.wtpWapiUnicastCipherSelected_len,
	     *                wtpWapiUnicastCipherSelected, wtpWapiUnicastCipherSelected_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiUnicastCipherSelected data
	     */

	    int wtpWapiUnicastCipherSelected_len = 0;
		wtpWapiUnicastCipherSelected_len = MIN(strlen("00-14-72-01"),sizeof(rowreq_ctx->data.wtpWapiUnicastCipherSelected));
	    rowreq_ctx->data.wtpWapiUnicastCipherSelected_len = wtpWapiUnicastCipherSelected_len * sizeof(rowreq_ctx->data.wtpWapiUnicastCipherSelected[0]);
	    memcpy( rowreq_ctx->data.wtpWapiUnicastCipherSelected, "00-14-72-01", rowreq_ctx->data.wtpWapiUnicastCipherSelected_len );
	    
	    /*
	     * setup/save data for wtpWapiMulticastCipherSelected
	     * wtpWapiMulticastCipherSelected(29)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastCipherSelected mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiMulticastCipherSelected_map(&rowreq_ctx->data.wtpWapiMulticastCipherSelected, &rowreq_ctx->data.wtpWapiMulticastCipherSelected_len,
	     *                wtpWapiMulticastCipherSelected, wtpWapiMulticastCipherSelected_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiMulticastCipherSelected data
	     */
	     int wtpWapiMulticastCipherSelected_len = 0;
		wtpWapiMulticastCipherSelected_len = MIN(strlen("00-14-72-01"),sizeof(rowreq_ctx->data.wtpWapiMulticastCipherSelected));
	    rowreq_ctx->data.wtpWapiMulticastCipherSelected_len = wtpWapiMulticastCipherSelected_len * sizeof(rowreq_ctx->data.wtpWapiMulticastCipherSelected[0]);
	    memcpy( rowreq_ctx->data.wtpWapiMulticastCipherSelected, "00-14-72-01", rowreq_ctx->data.wtpWapiMulticastCipherSelected_len );
	    
	    /*
	     * setup/save data for wtpWapiBKIDUsed
	     * wtpWapiBKIDUsed(30)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiBKIDUsed mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiBKIDUsed_map(&rowreq_ctx->data.wtpWapiBKIDUsed, &rowreq_ctx->data.wtpWapiBKIDUsed_len,
	     *                wtpWapiBKIDUsed, wtpWapiBKIDUsed_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiBKIDUsed data
	     */
	     int wtpWapiBKIDUsed_len = 0;
	    if ((NULL == rowreq_ctx->data.wtpWapiBKIDUsed) ||
	        (rowreq_ctx->data.wtpWapiBKIDUsed_len < (wtpWapiBKIDUsed_len * sizeof(rowreq_ctx->data.wtpWapiBKIDUsed[0])))) {
	        snmp_log(LOG_ERR,"not enough space for value\n");
	        return MFD_ERROR;
	    }
		
		memset(wtpWapiBKIDUsed, 0, sizeof(wtpWapiBKIDUsed));
		snprintf(wtpWapiBKIDUsed, sizeof(wtpWapiBKIDUsed) - 1,"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x",
						WlanShowNode->wtpWapiBKIDUsed[0],WlanShowNode->wtpWapiBKIDUsed[1],WlanShowNode->wtpWapiBKIDUsed[2],WlanShowNode->wtpWapiBKIDUsed[3],
						WlanShowNode->wtpWapiBKIDUsed[4],WlanShowNode->wtpWapiBKIDUsed[5],WlanShowNode->wtpWapiBKIDUsed[6],WlanShowNode->wtpWapiBKIDUsed[7],
						WlanShowNode->wtpWapiBKIDUsed[8],WlanShowNode->wtpWapiBKIDUsed[9],WlanShowNode->wtpWapiBKIDUsed[10],WlanShowNode->wtpWapiBKIDUsed[11],
						WlanShowNode->wtpWapiBKIDUsed[12],WlanShowNode->wtpWapiBKIDUsed[13],WlanShowNode->wtpWapiBKIDUsed[14],WlanShowNode->wtpWapiBKIDUsed[15]);

		wtpWapiBKIDUsed_len = MIN(strlen(wtpWapiBKIDUsed),sizeof(rowreq_ctx->data.wtpWapiBKIDUsed));
	    rowreq_ctx->data.wtpWapiBKIDUsed_len = wtpWapiBKIDUsed_len * sizeof(rowreq_ctx->data.wtpWapiBKIDUsed[0]);
	    memcpy( rowreq_ctx->data.wtpWapiBKIDUsed, wtpWapiBKIDUsed, rowreq_ctx->data.wtpWapiBKIDUsed_len );
	    
	    /*
	     * setup/save data for wtpWapiAuthSuiteRequested
	     * wtpWapiAuthSuiteRequested(31)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiAuthSuiteRequested mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiAuthSuiteRequested_map(&rowreq_ctx->data.wtpWapiAuthSuiteRequested, &rowreq_ctx->data.wtpWapiAuthSuiteRequested_len,
	     *                wtpWapiAuthSuiteRequested, wtpWapiAuthSuiteRequested_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiAuthSuiteRequested data
	     */
	     int wtpWapiAuthSuiteRequested_len = 0;
	    if ((NULL == rowreq_ctx->data.wtpWapiAuthSuiteRequested) ||
	        (rowreq_ctx->data.wtpWapiAuthSuiteRequested_len < (wtpWapiAuthSuiteRequested_len * sizeof(rowreq_ctx->data.wtpWapiAuthSuiteRequested[0])))) {
	        snmp_log(LOG_ERR,"not enough space for value\n");
	        return MFD_ERROR;
	    }
		
		memset(wtpWapiAuthSuiteRequested, 0, sizeof(wtpWapiAuthSuiteRequested));	
		snprintf(wtpWapiAuthSuiteRequested, sizeof(wtpWapiAuthSuiteRequested) - 1,"%02X-%02X-%02X-%02X",
					WlanShowNode->wtpWapiAuthSuiteRequested[0],WlanShowNode->wtpWapiAuthSuiteRequested[1],
					WlanShowNode->wtpWapiAuthSuiteRequested[2],WlanShowNode->wtpWapiAuthSuiteRequested[3]);

		wtpWapiAuthSuiteRequested_len = MIN(strlen(wtpWapiAuthSuiteRequested),sizeof(rowreq_ctx->data.wtpWapiAuthSuiteRequested));
	    rowreq_ctx->data.wtpWapiAuthSuiteRequested_len = wtpWapiAuthSuiteRequested_len * sizeof(rowreq_ctx->data.wtpWapiAuthSuiteRequested[0]);
	    memcpy( rowreq_ctx->data.wtpWapiAuthSuiteRequested, wtpWapiAuthSuiteRequested, rowreq_ctx->data.wtpWapiAuthSuiteRequested_len );
	    
	    /*
	     * setup/save data for wtpWapiUnicastCipherRequested
	     * wtpWapiUnicastCipherRequested(32)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiUnicastCipherRequested mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiUnicastCipherRequested_map(&rowreq_ctx->data.wtpWapiUnicastCipherRequested, &rowreq_ctx->data.wtpWapiUnicastCipherRequested_len,
	     *                wtpWapiUnicastCipherRequested, wtpWapiUnicastCipherRequested_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiUnicastCipherRequested data
	     */
	     int wtpWapiUnicastCipherRequested_len = 0;
	    if ((NULL == rowreq_ctx->data.wtpWapiUnicastCipherRequested) ||
	        (rowreq_ctx->data.wtpWapiUnicastCipherRequested_len < (wtpWapiUnicastCipherRequested_len * sizeof(rowreq_ctx->data.wtpWapiUnicastCipherRequested[0])))) {
	        snmp_log(LOG_ERR,"not enough space for value\n");
	        return MFD_ERROR;
	    }
		wtpWapiUnicastCipherRequested_len = MIN(strlen("00-14-72-01"),sizeof(rowreq_ctx->data.wtpWapiUnicastCipherRequested));
	    rowreq_ctx->data.wtpWapiUnicastCipherRequested_len = wtpWapiUnicastCipherRequested_len * sizeof(rowreq_ctx->data.wtpWapiUnicastCipherRequested[0]);
	    memcpy( rowreq_ctx->data.wtpWapiUnicastCipherRequested, "00-14-72-01", rowreq_ctx->data.wtpWapiUnicastCipherRequested_len );
	    
	    /*
	     * setup/save data for wtpWapiMulticastCipherRequested
	     * wtpWapiMulticastCipherRequested(33)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
	     */
	    /*
	     * TODO:246:r: |-> Define wtpWapiMulticastCipherRequested mapping.
	     * Map values between raw/native values and MIB values
	     *
	     * if(MFD_SUCCESS !=
	     *    wtpWapiMulticastCipherRequested_map(&rowreq_ctx->data.wtpWapiMulticastCipherRequested, &rowreq_ctx->data.wtpWapiMulticastCipherRequested_len,
	     *                wtpWapiMulticastCipherRequested, wtpWapiMulticastCipherRequested_len, 0)) {
	     *    return MFD_ERROR;
	     * }
	     */
	    /*
	     * make sure there is enough space for wtpWapiMulticastCipherRequested data
	     */
	     int wtpWapiMulticastCipherRequested_len = 0;
	    if ((NULL == rowreq_ctx->data.wtpWapiMulticastCipherRequested) ||
	        (rowreq_ctx->data.wtpWapiMulticastCipherRequested_len < (wtpWapiMulticastCipherRequested_len * sizeof(rowreq_ctx->data.wtpWapiMulticastCipherRequested[0])))) {
	        snmp_log(LOG_ERR,"not enough space for value\n");
	        return MFD_ERROR;
	    }
		wtpWapiMulticastCipherRequested_len = MIN(strlen("00-14-72-01"),sizeof(rowreq_ctx->data.wtpWapiMulticastCipherRequested));
	    rowreq_ctx->data.wtpWapiMulticastCipherRequested_len = wtpWapiMulticastCipherRequested_len * sizeof(rowreq_ctx->data.wtpWapiMulticastCipherRequested[0]);
	    memcpy( rowreq_ctx->data.wtpWapiMulticastCipherRequested, "00-14-72-01", rowreq_ctx->data.wtpWapiMulticastCipherRequested_len );
	    
	        
	        /*
	         * insert into table container
	         */
        	        if(CONTAINER_INSERT(container, rowreq_ctx))
        	        {
        				dot11WtpWAPIConfigTable_release_rowreq_ctx(rowreq_ctx);
        			}
        	        ++count;
        		}
           	}
    	}
        free_dbus_message_list(&messageHead, Free_show_all_wlan_wapi_extend_config_information_cmd);
	}
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    DEBUGMSGT(("verbose:dot11WtpWAPIConfigTable:dot11WtpWAPIConfigTable_cache_load",
               "inserted %d records\n", count));

	snmp_log(LOG_DEBUG, "exit dot11WtpWAPIConfigTable_cache_load\n");
    return MFD_SUCCESS;
} /* dot11WtpWAPIConfigTable_cache_load */

/**
 * cache clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
dot11WtpWAPIConfigTable_cache_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:dot11WtpWAPIConfigTable:dot11WtpWAPIConfigTable_cache_free","called\n"));

    /*
     * TODO:380:M: Free dot11WtpWAPIConfigTable cache.
     */
} /* dot11WtpWAPIConfigTable_cache_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
dot11WtpWAPIConfigTable_row_prep( dot11WtpWAPIConfigTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot11WtpWAPIConfigTable:dot11WtpWAPIConfigTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* dot11WtpWAPIConfigTable_row_prep */

/** @} */
