/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c,v 1.10 2004/10/08 23:39:17 rstory Exp $
 *
 * $Id:$
 */
#ifndef DOT11QUITWTPINFOTABLE_OIDS_H
#define DOT11QUITWTPINFOTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table dot11QuitWtpInfoTable */
//#define DOT11QUITWTPINFOTABLE_OID              1,3,6,1,4,1,31656,6,1,1,2,7
#define COLUMN_QUITWTPMACADDR		1
#define COLUMN_QUITWTPID		2
#define COLUMN_QUITWTPSTATE		3

#define DOT11QUITWTPINFOTABLE_MIN_COL		COLUMN_QUITWTPMACADDR
#define DOT11QUITWTPINFOTABLE_MAX_COL		COLUMN_QUITWTPSTATE


#ifdef __cplusplus
}
#endif

#endif /* DOT11QUITWTPINFOTABLE_OIDS_H */
