/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.12 $ of : mfd-data-access.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot11BssWAPIPerformanceStatsTable.h"
#include "dot11BssWAPIPerformanceStatsTable_data_access.h"
#include "wcpss/asd/asd.h"
#include "wcpss/wid/WID.h"
#include "dbus/wcpss/dcli_wid_wtp.h"
#include "dbus/wcpss/dcli_wid_wlan.h"
#include "ws_dcli_wlans.h"
#include "../mibs_public.h"

/** @defgroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11BssWAPIPerformanceStatsTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11BssWAPIPerformanceStatsTable is subid 5 of wtpWAPI.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.33050.6.1.1.10.5, length: 12
*/

/**
 * initialization for dot11BssWAPIPerformanceStatsTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param dot11BssWAPIPerformanceStatsTable_reg
 *        Pointer to dot11BssWAPIPerformanceStatsTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
dot11BssWAPIPerformanceStatsTable_init_data(dot11BssWAPIPerformanceStatsTable_registration_ptr dot11BssWAPIPerformanceStatsTable_reg)
{
    DEBUGMSGTL(("verbose:dot11BssWAPIPerformanceStatsTable:dot11BssWAPIPerformanceStatsTable_init_data","called\n"));

    /*
     * TODO:303:o: Initialize dot11BssWAPIPerformanceStatsTable data.
     */
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    return MFD_SUCCESS;
} /* dot11BssWAPIPerformanceStatsTable_init_data */

/**
 * container-cached overview
 *
 */

/***********************************************************************
 *
 * cache
 *
 ***********************************************************************/
/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
dot11BssWAPIPerformanceStatsTable_container_init(netsnmp_container **container_ptr_ptr,
                        netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:dot11BssWAPIPerformanceStatsTable:dot11BssWAPIPerformanceStatsTable_container_init","called\n"));
    
    if((NULL == cache) || (NULL == container_ptr_ptr)) {
        snmp_log(LOG_ERR,"bad params to dot11BssWAPIPerformanceStatsTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    /*
     * TODO:345:A: Set up dot11BssWAPIPerformanceStatsTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = DOT11BSSWAPIPERFORMANCESTATSTABLE_CACHE_TIMEOUT; /* seconds */
} /* dot11BssWAPIPerformanceStatsTable_container_init */

/**
 * load cache data
 *
 * TODO:350:M: Implement dot11BssWAPIPerformanceStatsTable cache load
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to cache the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the cache, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  dot11BssWAPIPerformanceStatsTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
dot11BssWAPIPerformanceStatsTable_cache_load(netsnmp_container *container)
{
	snmp_log(LOG_DEBUG, "enter dot11BssWAPIPerformanceStatsTable_cache_load\n");

    dot11BssWAPIPerformanceStatsTable_rowreq_ctx *rowreq_ctx;
    size_t                 count = 0;
    
    /*
     * this example code is based on a data source that is a
     * text file to be read and parsed.
     */
    //FILE *filep;
    //char line[MAX_LINE_SIZE];
    /*
     * temporary storage for index values
     */
        /*
         * wtpMacAddr(1)/Dot11BaseWtpIdTC/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
         */
        /** 128 - 1(entry) - 1(col) - 1(other indexes) = 111 */
   char   wtpMacAddr[20];
   size_t      wtpMacAddr_len = 0;
        /*
         * wtpBssCurrID(1)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        /** 128 - 1(entry) - 1(col) - 1(other indexes) = 111 */
   char   wtpBssCurrID[20];
   size_t      wtpBssCurrID_len = 0;

    DEBUGMSGTL(("verbose:dot11BssWAPIPerformanceStatsTable:dot11BssWAPIPerformanceStatsTable_cache_load","called\n"));

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    /*
     * open our data file.
     */
    //filep = fopen("/etc/dummy.conf", "r");
    //if(NULL ==  filep) {
      //  return MFD_RESOURCE_UNAVAILABLE;
    //}

    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    /*
     * TODO:351:M: |-> Load/update data in the dot11BssWAPIPerformanceStatsTable container.
     * loop over your dot11BssWAPIPerformanceStatsTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */

	unsigned char UnicastCipherSelected[4] = {0x00, 0x14, 0x72, 0x01};
	char WapiSelectedUnicastCipher[15];
	size_t bssWapiSelectedUnicastCipher_len = 0;

    snmpd_dbus_message *messageHead = NULL, *messageNode = NULL;
    
    snmp_log(LOG_DEBUG, "enter list_connection_call_dbus_method:show_all_wlan_bss_wapi_performance_stats_information_cmd\n");
    messageHead = list_connection_call_dbus_method(show_all_wlan_bss_wapi_performance_stats_information_cmd, SHOW_ALL_WTP_TABLE_METHOD);
	snmp_log(LOG_DEBUG, "exit list_connection_call_dbus_method:show_all_wlan_bss_wapi_performance_stats_information_cmd,messageHead=%p\n", messageHead);

	if(messageHead)
	{
		for(messageNode = messageHead; NULL != messageNode; messageNode = messageNode->next)
		{
		    struct BssWAPIPerformanceStatsInfo *WlanHead = messageNode->message;
		    if(WlanHead)
		    {
		        struct BssWAPIPerformanceStatsInfo *q = NULL;
        		for(q = WlanHead->BssWAPIPerformanceStatsInfo_list; q != NULL; q = q->next)
        		{
        		    int i = 0;
        		    struct Sub_BssWAPIPerformanceStatsInfo *BssShowNode = NULL;
        			for(i = 0, BssShowNode = q->Sub_BssWAPIPerformanceStatsInfo_head;
        			    i < q->wlan_bss_num && NULL != BssShowNode;
        			    i++, BssShowNode = BssShowNode->next)
        			{
        				memset(wtpMacAddr,0,sizeof(wtpMacAddr));
        				if(BssShowNode->wtpMacAddr) {
        				    snprintf(wtpMacAddr, sizeof(wtpMacAddr) - 1,"%02X:%02X:%02X:%02X:%02X:%02X",
        				                        BssShowNode->wtpMacAddr[0],BssShowNode->wtpMacAddr[1],BssShowNode->wtpMacAddr[2],
        				                        BssShowNode->wtpMacAddr[3],BssShowNode->wtpMacAddr[4],BssShowNode->wtpMacAddr[5]);
                        }
                        
        				memset(wtpBssCurrID,0,sizeof(wtpBssCurrID));
        				if(BssShowNode->wtpBssCurrID) {
        				    snprintf(wtpBssCurrID, sizeof(wtpBssCurrID) - 1,"%02X:%02X:%02X:%02X:%02X:%02X",
        				                            BssShowNode->wtpBssCurrID[0],BssShowNode->wtpBssCurrID[1],BssShowNode->wtpBssCurrID[2],
        				                            BssShowNode->wtpBssCurrID[3],BssShowNode->wtpBssCurrID[4],BssShowNode->wtpBssCurrID[5]);
        		        }
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    /*
     * get a line (skip blank lines)
     */
    //do {
      //  if (!fgets(line, sizeof(line), filep)) {
            /* we're done */
        //    fclose(filep);
          //  filep = NULL;
        //}
    //} while (filep && (line[0] == '\n'));

    /*
     * check for end of data
     */
    //if(NULL == filep)
      //  break;

    /*
     * parse line into variables
     */
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

        /*
         * TODO:352:M: |   |-> set indexes in new dot11BssWAPIPerformanceStatsTable rowreq context.
         */
        rowreq_ctx = dot11BssWAPIPerformanceStatsTable_allocate_rowreq_ctx();
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            free_dbus_message_list(&messageHead, Free_show_all_wlan_bss_wapi_performance_stats_information_cmd);
            return MFD_RESOURCE_UNAVAILABLE;
        }
		
		wtpMacAddr_len = strlen(wtpMacAddr);
		wtpBssCurrID_len = strlen(wtpBssCurrID);
        if(MFD_SUCCESS != dot11BssWAPIPerformanceStatsTable_indexes_set(rowreq_ctx
                               , wtpMacAddr, wtpMacAddr_len
                               , wtpBssCurrID, wtpBssCurrID_len
               )) {
            snmp_log(LOG_ERR,"error setting index while loading "
                     "dot11BssWAPIPerformanceStatsTable cache.\n");
            dot11BssWAPIPerformanceStatsTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }

        /*
         * TODO:352:r: |   |-> populate dot11BssWAPIPerformanceStatsTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
    /*
     * TRANSIENT or semi-TRANSIENT data:
     * copy data or save any info needed to do it in row_prep.
     */
    /*
     * setup/save data for bssWapiControlledPortStatus
     * bssWapiControlledPortStatus(1)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiControlledPortStatus mapping.
     * Map values between raw/native values and MIB values
     *
    * enums usually need mapping.
    */
    /*if(MFD_SUCCESS !=
       bssWapiControlledPortStatus_map(&rowreq_ctx->data.bssWapiControlledPortStatus, bssWapiControlledPortStatus )) {
        return MFD_ERROR;
    }*/

	rowreq_ctx->data.bssWapiControlledPortStatus = 0;
    
    /*
     * setup/save data for bssWapiSelectedUnicastCipher
     * bssWapiSelectedUnicastCipher(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
     */
    /*
     * TODO:246:r: |-> Define bssWapiSelectedUnicastCipher mapping.
     * Map values between raw/native values and MIB values
     *
     * if(MFD_SUCCESS !=
     *    bssWapiSelectedUnicastCipher_map(&rowreq_ctx->data.bssWapiSelectedUnicastCipher, &rowreq_ctx->data.bssWapiSelectedUnicastCipher_len,
     *                bssWapiSelectedUnicastCipher, bssWapiSelectedUnicastCipher_len, 0)) {
     *    return MFD_ERROR;
     * }
     */
    /*
     * make sure there is enough space for bssWapiSelectedUnicastCipher data
     */
    /*if ((NULL == rowreq_ctx->data.bssWapiSelectedUnicastCipher) ||
        (rowreq_ctx->data.bssWapiSelectedUnicastCipher_len < (bssWapiSelectedUnicastCipher_len * sizeof(rowreq_ctx->data.bssWapiSelectedUnicastCipher[0])))) {
        snmp_log(LOG_ERR,"not enough space for value\n");
        return MFD_ERROR;
    }*/
	
	memset(WapiSelectedUnicastCipher,0,sizeof(WapiSelectedUnicastCipher));
	snprintf(WapiSelectedUnicastCipher, sizeof(WapiSelectedUnicastCipher) - 1,"%02X-%02X-%02X-%02X",
	            UnicastCipherSelected[0],UnicastCipherSelected[1],UnicastCipherSelected[2],UnicastCipherSelected[3]);

	bssWapiSelectedUnicastCipher_len = MIN(strlen(WapiSelectedUnicastCipher),sizeof(rowreq_ctx->data.bssWapiSelectedUnicastCipher)-1);
	
    rowreq_ctx->data.bssWapiSelectedUnicastCipher_len = bssWapiSelectedUnicastCipher_len * sizeof(rowreq_ctx->data.bssWapiSelectedUnicastCipher[0]);
    memcpy( rowreq_ctx->data.bssWapiSelectedUnicastCipher, WapiSelectedUnicastCipher, rowreq_ctx->data.bssWapiSelectedUnicastCipher_len );
    
    /*
     * setup/save data for bssWapiWPIReplayCounters
     * bssWapiWPIReplayCounters(3)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWPIReplayCounters mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWPIReplayCounters = BssShowNode->bssWapiWPIReplayCounters;
    
    /*
     * setup/save data for bssWapiWPIDecryptableErrors
     * bssWapiWPIDecryptableErrors(4)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWPIDecryptableErrors mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWPIDecryptableErrors = BssShowNode->bssWapiWPIDecryptableErrors;
    
    /*
     * setup/save data for bssWapiWPIMICErrors
     * bssWapiWPIMICErrors(5)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWPIMICErrors mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWPIMICErrors = BssShowNode->bssWapiWPIMICErrors;
    
    /*
     * setup/save data for bssWapiWAISignatureErrors
     * bssWapiWAISignatureErrors(6)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAISignatureErrors mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAISignatureErrors = BssShowNode->bssWapiWAISignatureErrors;
    
    /*
     * setup/save data for bssWapiWAIHMACErrors
     * bssWapiWAIHMACErrors(7)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAIHMACErrors mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAIHMACErrors = BssShowNode->bssWapiWAIHMACErrors;
    
    /*
     * setup/save data for bssWapiWAIAuthResultFailures
     * bssWapiWAIAuthResultFailures(8)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAIAuthResultFailures mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAIAuthResultFailures = BssShowNode->bssWapiWAIAuthResultFailures;
    
    /*
     * setup/save data for bssWapiWAIDiscardCounters
     * bssWapiWAIDiscardCounters(9)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAIDiscardCounters mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAIDiscardCounters = BssShowNode->bssWapiWAIDiscardCounters;
    
    /*
     * setup/save data for bssWapiWAITimeoutCounters
     * bssWapiWAITimeoutCounters(10)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAITimeoutCounters mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAITimeoutCounters = BssShowNode->bssWapiWAITimeoutCounters;
    
    /*
     * setup/save data for bssWapiWAIFormatErrors
     * bssWapiWAIFormatErrors(11)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAIFormatErrors mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAIFormatErrors = BssShowNode->bssWapiWAIFormatErrors;
    
    /*
     * setup/save data for bssWapiWAICertificateHandshakeFailures
     * bssWapiWAICertificateHandshakeFailures(12)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAICertificateHandshakeFailures mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAICertificateHandshakeFailures = BssShowNode->bssWapiWAICertificateHandshakeFailures;
    
    /*
     * setup/save data for bssWapiWAIUnicastHandshakeFailures
     * bssWapiWAIUnicastHandshakeFailures(13)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAIUnicastHandshakeFailures mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAIUnicastHandshakeFailures = BssShowNode->bssWapiWAIUnicastHandshakeFailures;
    
    /*
     * setup/save data for bssWapiWAIMulticastHandshakeFailures
     * bssWapiWAIMulticastHandshakeFailures(14)/COUNTER/ASN_COUNTER/u_long(u_long)//l/A/w/e/r/d/h
     */
    /*
     * TODO:246:r: |-> Define bssWapiWAIMulticastHandshakeFailures mapping.
     * Map values between raw/native values and MIB values
     *
     * Integer based value can usually just do a direct copy.
     */
    rowreq_ctx->data.bssWapiWAIMulticastHandshakeFailures = BssShowNode->bssWapiWAIMulticastHandshakeFailures;
    
        
        /*
         * insert into table container
         */
    			        if(CONTAINER_INSERT(container, rowreq_ctx))
    			        {
    						dot11BssWAPIPerformanceStatsTable_release_rowreq_ctx(rowreq_ctx);
    			        }
    			        ++count;
        			}	
    			}
    		}
    	}
    	free_dbus_message_list(&messageHead, Free_show_all_wlan_bss_wapi_performance_stats_information_cmd);
	}


    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    //if(NULL != filep)
    //    fclose(filep);
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    DEBUGMSGT(("verbose:dot11BssWAPIPerformanceStatsTable:dot11BssWAPIPerformanceStatsTable_cache_load",
               "inserted %d records\n", count));

	snmp_log(LOG_DEBUG, "exit dot11BssWAPIPerformanceStatsTable_cache_load\n");
    return MFD_SUCCESS;
} /* dot11BssWAPIPerformanceStatsTable_cache_load */

/**
 * cache clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
dot11BssWAPIPerformanceStatsTable_cache_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:dot11BssWAPIPerformanceStatsTable:dot11BssWAPIPerformanceStatsTable_cache_free","called\n"));

    /*
     * TODO:380:M: Free dot11BssWAPIPerformanceStatsTable cache.
     */
} /* dot11BssWAPIPerformanceStatsTable_cache_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
dot11BssWAPIPerformanceStatsTable_row_prep( dot11BssWAPIPerformanceStatsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:dot11BssWAPIPerformanceStatsTable:dot11BssWAPIPerformanceStatsTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* dot11BssWAPIPerformanceStatsTable_row_prep */

/** @} */
