/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-set.m2c,v $ 
 *
 * $Id:$
 */
#ifndef DOT11CONFIGRADIUSACCSERVERTABLE_DATA_SET_H
#define DOT11CONFIGRADIUSACCSERVERTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11ConfigRadiusAccServerTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11ConfigRadiusAccServerTable is subid 7 of dot11securityConfig.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.14.7, length: 12
*/
int RadiusAccServerID_check_index( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx ); /* internal */


int dot11ConfigRadiusAccServerTable_undo_setup( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx);
int dot11ConfigRadiusAccServerTable_undo_cleanup( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx);
int dot11ConfigRadiusAccServerTable_commit( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx);
int dot11ConfigRadiusAccServerTable_undo_commit( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx);


int NewAccServerIPAdd_check_value( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, u_long NewAccServerIPAdd_val);
int NewAccServerIPAdd_undo_setup( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );
int NewAccServerIPAdd_set( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, u_long NewAccServerIPAdd_val );
int NewAccServerIPAdd_undo( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );

int NewAccServerPort_check_value( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, long NewAccServerPort_val);
int NewAccServerPort_undo_setup( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );
int NewAccServerPort_set( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, long NewAccServerPort_val );
int NewAccServerPort_undo( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );

int NewAccServerSharedkey_check_value( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, char *NewAccServerSharedkey_val_ptr,  size_t NewAccServerSharedkey_val_ptr_len);
int NewAccServerSharedkey_undo_setup( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );
int NewAccServerSharedkey_set( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, char *NewAccServerSharedkey_val_ptr,  size_t NewAccServerSharedkey_val_ptr_len );
int NewAccServerSharedkey_undo( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );

int NewRadiusAccServerIPAdd_check_value( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, u_long NewRadiusAccServerIPAdd_val);
int NewRadiusAccServerIPAdd_undo_setup( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );
int NewRadiusAccServerIPAdd_set( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, u_long NewRadiusAccServerIPAdd_val );
int NewRadiusAccServerIPAdd_undo( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );

int NewRadiusAccServerPort_check_value( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, long NewRadiusAccServerPort_val);
int NewRadiusAccServerPort_undo_setup( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );
int NewRadiusAccServerPort_set( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, long NewRadiusAccServerPort_val );
int NewRadiusAccServerPort_undo( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );

int NewRadiusAccServerSharedkey_check_value( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, char *NewRadiusAccServerSharedkey_val_ptr,  size_t NewRadiusAccServerSharedkey_val_ptr_len);
int NewRadiusAccServerSharedkey_undo_setup( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );
int NewRadiusAccServerSharedkey_set( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx, char *NewRadiusAccServerSharedkey_val_ptr,  size_t NewRadiusAccServerSharedkey_val_ptr_len );
int NewRadiusAccServerSharedkey_undo( dot11ConfigRadiusAccServerTable_rowreq_ctx *rowreq_ctx );


int dot11ConfigRadiusAccServerTable_check_dependencies(dot11ConfigRadiusAccServerTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* DOT11CONFIGRADIUSACCSERVERTABLE_DATA_SET_H */
