/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot11DHCPIpPoolConfigTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dot11DHCPIpPoolConfigTable get routines.
 * TODO:240:M: Implement dot11DHCPIpPoolConfigTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11DHCPIpPoolConfigTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigTable is subid 5 of dot11Service.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement dot11DHCPIpPoolConfigTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param DHCPID_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dot11DHCPIpPoolConfigTable_indexes_set_tbl_idx(dot11DHCPIpPoolConfigTable_mib_index *tbl_idx, long DHCPID_val)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:dot11DHCPIpPoolConfigTable_indexes_set_tbl_idx","called\n"));

    /* DHCPID(1)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    tbl_idx->DHCPID = DHCPID_val;
    

    return MFD_SUCCESS;
} /* dot11DHCPIpPoolConfigTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dot11DHCPIpPoolConfigTable_indexes_set(dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, long DHCPID_val)
{
    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:dot11DHCPIpPoolConfigTable_indexes_set","called\n"));

    if(MFD_SUCCESS != dot11DHCPIpPoolConfigTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , DHCPID_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != dot11DHCPIpPoolConfigTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* dot11DHCPIpPoolConfigTable_indexes_set */


/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.IPPollStartAddr
 * IPPollStartAddr is subid 2 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.2
 * Description:
IP Address pool starting address.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the IPPollStartAddr data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param IPPollStartAddr_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
IPPollStartAddr_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, u_long * IPPollStartAddr_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != IPPollStartAddr_val_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:IPPollStartAddr_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the IPPollStartAddr data.
 * copy (* IPPollStartAddr_val_ptr ) from rowreq_ctx->data
 */
    (* IPPollStartAddr_val_ptr ) = rowreq_ctx->data.IPPollStartAddr;

    return MFD_SUCCESS;
} /* IPPollStartAddr_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.IPPoolStopAddr
 * IPPoolStopAddr is subid 3 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.3
 * Description:
IP Address pool ending address.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the IPPoolStopAddr data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param IPPoolStopAddr_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
IPPoolStopAddr_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, u_long * IPPoolStopAddr_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != IPPoolStopAddr_val_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:IPPoolStopAddr_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the IPPoolStopAddr data.
 * copy (* IPPoolStopAddr_val_ptr ) from rowreq_ctx->data
 */
    (* IPPoolStopAddr_val_ptr ) = rowreq_ctx->data.IPPoolStopAddr;

    return MFD_SUCCESS;
} /* IPPoolStopAddr_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.GatewayAddr
 * GatewayAddr is subid 4 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.4
 * Description:
Gateway Address.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the GatewayAddr data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param GatewayAddr_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
GatewayAddr_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, u_long * GatewayAddr_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != GatewayAddr_val_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:GatewayAddr_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the GatewayAddr data.
 * copy (* GatewayAddr_val_ptr ) from rowreq_ctx->data
 */
    (* GatewayAddr_val_ptr ) = rowreq_ctx->data.GatewayAddr;

    return MFD_SUCCESS;
} /* GatewayAddr_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.Netmask
 * Netmask is subid 5 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.5
 * Description:
Netmask
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the Netmask data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param Netmask_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
Netmask_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, u_long * Netmask_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != Netmask_val_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:Netmask_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the Netmask data.
 * copy (* Netmask_val_ptr ) from rowreq_ctx->data
 */
    (* Netmask_val_ptr ) = rowreq_ctx->data.Netmask;

    return MFD_SUCCESS;
} /* Netmask_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.LeasePeriod
 * LeasePeriod is subid 6 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.6
 * Description:
IP Address Lease Periods.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is TICKS (based on perltype TICKS)
 * The net-snmp type is ASN_TIMETICKS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the LeasePeriod data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param LeasePeriod_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
LeasePeriod_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, u_long * LeasePeriod_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != LeasePeriod_val_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:LeasePeriod_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the LeasePeriod data.
 * copy (* LeasePeriod_val_ptr ) from rowreq_ctx->data
 */
    (* LeasePeriod_val_ptr ) = rowreq_ctx->data.LeasePeriod;

    return MFD_SUCCESS;
} /* LeasePeriod_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.FirDNSServerIPAddress
 * FirDNSServerIPAddress is subid 7 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.7
 * Description:
IP Address first DNS IP Address.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the FirDNSServerIPAddress data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param FirDNSServerIPAddress_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
FirDNSServerIPAddress_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, u_long * FirDNSServerIPAddress_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != FirDNSServerIPAddress_val_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:FirDNSServerIPAddress_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the FirDNSServerIPAddress data.
 * copy (* FirDNSServerIPAddress_val_ptr ) from rowreq_ctx->data
 */
    (* FirDNSServerIPAddress_val_ptr ) = rowreq_ctx->data.FirDNSServerIPAddress;

    return MFD_SUCCESS;
} /* FirDNSServerIPAddress_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.SeconDNSServerIPAddress
 * SeconDNSServerIPAddress is subid 8 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.8
 * Description:
IP Address second DNS IP Address.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 *
 * Its syntax is IPADDR (based on perltype IPADDR)
 * The net-snmp type is ASN_IPADDRESS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the SeconDNSServerIPAddress data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param SeconDNSServerIPAddress_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
SeconDNSServerIPAddress_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, u_long * SeconDNSServerIPAddress_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != SeconDNSServerIPAddress_val_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:SeconDNSServerIPAddress_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the SeconDNSServerIPAddress data.
 * copy (* SeconDNSServerIPAddress_val_ptr ) from rowreq_ctx->data
 */
    (* SeconDNSServerIPAddress_val_ptr ) = rowreq_ctx->data.SeconDNSServerIPAddress;

    return MFD_SUCCESS;
} /* SeconDNSServerIPAddress_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.DHCPRowStatus
 * DHCPRowStatus is subid 9 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.9
 * Description:
This variable is used to create, modify, and/or delete a row
			        	 in this table.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * Its syntax is RowStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the DHCPRowStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param DHCPRowStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
DHCPRowStatus_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, u_long * DHCPRowStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != DHCPRowStatus_val_ptr );

    (* DHCPRowStatus_val_ptr ) = rowreq_ctx->data.DHCPRowStatus;

    return MFD_SUCCESS;
} /* DHCPRowStatus_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.DHCPPoolName
 * DHCPPoolName is subid 10 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.10
 * Description:
DHCP pool name.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the DHCPPoolName data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param DHCPPoolName_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param DHCPPoolName_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by DHCPPoolName.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*DHCPPoolName_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update DHCPPoolName_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
DHCPPoolName_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, char **DHCPPoolName_val_ptr_ptr, size_t *DHCPPoolName_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != DHCPPoolName_val_ptr_ptr) && (NULL != *DHCPPoolName_val_ptr_ptr));
   netsnmp_assert( NULL != DHCPPoolName_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:DHCPPoolName_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the DHCPPoolName data.
 * copy (* DHCPPoolName_val_ptr_ptr ) data and (* DHCPPoolName_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for DHCPPoolName data
     */
    if ((NULL == (* DHCPPoolName_val_ptr_ptr )) ||
        ((* DHCPPoolName_val_ptr_len_ptr ) <
         (rowreq_ctx->data.DHCPPoolName_len* sizeof(rowreq_ctx->data.DHCPPoolName[0])))) {
        /*
         * allocate space for DHCPPoolName data
         */
        (* DHCPPoolName_val_ptr_ptr ) = malloc(rowreq_ctx->data.DHCPPoolName_len* sizeof(rowreq_ctx->data.DHCPPoolName[0]));
        if(NULL == (* DHCPPoolName_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* DHCPPoolName_val_ptr_len_ptr ) = rowreq_ctx->data.DHCPPoolName_len* sizeof(rowreq_ctx->data.DHCPPoolName[0]);
    memcpy( (* DHCPPoolName_val_ptr_ptr ), rowreq_ctx->data.DHCPPoolName, rowreq_ctx->data.DHCPPoolName_len* sizeof(rowreq_ctx->data.DHCPPoolName[0]) );

    return MFD_SUCCESS;
} /* DHCPPoolName_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11DHCPIpPoolConfigEntry.DHCPApOption43
 * DHCPApOption43 is subid 11 of dot11DHCPIpPoolConfigEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.6.5.1.11
 * Description:
DHCP option43 string.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the DHCPApOption43 data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param DHCPApOption43_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param DHCPApOption43_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by DHCPApOption43.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*DHCPApOption43_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update DHCPApOption43_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
DHCPApOption43_get( dot11DHCPIpPoolConfigTable_rowreq_ctx *rowreq_ctx, char **DHCPApOption43_val_ptr_ptr, size_t *DHCPApOption43_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != DHCPApOption43_val_ptr_ptr) && (NULL != *DHCPApOption43_val_ptr_ptr));
   netsnmp_assert( NULL != DHCPApOption43_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11DHCPIpPoolConfigTable:DHCPApOption43_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the DHCPApOption43 data.
 * copy (* DHCPApOption43_val_ptr_ptr ) data and (* DHCPApOption43_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for DHCPApOption43 data
     */
    if ((NULL == (* DHCPApOption43_val_ptr_ptr )) ||
        ((* DHCPApOption43_val_ptr_len_ptr ) <
         (rowreq_ctx->data.DHCPApOption43_len* sizeof(rowreq_ctx->data.DHCPApOption43[0])))) {
        /*
         * allocate space for DHCPApOption43 data
         */
        (* DHCPApOption43_val_ptr_ptr ) = malloc(rowreq_ctx->data.DHCPApOption43_len* sizeof(rowreq_ctx->data.DHCPApOption43[0]));
        if(NULL == (* DHCPApOption43_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* DHCPApOption43_val_ptr_len_ptr ) = rowreq_ctx->data.DHCPApOption43_len* sizeof(rowreq_ctx->data.DHCPApOption43[0]);
    memcpy( (* DHCPApOption43_val_ptr_ptr ), rowreq_ctx->data.DHCPApOption43, rowreq_ctx->data.DHCPApOption43_len* sizeof(rowreq_ctx->data.DHCPApOption43[0]) );

    return MFD_SUCCESS;
} /* DHCPApOption43_get */



/** @} */
