#ifndef _WID_DBUS_DEF1_H
#define _WID_DBUS_DEF1_H
#include "wcpss/waw.h"

extern char WID_DBUS_BUSNAME[PATH_LEN];
extern char WID_DBUS_OBJPATH[PATH_LEN];
extern char WID_DBUS_INTERFACE[PATH_LEN];
/*extern char WID_DBUS_SUCCESS 0
extern char WID_DBUS_ERROR	1
extern char WID_DBUS_NO_WLAN_ID	2
extern char WID_DBUS_NO_WTP_ID	3
extern char WID_DBUS_NO_Radios_ID	4
extern char WLAN_ID_BE_USED	5
extern char WLAN_ID_NOT_EXIST	6
extern char WTP_ID_BE_USED	7
extern char WTP_ID_NOT_EXIST	8
*/
enum wid_dbus_result_no_e {
	WID_DBUS_SUCCESS,
	WID_DBUS_ERROR, /* general use, no detail error information*/
	WLAN_ID_BE_USED,
	WLAN_ID_NOT_EXIST,
	WTP_ID_BE_USED,
	WTP_ID_NOT_EXIST,	
	BSS_NOT_EXIST,
	BSS_NOT_ENABLE,
	RADIO_ID_BE_USED,
	RADIO_ID_NOT_EXIST,
	APPLY_IF_FAIL,
	WLAN_BE_ENABLE,
	INTERFACE_NOT_BE_BINDED,
	INTERFACE_NOT_EXIST,
	INTERFACE_HAVE_NO_IP_ADDR,	//xiaodawei add for interface have no ip address, 20110323
	WTP_BE_USING,
	Wlan_IF_NOT_BE_BINDED,
	WTP_IF_NOT_BE_BINDED,
	WTP_WLAN_BINDING_NOT_MATCH,
	WTP_CLEAR_BINDING_WLAN_SUCCESS,
	WLAN_NOT_BINDING_IF,
	WID_UNKNOWN_ID,
	WTP_NO_SURPORT_TYPE,
	WTP_NO_SURPORT_Rate,
	RADIO_IS_DISABLE,
	WTP_OVER_MAX_BSS_NUM,
	WTP_IS_NOT_BINDING_WLAN_ID,
	WLAN_CREATE_L3_INTERFACE_FAIL,
	WLAN_DELETE_L3_INTERFACE_FAIL,
	BSS_CREATE_L3_INTERFACE_FAIL,
	BSS_DELETE_L3_INTERFACE_FAIL,
	WLAN_CREATE_BR_FAIL,
	WLAN_DELETE_BR_FAIL,
	BSS_L3_INTERFACE_ADD_BR_FAIL,
	BSS_L3_INTERFACE_DEL_BR_FAIL,
	PAST_L3_INTERFACE_ERROE,
	UNKNOWN_ERROR,
	WTP_NOT_IN_RUN_STATE,
	WLAN_BE_DISABLE,
	BSS_BE_ENABLE,
	BSS_IF_NEED_CREATE,
	SYSTEM_CMD_ERROR,
	BSS_IF_NEED_DELETE,
	L3_INTERFACE_ERROR,
	AUTO_AP_LOGIN_INTERFACE_ERROR,
	AUTO_AP_LOGIN_INTERFACE_NOT_SET,
	AUTO_AP_LOGIN_WLAN_NOT_SET,
	WID_QOS_BE_USED,
	WID_QOS_NOT_EXIST,
	WID_QOS_RADIO_SHOULD_BE_DISABLE,
	WID_QOS_WMM_MAP_DISABLE,
	WID_QOS_STREAM_ERROR,
	WID_QOS_PARAMETER_ERROR,
	WID_QOS_PARAMETER_VALUE_ERROR,
	WID_QOS_BE_USED_BY_RADIO,      /*fengwenchao add 20110427*/
	WID_EBR_ERROR,
	WID_EBR_BE_USED,
	WID_EBR_NOT_EXIST,
	WID_EBR_SHOULD_BE_DISABLE,
	WID_EBR_IFLIST_EMPTY,
	WID_WTP_LOCATION_NOT_SET,
	SUPPORT_VERSION_NOT_EXIST,
	VERSION_NOT_SUPPORTED,
	SAMPLE_THROUGHPUT_NOT_ENABLE,
	IF_POLICY_CONFLICT,
	WID_NO_SURPORT_MODEL,
	WTP_OVER_MAX_NUM,
	WTP_LESS_THAN_STATIC_WTP,
	WTP_SN_BE_USED,
	RADIO_SUPPORT_RATE_EMPTY,
	WTP_NO_NEIGHBORAP,
	RADIO_SUPPORT_RATE_ONE,
	RADIO_SUPPORT_RATE_EXIST,
	RADIO_SUPPORT_RATE_NOT_EXIST,
	RADIO_SUPPORT_MAX_RATE_NOT_ONE,
	RADIO_SUPPORT_RATE_CONFLICT,
	WID_NO_WHITELIST,
	WID_NO_BLACKLIST,
	WID_AP_SCANNING_DISABLE,
	WID_TRANSMIT_POWER_CONTROL_DISABLE,
	WLAN_APPLY_SECURITY_FIRST,
	WLAN_NOT_NEED_NAS,
	WID_BINDING_WLAN,
	WLAN_NOT_BINDING_VLAN,
	WLAN_BINDING_VLAN,
	MALLOC_ERROR,
	SWITCH_IS_DISABLE,
	SWITCH_HAS_ALREADY_SETTED,
	WID_AP_NO_STATICS,
	TXPOWER_OVER_TW,
	TXPOWER_OVER_TW_THREE,
	MODEL_NO_EXIST,
	MODEL_NO_CONFIG,
	RAOMING_DISABLE_FIRST,
	ISOLATION_CONFLICT,
	UPDATE_CONFIG_FAIL,
	WTP_WEP_NUM_OVER,
	RADIO_MODE_IS_11N,
	WDS_MODE_BE_USED,
	RADIO_NO_BINDING_WLAN,
	WTP_ID_LARGE_THAN_MAX,
	RADIO_ID_LARGE_THAN_MAX,
	WLAN_ID_LARGE_THAN_MAX,				/*for check*/
	BSS_ID_LARGE_THAN_MAX,
	WTP_MAC_BE_USED,
	NO_WIDS_DEVICE,
	NO_SURPPORT_IPIP,
	VALUE_IS_NONEED_TO_CHANGE,/*used to mark value is the same to the command,so no need to be changed*/
	UPDATE_PROCESS,
	AC_IP_EXIST,
	AC_IP_NOT_EXIST,
	AC_IP_BIND_IF_EXIST,
	AC_BALANCE_STATE,
	AC_BALANCE_FLOW,
	AC_BALANCE_NUM,
	BINDING_IPV6_ADDRE_RROR,
	
	ETH_NOT_EXIST,
	RADIO_NO_BINDING_WQOS,
	WID_EBR_IF_NOEXIT,
	RADIO_ENCRYPTION_NO_MATCH,	
	RADIO_BRMAC_NOT_EXIST,
	RADIO_NOT_SUPPORT_COMMAND,
	RADIO_SECTOR_DISABLE,

	WLAN_SERVICE_CONTROL_BE_USED,
	WTP_NO_SURPORT_CHANNEL,
	RADIO_AMPDU_DISABLE,
	MAC_DOESNOT_EXIT,
	MAC_ALREADY_EXIT,
	WID_NEED_REBOOT,
	RADIO_HT_IS_NOT_40,	
	GROUP_ID_EXIST,
	GROUP_ID_NOT_EXIST,
	RADIO_CHANNEL_OFFSET_NEED_BE_RESET,
	WID_ILLEGAL_INPUT,
	RADIO_11N_AMPDU_MUTEX,    //zhangshu add 2010-10-12
	RADIO_11N_AMSDU_MUTEX,     //zhangshu add 2010-10-12
	WRONG_LICENSE_LIST,					//xiaodawei append 20101104
	LICENSE_NUM_LARGER_THAN_MAX,		//xiaodawei append 20101104
	LICENSE_NUM_LESS_THAN_TWO,			//xiaodawei append 20101104
	LICENSE_NOT_EXIST,					//xiaodawei append 20101104
	LICENSE_TYPE_DUPLICATED,			//xiaodawei append 20101104
	LICENSE_TYPE_BINDED,				//xiaodawei append 20101104
	LICENSE_NO_BINDING_SUCCESS,			//xiaodawei append 20101108
	LICENSE_NOT_BINDED,					//xiaodawei append 20101108
	LICENSE_BINDED_ANOTHER,				//xiaodawei append 20101108
	CURRENT_NUM_MORE_THAN_MAX,			//xiaodawei append 20101108
	RADIO_CHAINMASK_NUM_1,         //zhangshu add 20101124
	RADIO_CHAINMASK_NUM_2,         //zhangshu add 20101124
	AP_L2_ISOLATION_ENABLE_OR_DIS_ALREADY,		//xiaodawei add for ap l2 isolation enable or disable already, 20101207
	SECURITYINDEX_IS_SAME,   //fengwenchao add 20110110
	RADIO_SET_TXPOF_COUNTRY_CODE_ERROR,		//fengwenchao append,20101213
	SET_MAX_STANUM_SMALLER_THAN_CURRENT_STANUM,   //fengwenchao append,20101213
	CHECK_CHANNEL_CWMODE_FAIL,		//fengwenchao append,20101213
	CHECK_COUNTRY_CODE_FAIL,			//fengwenchao append,20101213
	WID_ADD_RADIO_IF_FAIL,
	WID_ADD_BLACK_WHITE_OUI_MAC_ERR,
	WID_DEL_BLACK_WHITE_OUI_MAC_ERR,
	RADIO_SERVICE_CONTROL_BE_USED,
	MCS_CROSS_THE_BORDER,      //fengwenchao append 20110408
	IF_HAS_BEEN_LISTENNING,
	TXPOWEROFF_LARGER_THAN_MAX,	//xiaodawei add, txpoweroffset*step > max_txpower
	MAC_MPDU_MSDU_MODE,
	WLAN_IF_NOT_BE_TUNNELMODE,	
	WID_STATE_BE_SAME,
	WID_INTERFACE_NOT_BE_LOCAL_BOARD,	
	ESSID_LIST_IS_NULL,				//weichao append, 20110914
	ESSID_NOT_EXIT,					//weichao append,20110914
	IF_BINDING_FLAG,  //fengwenchao copy from 1318 for AXSSZFI-839
	RADIO_IN_EBR,    //fengwenchao add for radio whether in ebr check
	FLOW_CHECK_BE_DISABLE,
	ACCOUNT_AFTER_AUTHORIZE,
	MODEL_BIND_EVER,			//mahz add for ap upgrade
	MODEL_BIND_NEVER,
	WID_MAC_ADD_ALREADY,
	WID_UPGRADE_NUM_OVERFLOW,
	INTERFACE_NOT_L3_IF,
	INVALID_TYPE,
	MORE_THAN_ONE_IF,
	NO_IF_HAS_THIS_IP,
	AC_STATE_IP_NOT_EXIST,
	AC_STATE_FIRST_DISABLE,
	WID_SINGLE_RADIO,
	DELETE_WLAN_SPEN_TOO_MUCH_TIME,    // create a new thread to delete wlan. Huangleilei add it for AXSSZFI-1622
	WID_WANT_TO_DELETE_WLAN		/* Huangleilei add for ASXXZFI-1622 */
};

enum wid_radio_type {
	IEEE80211_11B = 0x1,
	IEEE80211_11A = 0x2,
	IEEE80211_11G = 0x4,
	IEEE80211_11N = 0x8,
	IEEE80211_11AN = 0x10,      //fengwenchao add for GM 20111109
	IEEE80211_11GN = 0x20,      //fengwenchao add for GM 20111109

};

enum wid_check_type {
	WID_WTP_CHECK,
	WID_WLAN_CHECK,
	WID_RADIO_CHECK,
	WID_SECURITY_CHECK,

};


/*
 arg lists for method WID_DBUS_CONF_METHOD_SHOWWLAN
  in arg list:
	BYTE WlanID //ID of WLAN which is unique sign of wlan
  out arg list:  // in the order as they are appended in the dbus message.
	STRING 	WLANNAME//name of wlan
	BYTE 	WLANID//ID of WLAN which is unique sign of wlan
	STRING 	ESSID//essid of wlan
	BYTE	AAW//aute add wtp 0(disable)/1(default enable)
	BYTE	STATUS//WLAN Status 0(default disable)/1(enable)
	BYTE	VID//num of vlan which wlan in
	BYTE	Wlan_Index
*/
extern char WID_DBUS_CONF_METHOD_SHOWWLAN[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOWWLAN_OF_ALL[PATH_LEN];    //fengwenchao add 20101223
extern char WID_DBUS_CONF_METHOD_WLANLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WTPLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WTPLIST_BYMAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WTPLIST_NEW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOWWTP_BYMODEL[PATH_LEN];    //fengwenchao add 20110226
extern char WID_DBUS_CONF_METHOD_SHOWWTP_BYVERSION[PATH_LEN];  //fengwenchao add 20110314
extern char WID_DBUS_CONF_METHOD_WTPLIST_NEW_BYINTERFACE[PATH_LEN];		//xiaodawei add, 20110301
extern char WID_DBUS_CONF_METHOD_WTPLIST_UPDATE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AC_ACCESS_WTPLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAN_AC_ACCESS_WTPLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_OLD_AP_IMG[PATH_LEN];


extern char WID_DBUS_CONF_METHOD_ACVERSION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ECHOTIMER[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WTP_RUNNING_CONFIG[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WLAN_SHOW_RUNNING_CONFIG_START[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WLAN_SHOW_RUNNING_CONFIG_END[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WTP_SHOW_RUNNING_CONFIG_START[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WTP_SHOW_RUNNING_CONFIG_END[PATH_LEN];
/*
 arg lists for method WID_DBUS_CONF_METHOD_WLAN
  in arg list:
	BYTE WlanID //ID of WLAN which is unique sign of wlan
  out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_CONF_METHOD_WLAN[PATH_LEN];

/*
 arg lists for method WID_DBUS_CONF_METHOD_SHOWWTP
  in arg list:
	BYTE WTPID //ID of WTP which is unique sign of wtp
  out arg list:  // in the order as they are appended in the dbus message.
	STRING 	WTPNAME//name of wtp
	BYTE 	WTPID//ID of wtp which is unique sign of wtp
	UNIT32	WTPSN//sn of wtp
	UNIT32	WTPMOD//model of wtp
	STRING	WTPIP//ip of wtp
	STRING	WTPMAC//mac of wtp
	BYTE	CTR_ID//id of control tunnel
	BYTE	DTA_ID//id of data tunnel
*/
extern char	WID_DBUS_CONF_METHOD_SHOWWTP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_CONFIG_WTP[PATH_LEN];  //fengwenchao add 20101223

extern char	WID_DBUS_WTP_METHOD_SHOW_WTP_MODEL_CODE_VERSION[PATH_LEN];


/*
 arg lists for method WID_DBUS_CONF_METHOD_WTP
  in arg list:
	BYTE WTPID //ID of WLAN which is unique sign of wlan
  out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_CONF_METHOD_WTP[PATH_LEN];


/*
 arg lists for method WID_DBUS_CONF_METHOD_SHOWRADIO
  in arg list:
	BYTE Radio_G_ID //global ID of radio which is unique sign of radio
  out arg list:  // in the order as they are appended in the dbus message.
	BYTE	WTPID
	BYTE	Radio_G_ID
	BYTE	Radio_L_ID
	UNIT32	Radio_TYPE//type of Radio(a/b/g/n)
	BYTE	Radio_Chan//channel of radio
	UNIT16	Radio_TXP//tx power of radio
	BYTE	AdStat//state of admin
	BYTE	OpStat//state of operate
*/
extern char	WID_DBUS_CONF_METHOD_SHOWRADIO[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_RADIOLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_RADIO[PATH_LEN];

/*
 arg lists for method WID_DBUS_CONF_METHOD_ADD_DEL_WLAN
  in arg list:
	BYTE	isADD //determine ADD(1) or DEL(0)	
  	STRING  WLANNAME//name of wlan
  	BYTE	  WLANID//ID of WLAN which is unique sign of wlan
  	STRING  ESSID//essid of wlan
  out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char	WID_DBUS_CONF_METHOD_ADD_DEL_WLAN[PATH_LEN];
extern char	WID_DBUS_CONF_METHOD_ADD_DEL_WLAN_CN[PATH_LEN];

/*
 arg lists for method WID_DBUS_CONF_METHOD_ADD_DEL_WTP
  in arg list:
	BYTE	isADD //determine ADD(1) or DEL(0)	
	STRING 	WTPNAME//name of wtp
	BYTE 	WTPID//ID of wtp which is unique sign of wtp
	UNIT32	WTPSN//sn of wtp
	UNIT32	WTPMOD//model of wtp
  out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char	WID_DBUS_CONF_METHOD_ADD_DEL_WTP[PATH_LEN];

extern char	WID_DBUS_CONF_METHOD_ADD_DEL_WTP_BY_MAC[PATH_LEN];


extern char WID_DBUS_CONF_METHOD_UPDATE_WTP_COUNT[PATH_LEN];
	
extern char	WID_DBUS_WLAN_OBJPATH[PATH_LEN];
extern char WID_DBUS_WLAN_INTERFACE[PATH_LEN];


/*
arg lists for method WID_DBUS_CONF_METHOD_WLAN_ENABLE
 in arg list:
   	BYTE	WlanID//id of wlan which you want enable or disable
  	BYTE	DisWLAN //determine disable(1) or enable(0)WLAN  
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_WLAN_METHOD_ENABLE[PATH_LEN];
extern char WID_DBUS_WDS_METHOD_ENABLE[PATH_LEN];


/*
arg lists for method WID_DBUS_CONF_METHOD_WLAN_APPLY_IF
 in arg list:
   	BYTE	WlanID//id of wlan which you want enable or disable
  	STRING	interface//which interface wlan apply  
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_WLAN_METHOD_APPLY_IF[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_APPAY_WTP_IFNAME[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_APPAY_WTP_MAX_STA[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_APPAY_WTP_TRIGER[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_APPAY_WTP_FLOW_TRIGER[PATH_LEN];
extern char WID_DBUS_WTP_INTERFACE_CHECK_WTP_STA[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_FLOW_CHECK[PATH_LEN];				//weichao add 2011.10.28
extern char WID_DBUS_WLAN_METHOD_NO_FLOW_TIME[PATH_LEN];			//weichao add 2011.10.31
extern char WID_DBUS_WLAN_METHOD_LIMIT_MIN_FLOW[PATH_LEN];			//weichao add 2011.10.31

extern char WID_DBUS_WTP_METHOD_APPAY_WTP_WLANID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_IFNAME[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_MAX_STA[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WLAN_MAX_STA_NEW[PATH_LEN]; //fengwenchao add 20120323
extern char WID_DBUS_WLAN_METHOD_WLAN_L2_ISOLATION[PATH_LEN]; //fengwenchao add 20120323
extern char WID_DBUS_WLAN_METHOD_WLAN_STA_STATIC_ARP[PATH_LEN]; //fengwenchao add 20120323
extern char WID_DBUS_WLAN_METHOD_WLAN_ACCESS_STA_LIMIT_RSSI[PATH_LEN];  //fengwenchao add 20120323
extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_BALANCE_PARA[PATH_LEN]; /*xm  08/12/29*/
extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_FLOW_BALANCE_PARA[PATH_LEN];/*xm  09/02/05*/

extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_BALANCE_SWITCH[PATH_LEN];/*xm  08/12/29*/
extern char WID_DBUS_WTP_METHOD_WTP_USED[PATH_LEN];
/*added by weiay 20080701*/
extern char WID_DBUS_WTP_METHOD_DELETE_WLAN_ID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_DISABLE_WLAN_ID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_ENABLE_WLAN_ID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WLAN_ID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_VERSION_PATH[PATH_LEN];/*xm 08/08/29*/
extern char WID_DBUS_WTP_METHOD_CONFIG_PORT_ENABLE[PATH_LEN];/*xm 08/09/01*/
extern char WID_DBUS_WTP_METHOD_CONFIG_PORT[PATH_LEN];/*xm 08/09/01*/
extern char WID_DBUS_WTP_METHOD_SET_WTPNAME[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTPSN[PATH_LEN];

extern char WID_DEBUS_WLAN_METHOD_SET_EAP_MAC[PATH_LEN]; //zhangshu 2010-10-22
/* zhangshu add for terminal distrub info, 2010-10-08 */
extern char WID_DBUS_WTP_METHOD_SET_WTP_TERMINAL_DISTRUB_INFOMATION_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_TERMINAL_DISTRUB_INFOMATION_PKT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_TERMINAL_DISTRUB_INFOMATION_STA_NUM[PATH_LEN];

extern char WID_DBUS_METHOD_SET_AP_HEART_STATISTICS_SWITCH[PATH_LEN];   //fengwenchao add for GM-3,20111130
extern char WID_DBUS_METHOD_SET_AP_HEART_STATISTICS_COLLECT_TIME[PATH_LEN];  //fengwenchao add for GM-3,20111130
extern char WID_DBUS_WTP_METHOD_SET_WTP_EXTENSION_INFOMATION_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_EXTENSION_INFOMATION_REPORTINTERVAL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_USERNAME_PASSWORD[PATH_LEN] ;
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_DEAUTH_MESSAGE_REPORT_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_ALL_FLOW_INFORMATION_REPORT_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_INFOMATION_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_INFOMATION_REPORTINTERVAL[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_CHECK_WLANID[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_INTERVAL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_THRESHOLD[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_LASTTIME_IN_BLACK[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AC_MASTER_BAK_CORRECT_WTP_STATE_TIMER[PATH_LEN]; //fengwenchao add 20120117 for onlinebug-96
extern char WID_DBUS_WTP_METHOD_SET_WTP_IF_INFO_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AC_ACTIVE_BAK_STATE[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_SET[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_WIDS_SET[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_IF_INFO_REPORTINTERVAL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_INTERFACE_UPDOWN[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_INTERFACE_ETH_RATE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_IF_INFO[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_NTPCLIENT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_UPDATE_WTP_CONFIG[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_ALL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_BY_WLANID[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_BY_INTERFACE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_BY_MODEL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_REBOOT_BY_LIST[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_GET_WTP_BSS_PKT_INFO[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_BSS_PKT_INFO[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_RADIO_PKT_INFO[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_RADIO_PKT_INFO_TUNNEL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_ETH_PKT_INFO[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SHOW_WTP_WIFI_SNR_INFO[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_PORT_VLAN_SECURITY[PATH_LEN];  /*sz20080827*/
extern char WID_DBUS_WTP_METHOD_SET_PORT_VLAN_ENABLE[PATH_LEN];  /*sz20080827*/
extern char WID_DBUS_WTP_METHOD_SET_SECURITY[PATH_LEN]; /*sz20080827*/
extern char WID_DBUS_WTP_METHOD_SET_VLAN_LIST_ENABLE[PATH_LEN];  /*sz20080827*/
extern char WID_DBUS_WTP_METHOD_DELETE_AP_MODEL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AP_TIMER[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AP_CHECKTIMER[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AP_COLLECT_TIME[PATH_LEN];	/*nl 2010/07/13*/
extern char WID_DBUS_WLAN_METHOD_DELETE_IF[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_IF[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_HIDE_ESSID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_L3IF_POLICY[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_L3IF_POLICY2[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_NAS_IDENTIFIER[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_REMOVE_NAS_IDENTIFIER[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_ROAMING_POLICY[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_BRIDGE_ISOLATION[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_BRIDGE_MULTICAST_ISOLATION[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_BRIDGE_ISOLATION[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_BRIDGE_SAMEPORTSWICTH[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_ESSID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_ASCII_ESSID[PATH_LEN];     /*fengwenchao add 20110307*/
extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_SEND_TRAFFIC_LIMIT_VALUE[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_STA_AVERAGE_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_STA_AVERAGE_SEND_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_WHOLE_WLAN_BSS_MULTI_USER_OPTIMIZE_SWITCH[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_MOLTI_USER_OPTIMIZE_SWITH [PATH_LEN];
extern char  WID_DBUS_WTP_METHOD_5G_SWITH [PATH_LEN];


extern char WID_DBUS_WLAN_METHOD_UNDO_WLAN_VLANID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_WLAN_VLANID[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_NAS_PORT_ID[PATH_LEN];			//mahz add 2011.5.25
extern char  WID_DBUS_WLAN_METHOD_SET_WLAN_HOTSPOTID[PATH_LEN];		
extern char  WID_DBUS_WLAN_METHOD_CLEAN_WLAN_HOTSPOTID[PATH_LEN];		
extern char WID_DBUS_WLAN_METHOD_SET_TUNNEL_WLAN_VLAN[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_TUNNEL_WLAN_VLAN[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SET_WLAN_VLAN_PRIORITY[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_WLAN_VLAN_INFO[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_L3IF_POLICY_BR[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_L3IF_POLICY2_BR[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_WSM_STA_INFO_REPORTSWITCH[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_WSM_STA_INFO_REPORTINTERVAL[PATH_LEN];
/*added end 20080701*/

extern char WID_DBUS_WTP_OBJPATH[PATH_LEN];
extern char WID_DBUS_WTP_INTERFACE[PATH_LEN];



extern char	WID_DBUS_RADIO_OBJPATH[PATH_LEN];
extern char WID_DBUS_RADIO_INTERFACE[PATH_LEN];

/*
arg lists for method WID_DBUS_CONF_METHOD_RADIO_STXP
 in arg list:
   	BYTE	Radio_G_ID//Global id of Radio
	UNIT16	Radio_TXP//tx power of radio
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_RADIO_METHOD_SET_TXP[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_TXPOF[PATH_LEN];

/*
arg lists for method WID_DBUS_CONF_METHOD_RADIO_SCHAN
 in arg list:
   	BYTE	Radio_G_ID//Global id of Radio
	BYTE	Radio_Chan//channel of radio
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_RADIO_METHOD_SET_CHAN[PATH_LEN];
/*added by weiay 20080714*/

extern char WID_DBUS_RADIO_METHOD_SET_RATE[PATH_LEN];
extern char WID_DBUG_RADIO_METHOD_SET_11N_RATE_PARAS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_MODE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_FRAGMENTATION[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_BEACON[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RTSTHROLD[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_DTIM[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_STATUS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WDS_STATUS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_PREAMBLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_LONGRETRY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_SHORTRETRY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_BSS_MAX_STA[PATH_LEN];


extern char WID_DBUS_RADIO_METHOD_SET_SUPPORT_RATELIST[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_MAX_RATE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_BSS_L3_POLICY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_BSS_MAX_THROUGHPUT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_BSS_MAX_THROUGHPUT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_CHANNEL_CHANGE[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_BASE_VLANID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_CLEAN_VLANID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_CHECK_RADIO_MEMBER[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_BASE_NAS_PORT_ID[PATH_LEN];	//mahz add 2011.5.30
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_CLEAN_NAS_PORT_ID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_BASE_HOTSPOT_ID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_RADIO_APPLY_WLANID_CLEAN_HOTSPOT_ID[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_SET_BSS_L3_IF_WLAN_BR[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_RADIO_QOS[PATH_LEN];

/*
arg lists for method WID_DBUS_CONF_METHOD_RADIO_APPLY_WLAN
 in arg list:
   	BYTE	Radio_G_ID//Global id of Radio
	BYTE	WlanID//id of wlan which radio apply
out arg list:  // in the order as they are appended in the dbus message.
	UNIT32	ret//success or fail(reason)
*/
extern char WID_DBUS_RADIO_METHOD_APPLY_WLAN[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_DELETE_WLAN[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_ENABLE_WLAN[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_DISABLE_WLAN[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_WDS_WLAN_SET[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_WDS_BSSID_INFO[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_REVOVER_DEFAULT_CONFIG[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_SET_MAX_THROUGHOUT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RADIO_L2_ISOLATION_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_11N_SET_RADIO_CWMMODE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SHOW_BSS_LIST[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_SET_WTP_RADIO_AUTO_CHANNEL[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WTP_RADIO_DIVERSITY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WTP_RADIO_TXANTENNA[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WTP_RADIO_AUTO_CHANNEL_CONT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_INTER_VAP_FORVARDING_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_INTRA_VAP_FORVARDING_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_KEEP_ALIVE_PERIOD[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_KEEP_ALIVE_IDLE_TIME[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_CONGESTION_AVOID_STATE[PATH_LEN];


extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_AVERAGE_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_STA_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_CANCEL_STA_VALUE[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_SEND_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_AVERAGE_SEND_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_STA_SEND_VALUE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_TRAFFIC_LIMIT_CANCEL_STA_SEND_VALUE[PATH_LEN];

extern char	WID_DBUS_QOS_OBJPATH[PATH_LEN];
extern char WID_DBUS_QOS_INTERFACE[PATH_LEN];

extern char WID_DBUS_QOS_METHOD_ADD_DEL_QOS[PATH_LEN];

extern char WID_DBUS_QOS_METHOD_SHOW_QOS_LIST[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SHOW_QOS[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_CONFIG_QOS[PATH_LEN];

extern char WID_DBUS_QOS_METHOD_SET_QOS_INFO[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_INFO_CLIENT[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_MAP[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_WMM_MAP_DOT1P[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_DOT1P_MAP_WMM[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_APPLY_QOS[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_DELETE_QOS[PATH_LEN];
/*set wireless qos info for mib*/
extern char WID_DBUS_QOS_METHOD_SET_QOS_TOTAL_BANDWIDTH[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SHOW_QOS_EXTENSION_INFO[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_FLOW_PARAMETER[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_PARAMETER[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DELETE_RADIO_WITH_QOS_PROFILE[PATH_LEN];   //fengwenchao add 20110427
extern char WID_DBUS_QOS_METHOD_SET_QOS_POLICY[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_POLICY_NAME[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_MANAGE_ARITHMETIC_NAME[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SHOW_RADIO_QOS_INFO[PATH_LEN];

/*ethereal bridge infomation area*/
extern char	WID_DBUS_EBR_OBJPATH[PATH_LEN];
extern char WID_DBUS_EBR_INTERFACE[PATH_LEN];

extern char WID_DBUS_EBR_METHOD_ADD_DEL_EBR[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SHOW_EBR_LIST[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SHOW_EBR[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_CONFIG_EBR[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_CONFIG_EBR_ENABLE[PATH_LEN];

extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_ISOLATION[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_MULTICAST_ISOLATION[PATH_LEN];

extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_UCAST_SOLICT[PATH_LEN];			/* Huang Leilei add, 2012-11-12 11:24 */
extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_MCAST_SOLICT[PATH_LEN];			/* Huang Leilei add, 2012-11-12 20:09 */

extern char WID_DBUS_EBR_METHOD_SET_EBR_ADD_DEL_IF[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SET_BRIDGE_SAMEPORTSWITCH[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_EBR_INTERFACE_EBR[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SET_MULTICAST_FDB_LEARN[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_EBR_SHOW_RUNNING_CONFIG_START[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_EBR_SHOW_RUNNING_CONFIG_END[PATH_LEN];

/*
Wid config infomation 
*/

extern char WID_DBUS_CONF_METHOD_ADD_OUI[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ADD_ESSID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ADD_ATTACK_MAC[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_DEL_OUI[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_ESSID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_ATTACK_MAC[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_OUI_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ESSID_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ATTACK_MAC_SHOW[PATH_LEN];




extern char WID_DBUS_CONF_METHOD_WIDCONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LEV3_PROTOCOL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SECURITY_TYPE[PATH_LEN];	
extern char WID_DBUS_CONF_METHOD_HW_VERSION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SW_VERSION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AC_NAME[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_MAX_WTP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MAX_MTU[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LOG_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LOG_SIZE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LOG_LEVEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DAEMONLOG_DEBUG_OPEN[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_HNLOG_SWITCH_ACTIVATED[PATH_LEN];//qiuchen add it for Henan mobile 2013.02.21
extern char WID_DBUS_CONF_METHOD_SET_AC_MANAGEMENT_IP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SCANNING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SCANNING_REPORT_INTERVAL[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_UPDATE_AP_SCANNING_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WHITELIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BLACKLIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WHITELIST_DELETE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BLACKLIST_DELETE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ROGUE_AP_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ROGUE_AP_THRESHOLD[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_ROGUE_AP_LIST_V1[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ROGUE_AP_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DYNAMIC_CHANNEL_SELECTION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DYNAMIC_CHANNEL_SELECTION_RANGE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_NEIGHBOR_AP_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_NEIGHBOR_AP_LIST[PATH_LEN];   //fengwenchao add 20101220
extern char WID_DBUS_CONF_METHOD_NEIGHBOR_AP_LIST_BYWTPID2[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WHITELIST_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BLACKLIST_SHOW[PATH_LEN];
/*country code area*/
extern char WID_DBUS_CONF_METHOD_SET_COUNTRY_CODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_UNDO_COUNTRY_CODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_COUNTRY_CODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TRANSMIT_POWER_CONTROL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TXPOWER_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ROGUE_AP_TRAP_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_COVERAGE_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_NEIGHBOR_RSSI_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CONTROL_SCOPE[PATH_LEN];
/*auto ap area*/
extern char WID_DBUS_CONF_METHOD_SET_WID_DYNAMIC_AP_LOGIN_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_DYNAMIC_AP_LOGIN_L3_INTERFACE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_LISTEN_L3_INTERFACE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_LISTEN_IP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_LISTEN_L3_INTERFACE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WID_DYNAMIC_AP_LOGIN_WLANID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_WID_DYNAMIC_AP_LOGIN_WLANID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_DYNAMIC_AP_LOGIN_SAVE_CONFIG_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_DYNAMIC_AP_LOGIN_SAVE_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_WID_DYNAMIC_AP_LOGIN_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_DATA_EXCLUDE_MULTICAST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_STATISTICS[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_STATISTICS_INTERVAL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_TIMESTAMP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_STATISTICS_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_IPADDR[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_AP_IP_GATEWAY_DNS[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_NETWORK[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AC_LOAD_BALANCE[PATH_LEN];
extern char WID_DBUS_CONF_AC_LOAD_BALANCE_PARA[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_INTERFACE_ETH_MTU[PATH_LEN];  //fengwenchao add 20110126



extern char WID_DBUS_CONF_METHOD_SET_WID_AC_EXTENTION_INFOR_ENABLE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WID_AP_MAX_THROUGHOUT[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WID_AP_EXTENSION_COMMAND[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_AP_OPTION60_PARAMETER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_WID_AP_IP_GATEWAY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TCPDUMP_AP_EXTENSION_COMMAND[PATH_LEN];

/*mib area*/
extern char WID_TRAP_OBJPATH[PATH_LEN];
extern char WID_TRAP_INTERFACE[PATH_LEN];

extern char WID_DBUS_TRAP_WID_WTP_ENTER_IMAGEDATA_STATE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_CHANGE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WLAN_ENCRYPTION_TYPE_CHANGE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WLAN_PRESHARED_KEY_CHANGE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_TRANFER_FILE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_UPDATE_SUCCESSFUL[PATH_LEN];   /*fengwenchao add 20110216*/
extern char WID_DBUS_TRAP_WID_WTP_UPDATE_FAIL[PATH_LEN];   /*fengwenchao add 20110216*/

extern char WID_DBUS_TRAP_WID_WTP_CODE_START[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_ELECTRIFY_REGISTER_CIRCLE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_AP_DOWN[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_AP_REBOOT[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_IP_CHANGE_ALARM[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_ACTIMESYNCHROFAILURE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_DEVICE_INTERFERENCE_DETECTED[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_SHOW_RUNTIME[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_REMOTE_RESTART[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_DIVORCE_NETWORK[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_AP_FLASH_WRITE_FAIL[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_RUNTIME[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_WTP_LOCATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_LOCATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_WTP_NETID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_NETID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_MONITOR_TIME[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_SAMPLE_TIME[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_SAMPLE_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_MONITOR_ENABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_SAMPLE_ENABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_IPFWD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_IPFWD[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_AP_UPDATE_TIMER[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_UPDATE_TIMER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_AP_L2_ISOLATION_ABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_AP_PREVENT_DOS_ATTACK[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_AP_IGMP_SNOOPING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_MIB_INFO[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_AP_CM_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_CM_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_CM_STATISTICS[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AC_BALANCE_CONFIGURATION[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_AP_CHANNEL_DISTURB_TRAP[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_MODEL_INFOMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_MODEL_CODE_INFOMATION[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_EXTENSION_INFOMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_EXTENSION_INFOMATION_V2[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_EXTENSION_INFOMATION_V3[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_EXTENSION_INFOMATION_V4[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_MAX_POWER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_RRM_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_SHOW_WTP_TXPOWER_CONTROL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_RECEIVER_SIGNAL_LEVEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_RECEIVER_SIGNAL_LEVEL[PATH_LEN];

extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_DEVICE_INTERFERENCE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_AP_INTERFERENCE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_NEIGHBOR_CHANNEL_AP_INTERFERENCE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_TERMINAL_INTERFERENCE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_COUNT_MINOR[PATH_LEN];

extern char WID_DBUS_TRAP_WID_WTP_AC_DISCOVERY_DANGER_AP[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_AC_DISCOVERY_COVER_HOLE[PATH_LEN];

extern char WID_DBUS_TRAP_WID_AP_CPU_THRESHOLD[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_MEM_THRESHOLD[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_TEMP_THRESHOLD[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_ROGUE_THRESHOLD[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_WIFI_IF_ERROR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_ATH_ERROR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_RRM_STATE_CHANGE[PATH_LEN];
extern char WID_DBUS_TRAP_WID_AP_RUN_QUIT[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_SAMPLE_THROUGHPUT_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_WLAN_VLAN_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WID_WTP_ETH_IF_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_WATCH_DOG[PATH_LEN];

/* add for sample  begin*/
extern char WID_DBUS_WTP_METHOD_SET_WTP_MOMENT_INFOMATION_SWITCH[PATH_LEN];     
extern char WID_DBUS_WTP_METHOD_SET_WTP_MOMENT_INFOMATION_REPORTINTERVAL[PATH_LEN];      
extern char WID_DBUS_WTP_METHOD_SET_WTP_SAMPLE_INFOMATION_REPORTINTERVAL[PATH_LEN];	
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_ROUTINE_INFOMATION_REPORTINTERVAL[PATH_LEN];		
extern char WID_DBUS_WTP_METHOD_SHOW_WTP_MOMENT_INFOMATION_REPORTINTERVAL[PATH_LEN];		
/* add for sample  end*/

/*******************************************for mib optimize begin**********************************************/
/*add by nl for showing wtp information for mib need 20100507*/
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_BASIC_INFORMATION[PATH_LEN];	
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_COLLECT_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_PARA_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_WIRELESS_IFSTATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_DEVICE_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_DATA_PKTS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WLAN_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WLAN_SSID_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_INFORMATION[PATH_LEN];    /*fengwenchao add 20110617*/
extern char WID_DBUS_CONF_METHOD_SHOW_INFO_BYWLANID[PATH_LEN];    /*fengwenchao add 20110617*/
extern char WD_DBUS_CONF_METHOD_SHOW_INFO_ALLWLAN[PATH_LEN];  /*fengwenchao add 20110617*/
extern char WID_DBUS_CONF_METHOD_SHOW_INFO_BYWTPID[PATH_LEN];   /*fengwenchao add 20110617*/
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_IFNAME_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_RADIO_PARA_INFOR_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_ETH_PORT_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_RADIO_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_RADIO_CONFIG_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_WIRED_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_WIRELESS_STATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_NEW_WTPWIRELESS_IF_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_NEW_WTP_WIRELESS_IFSTATS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_ROGUE_WTP_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_HIDE_QUIT_WTP_INFOR_IN_MIB_SHOWING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_NETWORK_INFO[PATH_LEN];/*xdw add for show ap network information of all wtp, 20101215*/
/* zhangshu add 2010-08-30 */
extern char WID_DBUS_CONF_METHOD_SET_WTP_TRAP_IGNORE_PERCENT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_HIDE_QUIT_WTP_INFOR_IN_MIB_SHOWING[PATH_LEN];

//mahz add 2011.1.21
extern char WID_DBUS_CONF_METHOD_SHOW_RADIO_INFO_BYWTPID_WID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BSS_ADD_MAC_LIST[PATH_LEN];		//mahz add 2011.5.12
extern char WID_DBUS_CONF_METHOD_BSS_DEL_MAC_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_BSS_USE_MAC_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_BSS_MAC_LIST[PATH_LEN];

/*fengwenchao add 20110329*/
extern char WID_DBUS_CONF_METHOD_SHOW_STATISTICS_INFOMATION_OF_ALL_WTP_WHOLE[PATH_LEN];

/*luzhenhua append  2010-05-26 */
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_WLAN_DATA_PKTS_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WTP_ATH_STATISTICS_INFOMATION[PATH_LEN];		
extern char WID_DBUS_CONF_METHOD_SHOW_ALL_WLAN_SSID_CONFIG_INFORMATION[PATH_LEN]; 
extern char WID_DBUS_STA_METHOD_SHOW_TERMINAL_INFO_OF_ALL_WTP[PATH_LEN];

/*****************************************for mib optimize end**********************************************/

/*
extern char ASD_DBUS_SIG_STA_LEAVE	"signal_sta_leave"



extern char ASD_DBUS_SIG_STA_COME   "signal_sta_come"
extern char ASD_DBUS_SIG_WTP_DENY_STA   "signal_wtp_deny"
extern char ASD_DBUS_SIG_DE_WTP_DENY_STA   "signal_de_wtp_deny"


extern char ASD_DBUS_SIG_STA_VERIFY	"signal_sta_verify"
extern char ASD_DBUS_SIG_STA_VERIFY_FAILED   "signal_sta_verify_failed"


extern char ASD_DBUS_SIG_STA_ASSOC_FAILED   "signal_sta_assoc_failed"
extern char ASD_DBUS_SIG_STA_JIANQUAN_FAILED   "signal_sta_jianquan_failed"
*/

extern char WID_DBUS_TRAP_WID_WTP_WIRELESS_INTERFACE_DOWN[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_WIRELESS_INTERFACE_DOWN_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CONFIG_CHANGE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_MODEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_MODEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_MODEL_LIST[PATH_LEN];


extern char WID_DBUS_TRAP_WID_WTP_AC_DISCOVERY_COVER_HOLE_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_DEVICE_INTERFERENCE_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_AP_INTERFERENCE_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_TERMINAL_INTERFERENCE_CLEAR[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_CHANNEL_COUNT_MINOR_CLEAR[PATH_LEN];

extern char WID_DBUS_TRAP_WID_WTP_FIND_UNSAFE_ESSID[PATH_LEN];
extern char WID_DBUS_TRAP_WID_WTP_FIND_WIDS_ATTACK[PATH_LEN];		
extern char WID_DBUS_TRAP_WID_SSID_KEY_CONFLICT[PATH_LEN];		

extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_STATISTICS_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_STATISTICS_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_WIDS_STATISTICS_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_WIDS_STATISTICS_LIST[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_DEVICE_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_DEVICE_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_WIDS_DEVICE_OF_ALL[PATH_LEN];   //fengwenchao add 20101227
extern char WID_DBUS_CONF_METHOD_CLEAR_WIDS_DEVICE_LIST_BYWTPID[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_WIDS_DEVICE_LIST[PATH_LEN];
extern char WID_BAK_OBJPATH[PATH_LEN];
extern char WID_BAK_INTERFACE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_MASTER_BAK_SET[PATH_LEN];
extern char WID_DBUS_AC_METHOD_UPDATE_BAK_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_SYNCHRONIZE_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_ASD_SYNCHRONIZE_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_NOTICE_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_VRRP_INFO[PATH_LEN];
extern char WID_DBUS_AC_METHOD_VRRP_SOCK_INFO[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_FORMARD_MODE[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_TUNNEL_MODE[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SET_NEIGHBORDEAD_INTERVAL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_NEIGHBORDEAD_INTERVAL[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WTPLIST_BYWLANID[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_UPDATE_PATH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_UPDATE_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_UPDATE_CONFIG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TRAP_DEBUG_OPEN[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TRAP_SWITCH_ABLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TRAP_SWITCH_SHOW[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_UPDATE_WTP_IMG[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_CLEAR_UPDATE_WTP_IMG[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_UPDATE_WTP_IMG_LIST[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_CLEAR_UPDATE_WTP_IMG_LIST[PATH_LEN];
/*mahz add for ap upgrade automatically*/
extern char WID_DBUS_WTP_METHOD_BIND_MODEL_WITH_FILE[PATH_LEN];	
extern char WID_DBUS_WTP_METHOD_SET_AP_UPDATE_BASE_MODEL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_MODEL_BIND_INFO[PATH_LEN];	
extern char WID_DBUS_WTP_METHOD_DELETE_MODEL_BIND_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CLEAR_ONE_MODEL_UPDATE_CONFIG[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_DETAIL_MODEL_BIND_INFO[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_AP_UPDATE_COUNT_ONETIME[PATH_LEN];	
extern char WID_DBUS_WTP_METHOD_SET_AP_UPDATE_CONTROL[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SHOW_AP_UPGRADE_RESULT_INFO[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_UPDATE_WTPCOMPATIBLE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_AP_UPDATE_FAIL_COUNT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_AP_UPDATE_FAIL_COUNT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WTPLIST_UPDATE_FAIL_LIST[PATH_LEN];
extern char	WID_DBUS_WTP_METHOD_CLEAR_UPDATE_FAIL_WTP_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_OLD_AP_IMG[PATH_LEN];

/*zhanglei add for bak ac ip list group*/
extern char	WID_DBUS_ACIPLIST_OBJPATH[PATH_LEN];
extern char WID_DBUS_ACIPLIST_INTERFACE[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_CONFIG[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_ADD_AC_IP_LIST_GROUP[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_DEL_AC_IP_LIST_GROUP[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_CONFIG_AC_IP_LIST[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_ADD_AC_IP[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_DEL_AC_IP[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_SET_AC_IP_PRIORITY[PATH_LEN];
extern char	WID_DBUS_ACIPLIST_METHOD_AC_IP_LIST_GROUP_SWITCH[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SHOW_AC_IP_LIST[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SHOW_AC_IP_LIST_ONE[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SHOW_RUNNING_CONFIG[PATH_LEN];

extern char WID_DBUS_RADIO_METHOD_WLAN_SET_STA_IP_MAC_BINDING[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_APPAY_WLAN_IFNAME_IPV6[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_APPAY_WTP_IFNAME_IPV6[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_SET_STA_VLANID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_WLAN_SET_STA_DHCP_BEFORE_AUTHERIZED[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_HOTREBOOT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_ACCESS_THROUGH_NAT[PATH_LEN];

extern char WID_DBUS_WTP_METHOD_SET_WTP_WIDS_POLICY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ADD_WID_MAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_WID_MAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_MAC_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_COUNTERMEASURES[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_AP_COUNTERMEASURES_MODE[PATH_LEN];

extern char  WID_DBUS_RADIO_METHOD_SET_ACKTIMEOUT_DISTANCE[PATH_LEN];/*wcl add for RDIR-33*/
extern char  WID_DBUS_RADIO_METHOD_SET_GUARD_INTERVAL[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SET_MCS[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SET_CMMODE[PATH_LEN];

extern char WID_DBUS_EBR_METHOD_SET_EBR_ADD_DEL_UPLINK[PATH_LEN];
extern char WID_DBUS_EBR_METHOD_SHOW_FDB_SUMMARY_DETAIL[PATH_LEN];

extern char  WID_DBUS_RADIO_METHOD_SET_WDS_DISTANCE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WDS_REMOTE_BRMAC[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WDS_WEP_KEY[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_WDS_AES_KEY[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SET_WDS_ENCRYPTION_TYPE[PATH_LEN];
extern char  WID_DBUS_RADIO_SECTOR_SET_CMD[PATH_LEN];
extern char  WID_DBUS_RADIO_TX_CHAINMASK_SET_CMD[PATH_LEN];
extern char  WID_DBUS_RADIO_TX_CHAINMASK_SET_CMD_V2	[PATH_LEN];

extern char  WID_DBUS_RADIO_SECTOR_POWER_SET_CMD[PATH_LEN];
extern char  WID_DBUS_RADIO_NETGEAR_G_SET_CMD[PATH_LEN];

extern char  WID_DBUS_WTP_LIST_METHOD_SET_DHCP_SNOOPING[PATH_LEN];
extern char  WID_DBUS_WTP_METHOD_SET_DHCP_SNOOPING[PATH_LEN];
extern char  WID_DBUS_WTP_LIST_METHOD_STA_INFO_REPORT[PATH_LEN];
extern char  WID_DBUS_WTP_METHOD_STA_INFO_REPORT[PATH_LEN];
extern char  WID_DBUS_WLAN_METHOD_STA_IP_MAC_BINDING[PATH_LEN];
extern char  WID_DBUS_WLAN_WTP_LIST_METHOD_STA_STATIC_ARP[PATH_LEN];
extern char  WID_DBUS_WLAN_WTP_METHOD_STA_STATIC_ARP[PATH_LEN];

extern char WID_DBUS_WLAN_METHOD_SERVICE_CONTROL_TIMER[PATH_LEN];
extern char  WID_DBUS_WLAN_METHOD_TIMER_ABLE[PATH_LEN];
extern char  WID_DBUS_CONF_METHOD_SHOW_AP_TRAP_ROGUE_AP_TERMINAL_CPU_MEM_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WTP_ROGUEAP_ROGUETERMINAL_CPU_MEM_TRAP_THRESHOLD[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WTP_TRAP_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WTP_SEQNUM_SWITCH[PATH_LEN]; /*wcl add*/
extern char WID_DBUS_CONF_METHD_SET_WID_ROGUE_DANGER_UNSAFE_ATTACK_TRAP_STATE[PATH_LEN];   /*fengwenchao add 20110221*/
extern char WID_DBUS_CONF_METHOD_MODIFY_ESSID[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_AMPDU_ABLE[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_AMPDU_LIMIT[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_AMPDU_SUBFRAME[PATH_LEN]; // zhangshu add for subframe , 2010-10-09

extern char WID_DBUS_RADIO_METHOD_SET_MIXED_PURE_N[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_WAPI_INFO_SWITCH[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_STA_WAPI_INFO_REPORTINTERVAL[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_CHANNEL_OFFSET[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_TXPOWER_STEP[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RADIO_WLAN_LIMIT_RSSI_ACCESS_STA[PATH_LEN]; //fengwenchao add 20120222 for RDIR-25
extern char WID_DBUS_ACIPLIST_METHOD_SET_AC_IP_BANLANCE_FLAG[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_MAC_WHITELIST_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_ESSID_WHITELIST_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CHANGE_WHITELIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_CHANGE_BLACKLIST [PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_TPC_POLICY[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SET_AC_IP_THRESHOLD[PATH_LEN];
extern char WID_DBUS_ACIPLIST_METHOD_SET_AC_IP_DIFF_BANLANCE[PATH_LEN];


extern char  WID_DBUS_RADIO_METHOD_TIMER_ABLE[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SERVICE_CONTROL_TIMER[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_WIDS_MONITOR_MODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_MODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_CHANNEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_MODE_CHANNEL_SHOW[PATH_LEN];
extern char WID_DBUS_AC_METHOD_SET_INTERFACE_VMAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_AP_IP_MODE[PATH_LEN];
extern char WID_DBUS_WTP_METHOD_SET_WTP_INTERFACE_ETH_MTU[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ACCESS_WTP_VENDOR_COUNT_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_JUDGE_POLICY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_JUDGE_POLICY_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_TUNNEL_MODE_POLICY[PATH_LEN];
extern char  WID_DBUS_RADIO_METHOD_SET_AMPDU_SUBFREAM[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_MIMO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_LICENSE_BINDING[PATH_LEN];		/*xiaodawei append, 20101029*/
extern char WID_DBUS_IPERF_WTPIP[PATH_LEN];							//xiaodawei add, 20110303
extern char WID_DBUS_CONF_METHOD_SET_WTP_LINK_DETECT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WSM_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_VLAN_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_DHCP_OPTION82_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_NEIGHBOR_SAME_CHANNELRSSI_THRESHOLD[PATH_LEN];/*zhaoruijia,tranlate  neighbor_channel_interference to 1.3*/

extern char WID_DBUS_AP_GROUP_OBJPATH[PATH_LEN];
extern char WID_DBUS_AP_GROUP_INTERFACE[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_CONFIG[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_CREATE[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_DEL[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_ADD_DEL_MEMBER[PATH_LEN];
extern char WID_DBUS_AP_GROUP_METHOD_SHOW_MEMBER[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SERVICE_TFTP_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_SERVICE_TFTP_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SERVICE_FTP_SWITCH[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_SERVICE_FTP_SWITCH[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_SHOW_WLAN_RADIO_INFORMATION[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WID_ERROR_HANDLE_STATE[PATH_LEN];


extern char WID_DBUS_WTP_METHOD_SHOW_WTP_RADIO_PKT_INFO_TUNNEL[PATH_LEN];
extern char WID_DBUS_WLAN_METHOD_SHOW_WLAN_PTK_INFO[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RADIO_RX_DATA_DEAD_TIME[PATH_LEN];
extern char WID_DBUS_RADIO_METHOD_SET_RADIO_RX_DATA_DEAD_TIME_SHOW[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_FLOW_PARAMETER_V2[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_FLOW_ABLE[PATH_LEN];
extern char WID_DBUS_QOS_METHOD_SET_QOS_FLOW_ABLE_V2[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_WTP_COLLECT_TIME[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_DBUS_COUNT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SET_DBUS_COUNT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_ADD_BLACK_WHITE_OUI_MAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_DEL_BLACK_WHITE_OUI_MAC[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_BLACK_WHITE_OUI_INFO[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_UPDATE_BLACK_WHITE_OUI_INFO_LIST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_USE_BLACK_WHITE_NONE_OUI_POLICY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_OUI_POLICY[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_SHOW_CONFLICT_WTP_LIST[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_CHECKING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_QUIT[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_LOCAL_HASNI_STATE_CHANGE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_MONITOR_MODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_MODE[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_CHANNEL[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WIDS_SCANNING_MODE_CHANNEL_SHOW[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MULTICAST_LISTEN_SETTING[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_NO_RESPONSE_TO_STA_PROBLE_REQUEST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_UNI_MUTI_BR_CAST_ISOLATION_SW_AND_RATE_SET[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_MUTI_BR_CAST_RATE_SET[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WLAN_NO_RESPONSE_TO_STA_PROBLE_REQUEST[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WLAN_UNI_MUTI_BR_CAST_ISOLATION_SW_AND_RATE_SET[PATH_LEN];
extern char WID_DBUS_CONF_METHOD_WLAN_MUTI_BR_CAST_RATE_SET[PATH_LEN];

extern char WID_DBUS_CONF_METHOD_BAK_CHECK_INTERVAL[PATH_LEN];			/* Huang Leilei 2012-10-24 add */
extern char WID_DBUS_CONF_METHOD_BAK_CHECK_INTERVAL_SHOW[PATH_LEN];		/* Huang Leilei 2012-10-24 add */
extern char WID_DBUS_CONF_METHOD_LIC_BAK_REQ_INTERVAL[PATH_LEN];		/* Huang Leilei 2012-10-25 add */
extern char WID_DBUS_CONF_METHOD_LIC_BAK_REQ_INTERVAL_SHOW[PATH_LEN];	/* Huang Leilei 2012-10-25 add */
extern char WID_DBUS_WLAN_METHOD_TUNNEL_NODE_SETTING[PATH_LEN];
#endif
