
PUB_DIR= ../../../lib/asn1/pub
HNBAP_DIR= ../../../lib/asn1/hnbap
RUA_DIR= ../../../lib/asn1/rua
RANAP_DIR= ../../../lib/asn1/ranap

PUB_OBJS =\
$(PUB_DIR)/ANY.o\
$(PUB_DIR)/BOOLEAN.o\
$(PUB_DIR)/ENUMERATED.o\
$(PUB_DIR)/INTEGER.o\
$(PUB_DIR)/NativeEnumerated.o\
$(PUB_DIR)/NativeInteger.o\
$(PUB_DIR)/OBJECT_IDENTIFIER.o\
$(PUB_DIR)/asn_SEQUENCE_OF.o\
$(PUB_DIR)/asn_SET_OF.o\
$(PUB_DIR)/constr_CHOICE.o\
$(PUB_DIR)/constr_SEQUENCE.o\
$(PUB_DIR)/constr_SEQUENCE_OF.o\
$(PUB_DIR)/constr_SET_OF.o\
$(PUB_DIR)/OCTET_STRING.o\
$(PUB_DIR)/BIT_STRING.o\
$(PUB_DIR)/asn_codecs_prim.o\
$(PUB_DIR)/ber_tlv_length.o\
$(PUB_DIR)/ber_tlv_tag.o\
$(PUB_DIR)/ber_decoder.o\
$(PUB_DIR)/der_encoder.o\
$(PUB_DIR)/constr_TYPE.o\
$(PUB_DIR)/constraints.o\
$(PUB_DIR)/xer_support.o\
$(PUB_DIR)/xer_decoder.o\
$(PUB_DIR)/xer_encoder.o\
$(PUB_DIR)/per_support.o\
$(PUB_DIR)/per_decoder.o\
$(PUB_DIR)/per_encoder.o\
$(PUB_DIR)/per_opentype.o\


HNBAP_OBJS=\
$(HNBAP_DIR)/Access-stratum-release-indicator.o \
$(HNBAP_DIR)/AltitudeAndDirection.o \
$(HNBAP_DIR)/BackoffTimer.o \
$(HNBAP_DIR)/CGI.o \
$(HNBAP_DIR)/CI.o \
$(HNBAP_DIR)/CSG-ID.o \
$(HNBAP_DIR)/CSG-Indicator.o \
$(HNBAP_DIR)/CSGMembershipUpdate.o \
$(HNBAP_DIR)/HNBAP-Cause.o \
$(HNBAP_DIR)/HNBAP-CauseRadioNetwork.o \
$(HNBAP_DIR)/CellIdentity.o \
$(HNBAP_DIR)/CriticalityDiagnostics-IE-List.o \
$(HNBAP_DIR)/CriticalityDiagnostics.o \
$(HNBAP_DIR)/ESN.o \
$(HNBAP_DIR)/ErrorIndication.o \
$(HNBAP_DIR)/GeographicalCoordinates.o \
$(HNBAP_DIR)/GeographicalLocation.o \
$(HNBAP_DIR)/HNB-Cell-Access-Mode.o \
$(HNBAP_DIR)/HNB-Identity-Info.o \
$(HNBAP_DIR)/HNB-Identity.o \
$(HNBAP_DIR)/HNB-Location-Information.o \
$(HNBAP_DIR)/HNBAP-PDU.o \
$(HNBAP_DIR)/HNBDe-Register.o \
$(HNBAP_DIR)/HNBRegisterAccept.o \
$(HNBAP_DIR)/HNBRegisterReject.o \
$(HNBAP_DIR)/HNBRegisterRequest.o \
$(HNBAP_DIR)/IMEI.o \
$(HNBAP_DIR)/IMSI.o \
$(HNBAP_DIR)/IMSIDS41.o \
$(HNBAP_DIR)/IMSIESN.o \
$(HNBAP_DIR)/IP-Address.o \
$(HNBAP_DIR)/Ipv4Address.o \
$(HNBAP_DIR)/Ipv6Address.o \
$(HNBAP_DIR)/LAC.o \
$(HNBAP_DIR)/LAI.o \
$(HNBAP_DIR)/MacroCellID.o \
$(HNBAP_DIR)/MacroCoverageInformation.o \
$(HNBAP_DIR)/MuxPortNumber.o \
$(HNBAP_DIR)/PLMNidentity.o \
$(HNBAP_DIR)/PTMSI.o \
$(HNBAP_DIR)/PTMSIRAI.o \
$(HNBAP_DIR)/PrivateIE-Container.o \
$(HNBAP_DIR)/PrivateMessage.o \
$(HNBAP_DIR)/ProtocolExtensionContainer.o \
$(HNBAP_DIR)/HNBAP-ProtocolIE-Container.o \
$(HNBAP_DIR)/RAC.o \
$(HNBAP_DIR)/RAI.o \
$(HNBAP_DIR)/RNC-ID.o \
$(HNBAP_DIR)/Registration-Cause.o \
$(HNBAP_DIR)/SAC.o \
$(HNBAP_DIR)/TMSIDS41.o \
$(HNBAP_DIR)/TMSILAI.o \
$(HNBAP_DIR)/UE-Capabilities.o \
$(HNBAP_DIR)/UE-Identity.o \
$(HNBAP_DIR)/UEDe-Register.o \
$(HNBAP_DIR)/UERegisterAccept.o \
$(HNBAP_DIR)/UERegisterReject.o \
$(HNBAP_DIR)/UERegisterRequest.o \
$(HNBAP_DIR)/UTRANCellID.o \


RUA_OBJS=\
$(RUA_DIR)/Ansi-41-IDNNS.o \
$(RUA_DIR)/RUA-CN-DomainIndicator.o \
$(RUA_DIR)/CSGMembershipStatus.o \
$(RUA_DIR)/Cause.o \
$(RUA_DIR)/CauseMisc.o \
$(RUA_DIR)/CauseProtocol.o \
$(RUA_DIR)/CauseRadioNetwork.o \
$(RUA_DIR)/CauseTransport.o \
$(RUA_DIR)/Connect.o \
$(RUA_DIR)/ConnectionlessTransfer.o \
$(RUA_DIR)/Context-ID.o \
$(RUA_DIR)/Criticality.o \
$(RUA_DIR)/CriticalityDiagnostics-IE-List.o \
$(RUA_DIR)/CriticalityDiagnostics.o \
$(RUA_DIR)/DirectTransfer.o \
$(RUA_DIR)/Disconnect.o \
$(RUA_DIR)/ErrorIndication.o \
$(RUA_DIR)/Establishment-Cause.o \
$(RUA_DIR)/Gsm-map-IDNNS.o \
$(RUA_DIR)/InitiatingMessage.o \
$(RUA_DIR)/IntraDomainNasNodeSelector.o \
$(RUA_DIR)/Presence.o \
$(RUA_DIR)/PrivateIE-Container.o \
$(RUA_DIR)/PrivateIE-Field.o \
$(RUA_DIR)/PrivateIE-ID.o \
$(RUA_DIR)/PrivateMessage.o \
$(RUA_DIR)/ProcedureCode.o \
$(RUA_DIR)/ProtocolExtensionContainer.o \
$(RUA_DIR)/ProtocolExtensionField.o \
$(RUA_DIR)/ProtocolIE-Container.o \
$(RUA_DIR)/ProtocolIE-ContainerList.o \
$(RUA_DIR)/ProtocolIE-Field.o \
$(RUA_DIR)/ProtocolIE-ID.o \
$(RUA_DIR)/ProtocolIE-Single-Container.o \
$(RUA_DIR)/RANAP-Message.o \
$(RUA_DIR)/RUA-PDU.o \
$(RUA_DIR)/RoutingParameter.o \
$(RUA_DIR)/SuccessfulOutcome.o \
$(RUA_DIR)/TriggeringMessage.o \
$(RUA_DIR)/TypeOfError.o \
$(RUA_DIR)/UnsuccessfulOutcome.o

RANAP_OBJS=\
$(RANAP_DIR)/RANAP-ProtocolIE-Container.o \
$(RANAP_DIR)/RAB-ReleaseRequest.o \
$(RANAP_DIR)/RAB-AssignmentRequest.o \
$(RANAP_DIR)/RAB-ID.o \
$(RANAP_DIR)/RANAP-PDU.o \
$(RANAP_DIR)/Paging.o \
$(RANAP_DIR)/PagingAreaID.o \
$(RANAP_DIR)/PagingCause.o \
$(RANAP_DIR)/RANAP-CN-DomainIndicator.o \
$(RANAP_DIR)/PermanentNAS-UE-ID.o \
$(RANAP_DIR)/TemporaryUE-ID.o \
$(RANAP_DIR)/NonSearchingIndication.o \
$(RANAP_DIR)/GlobalCN-ID.o \
$(RANAP_DIR)/DRX-CycleLengthCoefficient.o \
$(RANAP_DIR)/RAB-AssignmentRequest.o \
$(RANAP_DIR)/RAB-Parameters.o \
$(RANAP_DIR)/NAS-SynchronisationIndicator.o \
$(RANAP_DIR)/UserPlaneMode.o \
$(RANAP_DIR)/TransportLayerInformation.o \
$(RANAP_DIR)/RAB-SetupOrModifyList.o \
$(RANAP_DIR)/RAB-SetupOrModifiedList.o \
$(RANAP_DIR)/RAB-SetupOrModifiedItem.o \
$(RANAP_DIR)/RAB-SetupOrModifyItemFirst.o \
$(RANAP_DIR)/RAB-SetupOrModifyItemSecond.o \
$(RANAP_DIR)/RAB-ReleaseRequest.o \
$(RANAP_DIR)/RAB-ReleaseList.o \
$(RANAP_DIR)/RAB-ReleaseItem.o \
$(RANAP_DIR)/RANAP-Cause.o \
$(RANAP_DIR)/RANAP-CauseMisc.o \
$(RANAP_DIR)/RANAP-CauseProtocol.o \
$(RANAP_DIR)/ResetResource.o \
$(RANAP_DIR)/IuSignallingConnectionIdentifier.o \
$(RANAP_DIR)/ResetResourceList.o \
$(RANAP_DIR)/ResetResourceItem.o \
$(RANAP_DIR)/RelocationRequest.o \
$(RANAP_DIR)/InitialUE-Message.o \
$(RANAP_DIR)/SourceRNC-ToTargetRNC-TransparentContainer.o \
$(RANAP_DIR)/Reset.o 


CC = mips-linux-gnu-gcc

LDFLAGS = -lpthread -ldl

CFLAGS = -Wall -g -O0 -D_DISTRIBUTION_ -I. 
CFLAGS += -I/opt/mipslibs/usr/include
CFLAGS += -I../../../../accapi
CFLAGS += -I/opt/mipslibs/usr/include/libxml2
CFLAGS += -I../../../lib/asn1/pub
CFLAGS += -I../../../lib/asn1/hnbap
CFLAGS += -I../../../lib/asn1/rua
CFLAGS += -I../../../lib/asn1/ranap


LIBS = -L/opt/mipslibs/usr/lib -L./  -lm -L/opt/mipslibs/usr/lib -lxml2 -lz  -L/opt/mipslibs/usr/lib -lsctp  -L../../../lib/asn1/ranap -lranap

DBUS_INCLUDE=-I/opt/mipslibs/usr/include/dbus-1.0 -I/opt/mipslibs/usr/lib/dbus-1.0/include
DBUS_LIBS=-ldbus-1


RM = /bin/rm -f 

ASN_PATH = ../../../lib/asn1


# list of generated object files for AC. 

IUH_OBJS = Iuh.o Iuh_DBus.o Iuh_DBus_handler.o Iuh_IuRecv.o Iuh_log.o Iuh_ManageHNB.o Iuh_Msgq.o Iuh_SockOP.o Iuh_Thread.o Iuh_Timerlib.o Iuh_DBusPath.o Iuh_Stevens.o\
            Iuh_IFListen.o Iuh_License.o iplist.o Iuh_Encode.o Iuh_Decode.o
 
IUH_SRCS = $(IUH_OBJS:.o=.c) 

IUH_DEPS := $(IUH_OBJS:.o=.d)

# program executables. 
IUH_APP = iuh

.PHONY: deps clean clean_libs libs

# top-level rule, to compile everything. 
all: $(IUH_APP) 



$(IUH_APP): $(IUH_OBJS) PUB HNBAP RUA RANAP
#	$(CC) $(CFLAGS) $(LDFLAG) -o $(IUH_APP) ${IUH_OBJS} ${HNBAP_OBJS} ${RUA_OBJS} $(PUB_OBJS)
	$(CC)  $(IUH_OBJS) $(PUB_OBJS) $(HNBAP_OBJS) $(RUA_OBJS) $(RANAP_OJBS) $(LDFLAGS) $(LDLIBS)  $(DBUS_LIBS) $(LIBS) -o $(IUH_APP) 
	
PUB:
	${MAKE} -C ${PUB_DIR}
HNBAP:
	${MAKE} -C ${HNBAP_DIR}
RUA:
	${MAKE} -C ${RUA_DIR}
RANAP:
	${MAKE} -C ${RANAP_DIR}

%.o: %.c
	$(CC) -c $(CFLAGS) $(DBUS_INCLUDE) $(INCLUDES) -o $*.o $<


clean:  cleanhnbap cleanrua cleanranap cleanpub
	$(RM) $(IUH_APP) $(IUH_OBJS) $(IUH_DEPS) 

clean_deps:
	$(IUH_DEPS) 
	
deps: $(IUH_SRC) 
	$(CC) -MD -E $(IUH_SRCS) $(CFLAGS) >/dev/null

-include $(IUH_DEPS)

cleanhnbap:
	${MAKE} -C ${HNBAP_DIR} clean
  
cleanrua:
	${MAKE} -C ${RUA_DIR} clean

cleanranap:
	${MAKE} -C ${RANAP_DIR} clean

cleanpub:
	${MAKE} -C ${PUB_DIR} clean




#BIT_STRING.o OCTET_STRING.o INTEGER.o LAC.o RAC.o SAC.o CSG-ID.o Cause.o PLMNidentity.o CellIdentity.o \
#Context-ID.o UE-Identity.o UE-Capabilities.o Registration-Cause.o HNB-Identity.o HNBDe-Register.o \
#HNBRegisterRequest.o ProtocolIE-Container.o HNB-Location-Information.o UEDe-Register.o UERegisterRequest.o \
#RNC-ID.o Cause.o BackoffTimer.o HNBRegisterAccept.o HNBRegisterReject.o UERegisterAccept.o UERegisterReject.o \
#HNBAP-PDU.o per_encoder.o per_decoder.o asn_SEQUENCE_OF.o \