/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef DOT11DHCPIPV6USEAGETABLE_INTERFACE_H
#define DOT11DHCPIPV6USEAGETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "dot11DHCPIpv6UseageTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _dot11DHCPIpv6UseageTable_initialize_interface(dot11DHCPIpv6UseageTable_registration * user_ctx,
                                    u_long flags);
void _dot11DHCPIpv6UseageTable_shutdown_interface(dot11DHCPIpv6UseageTable_registration * user_ctx);

dot11DHCPIpv6UseageTable_registration *
dot11DHCPIpv6UseageTable_registration_get( void );

dot11DHCPIpv6UseageTable_registration *
dot11DHCPIpv6UseageTable_registration_set( dot11DHCPIpv6UseageTable_registration * newreg );

netsnmp_container *dot11DHCPIpv6UseageTable_container_get( void );
int dot11DHCPIpv6UseageTable_container_size( void );

    dot11DHCPIpv6UseageTable_rowreq_ctx * dot11DHCPIpv6UseageTable_allocate_rowreq_ctx(void *);
void dot11DHCPIpv6UseageTable_release_rowreq_ctx(dot11DHCPIpv6UseageTable_rowreq_ctx *rowreq_ctx);

int dot11DHCPIpv6UseageTable_index_to_oid(netsnmp_index *oid_idx,
                            dot11DHCPIpv6UseageTable_mib_index *mib_idx);
int dot11DHCPIpv6UseageTable_index_from_oid(netsnmp_index *oid_idx,
                              dot11DHCPIpv6UseageTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void dot11DHCPIpv6UseageTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* DOT11DHCPIPV6USEAGETABLE_INTERFACE_H */
/** @} */
