/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "RANAP-IEs.asn"
 */

#ifndef	_Alt_RAB_Parameter_SupportedGuaranteedBitrates_H_
#define	_Alt_RAB_Parameter_SupportedGuaranteedBitrates_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SupportedRAB_ParameterBitrateList;

/* Alt-RAB-Parameter-SupportedGuaranteedBitrates */
typedef struct Alt_RAB_Parameter_SupportedGuaranteedBitrates {
	A_SEQUENCE_OF(struct SupportedRAB_ParameterBitrateList) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Alt_RAB_Parameter_SupportedGuaranteedBitrates_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Alt_RAB_Parameter_SupportedGuaranteedBitrates;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SupportedRAB-ParameterBitrateList.h"

#endif	/* _Alt_RAB_Parameter_SupportedGuaranteedBitrates_H_ */
#include <asn_internal.h>
