/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "RANAP-IEs.asn"
 */

#ifndef	_ExtendedGuaranteedBitrate_H_
#define	_ExtendedGuaranteedBitrate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedGuaranteedBitrate */
typedef long	 ExtendedGuaranteedBitrate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedGuaranteedBitrate;
asn_struct_free_f ExtendedGuaranteedBitrate_free;
asn_struct_print_f ExtendedGuaranteedBitrate_print;
asn_constr_check_f ExtendedGuaranteedBitrate_constraint;
ber_type_decoder_f ExtendedGuaranteedBitrate_decode_ber;
der_type_encoder_f ExtendedGuaranteedBitrate_encode_der;
xer_type_decoder_f ExtendedGuaranteedBitrate_decode_xer;
xer_type_encoder_f ExtendedGuaranteedBitrate_encode_xer;
per_type_decoder_f ExtendedGuaranteedBitrate_decode_uper;
per_type_encoder_f ExtendedGuaranteedBitrate_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedGuaranteedBitrate_H_ */
#include <asn_internal.h>
