/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "RANAP-IEs.asn"
 */

#ifndef	_GeographicalArea_H_
#define	_GeographicalArea_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GA-Point.h"
#include "GA-PointWithUnCertainty.h"
#include "GA-Polygon.h"
#include "GA-PointWithUnCertaintyEllipse.h"
#include "GA-PointWithAltitude.h"
#include "GA-PointWithAltitudeAndUncertaintyEllipsoid.h"
#include "GA-EllipsoidArc.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GeographicalArea_PR {
	GeographicalArea_PR_NOTHING,	/* No components present */
	GeographicalArea_PR_point,
	GeographicalArea_PR_pointWithUnCertainty,
	GeographicalArea_PR_polygon,
	/* Extensions may appear below */
	GeographicalArea_PR_pointWithUncertaintyEllipse,
	GeographicalArea_PR_pointWithAltitude,
	GeographicalArea_PR_pointWithAltitudeAndUncertaintyEllipsoid,
	GeographicalArea_PR_ellipsoidArc
} GeographicalArea_PR;

/* GeographicalArea */
typedef struct GeographicalArea {
	GeographicalArea_PR present;
	union GeographicalArea_u {
		GA_Point_t	 point;
		GA_PointWithUnCertainty_t	 pointWithUnCertainty;
		GA_Polygon_t	 polygon;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		GA_PointWithUnCertaintyEllipse_t	 pointWithUncertaintyEllipse;
		GA_PointWithAltitude_t	 pointWithAltitude;
		GA_PointWithAltitudeAndUncertaintyEllipsoid_t	 pointWithAltitudeAndUncertaintyEllipsoid;
		GA_EllipsoidArc_t	 ellipsoidArc;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeographicalArea_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeographicalArea;

#ifdef __cplusplus
}
#endif

#endif	/* _GeographicalArea_H_ */
#include <asn_internal.h>
