/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "RANAP-IEs.asn"
 */

#ifndef	_IuSignallingConnectionIdentifier_H_
#define	_IuSignallingConnectionIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IuSignallingConnectionIdentifier */
typedef BIT_STRING_t	 IuSignallingConnectionIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IuSignallingConnectionIdentifier;
asn_struct_free_f IuSignallingConnectionIdentifier_free;
asn_struct_print_f IuSignallingConnectionIdentifier_print;
asn_constr_check_f IuSignallingConnectionIdentifier_constraint;
ber_type_decoder_f IuSignallingConnectionIdentifier_decode_ber;
der_type_encoder_f IuSignallingConnectionIdentifier_encode_der;
xer_type_decoder_f IuSignallingConnectionIdentifier_decode_xer;
xer_type_encoder_f IuSignallingConnectionIdentifier_encode_xer;
per_type_decoder_f IuSignallingConnectionIdentifier_decode_uper;
per_type_encoder_f IuSignallingConnectionIdentifier_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IuSignallingConnectionIdentifier_H_ */
#include <asn_internal.h>
