/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "RANAP-IEs.asn"
 */

#ifndef	_NewRAListofIdleModeUEs_H_
#define	_NewRAListofIdleModeUEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RAC.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NewRAListofIdleModeUEs */
typedef struct NewRAListofIdleModeUEs {
	A_SEQUENCE_OF(RAC_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NewRAListofIdleModeUEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NewRAListofIdleModeUEs;

#ifdef __cplusplus
}
#endif

#endif	/* _NewRAListofIdleModeUEs_H_ */
#include <asn_internal.h>
