/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "RANAP-IEs.asn"
 */

#ifndef	_PositionDataSpecificToGERANIuMode_H_
#define	_PositionDataSpecificToGERANIuMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PositionDataSpecificToGERANIuMode */
typedef OCTET_STRING_t	 PositionDataSpecificToGERANIuMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionDataSpecificToGERANIuMode;
asn_struct_free_f PositionDataSpecificToGERANIuMode_free;
asn_struct_print_f PositionDataSpecificToGERANIuMode_print;
asn_constr_check_f PositionDataSpecificToGERANIuMode_constraint;
ber_type_decoder_f PositionDataSpecificToGERANIuMode_decode_ber;
der_type_encoder_f PositionDataSpecificToGERANIuMode_encode_der;
xer_type_decoder_f PositionDataSpecificToGERANIuMode_decode_xer;
xer_type_encoder_f PositionDataSpecificToGERANIuMode_encode_xer;
per_type_decoder_f PositionDataSpecificToGERANIuMode_decode_uper;
per_type_encoder_f PositionDataSpecificToGERANIuMode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PositionDataSpecificToGERANIuMode_H_ */
#include <asn_internal.h>
