/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-PDU-Contents"
 * 	found in "RANAP-PDU-Contents.asn"
 */

#ifndef	_RAB_ContextItem_RANAP_RelocInf_H_
#define	_RAB_ContextItem_RANAP_RelocInf_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RAB-ID.h"
#include "DL-GTP-PDU-SequenceNumber.h"
#include "UL-GTP-PDU-SequenceNumber.h"
#include "DL-N-PDU-SequenceNumber.h"
#include "UL-N-PDU-SequenceNumber.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
/* auto changed by perl script */
/*struct ;*/

/* RAB-ContextItem-RANAP-RelocInf */
typedef struct RAB_ContextItem_RANAP_RelocInf {
	RAB_ID_t	 rAB_ID;
/* auto changed by perl script */
	DL_GTP_PDU_SequenceNumber_t	*dl_GTP_PDU_SequenceNumber;	/* OPTIONAL */
/* auto changed by perl script */
	UL_GTP_PDU_SequenceNumber_t	*ul_GTP_PDU_SequenceNumber;	/* OPTIONAL */
/* auto changed by perl script */
	DL_N_PDU_SequenceNumber_t	*dl_N_PDU_SequenceNumber;	/* OPTIONAL */
/* auto changed by perl script */
	UL_N_PDU_SequenceNumber_t	*ul_N_PDU_SequenceNumber;	/* OPTIONAL */
/* auto changed by perl script */
	struct 	 ProtocolExtensionContainer_209P0 *iE_Extensions ;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RAB_ContextItem_RANAP_RelocInf_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RAB_ContextItem_RANAP_RelocInf;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _RAB_ContextItem_RANAP_RelocInf_H_ */
#include <asn_internal.h>
