/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-PDU-Contents"
 * 	found in "RANAP-PDU-Contents.asn"
 */

#include "RAB-SetupItem-EnhancedRelocCompleteReq.h"

static asn_TYPE_member_t asn_MBR_RAB_SetupItem_EnhancedRelocCompleteReq_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RAB_SetupItem_EnhancedRelocCompleteReq, rAB_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAB_ID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rAB-ID"
		},
	{ ATF_POINTER, 4, offsetof(struct RAB_SetupItem_EnhancedRelocCompleteReq, transportLayerAddressReq1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransportLayerAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"transportLayerAddressReq1"
		},
	{ ATF_POINTER, 3, offsetof(struct RAB_SetupItem_EnhancedRelocCompleteReq, iuTransportAssociationReq1),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_IuTransportAssociation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"iuTransportAssociationReq1"
		},
	{ ATF_POINTER, 2, offsetof(struct RAB_SetupItem_EnhancedRelocCompleteReq, ass_RAB_Parameters),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ass_RAB_Parameters,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ass-RAB-Parameters"
		},
	{ ATF_POINTER, 1, offsetof(struct RAB_SetupItem_EnhancedRelocCompleteReq, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_209P0,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"iE-Extensions"
		},
};
static int asn_MAP_RAB_SetupItem_EnhancedRelocCompleteReq_oms_1[] = { 1, 2, 3, 4 };
static ber_tlv_tag_t asn_DEF_RAB_SetupItem_EnhancedRelocCompleteReq_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RAB_SetupItem_EnhancedRelocCompleteReq_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rAB-ID at 1851 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* transportLayerAddressReq1 at 1852 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* iuTransportAssociationReq1 at 1853 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ass-RAB-Parameters at 1854 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions at 1855 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RAB_SetupItem_EnhancedRelocCompleteReq_specs_1 = {
	sizeof(struct RAB_SetupItem_EnhancedRelocCompleteReq),
	offsetof(struct RAB_SetupItem_EnhancedRelocCompleteReq, _asn_ctx),
	asn_MAP_RAB_SetupItem_EnhancedRelocCompleteReq_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RAB_SetupItem_EnhancedRelocCompleteReq_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RAB_SetupItem_EnhancedRelocCompleteReq = {
	"RAB-SetupItem-EnhancedRelocCompleteReq",
	"RAB-SetupItem-EnhancedRelocCompleteReq",
	SEQUENCE_free_for_RANAP,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper_for_RANAP,
	SEQUENCE_encode_uper_for_RANAP,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RAB_SetupItem_EnhancedRelocCompleteReq_tags_1,
	sizeof(asn_DEF_RAB_SetupItem_EnhancedRelocCompleteReq_tags_1)
		/sizeof(asn_DEF_RAB_SetupItem_EnhancedRelocCompleteReq_tags_1[0]), /* 1 */
	asn_DEF_RAB_SetupItem_EnhancedRelocCompleteReq_tags_1,	/* Same as above */
	sizeof(asn_DEF_RAB_SetupItem_EnhancedRelocCompleteReq_tags_1)
		/sizeof(asn_DEF_RAB_SetupItem_EnhancedRelocCompleteReq_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RAB_SetupItem_EnhancedRelocCompleteReq_1,
	5,	/* Elements count */
	&asn_SPC_RAB_SetupItem_EnhancedRelocCompleteReq_specs_1	/* Additional specs */
};

