/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "RANAP-IEs.asn"
 */

#ifndef	_RelocationRequirement_H_
#define	_RelocationRequirement_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RelocationRequirement {
	RelocationRequirement_lossless	= 0,
	RelocationRequirement_none	= 1,
	/*
	 * Enumeration is extensible
	 */
	RelocationRequirement_realtime	= 2
} e_RelocationRequirement;

/* RelocationRequirement */
typedef ENUMERATED_t	 RelocationRequirement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelocationRequirement;
asn_struct_free_f RelocationRequirement_free;
asn_struct_print_f RelocationRequirement_print;
asn_constr_check_f RelocationRequirement_constraint;
ber_type_decoder_f RelocationRequirement_decode_ber;
der_type_encoder_f RelocationRequirement_encode_der;
xer_type_decoder_f RelocationRequirement_decode_xer;
xer_type_encoder_f RelocationRequirement_encode_xer;
per_type_decoder_f RelocationRequirement_decode_uper;
per_type_encoder_f RelocationRequirement_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RelocationRequirement_H_ */
#include <asn_internal.h>
