/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "RANAP-IEs"
 * 	found in "RANAP-IEs.asn"
 */

#ifndef	_RequestedLocationRelatedDataType_H_
#define	_RequestedLocationRelatedDataType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RequestedLocationRelatedDataType {
	RequestedLocationRelatedDataType_decipheringKeysUEBasedOTDOA	= 0,
	RequestedLocationRelatedDataType_decipheringKeysAssistedGPS	= 1,
	RequestedLocationRelatedDataType_dedicatedAssistanceDataUEBasedOTDOA	= 2,
	RequestedLocationRelatedDataType_dedicatedAssistanceDataAssistedGPS	= 3,
	/*
	 * Enumeration is extensible
	 */
	RequestedLocationRelatedDataType_decipheringKeysAssistedGANSS	= 4,
	RequestedLocationRelatedDataType_dedicatedAssistanceDataAssistedGANSS	= 5,
	RequestedLocationRelatedDataType_decipheringKeysAssistedGPSandGANSS	= 6,
	RequestedLocationRelatedDataType_dedicatedAssistanceDataAssistedGPSandGANSS	= 7
} e_RequestedLocationRelatedDataType;

/* RequestedLocationRelatedDataType */
typedef ENUMERATED_t	 RequestedLocationRelatedDataType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestedLocationRelatedDataType;
asn_struct_free_f RequestedLocationRelatedDataType_free;
asn_struct_print_f RequestedLocationRelatedDataType_print;
asn_constr_check_f RequestedLocationRelatedDataType_constraint;
ber_type_decoder_f RequestedLocationRelatedDataType_decode_ber;
der_type_encoder_f RequestedLocationRelatedDataType_encode_der;
xer_type_decoder_f RequestedLocationRelatedDataType_decode_xer;
xer_type_encoder_f RequestedLocationRelatedDataType_encode_xer;
per_type_decoder_f RequestedLocationRelatedDataType_decode_uper;
per_type_encoder_f RequestedLocationRelatedDataType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestedLocationRelatedDataType_H_ */
#include <asn_internal.h>
