#ifndef _WBMD_DBUS_DEF_H
#define _WBMD_DBUS_DEF_H
extern char MSGQ_PATH[PATH_LEN];
extern char WBMD_DBUS_BUSNAME[PATH_LEN];
extern char WBMD_DBUS_OBJPATH[PATH_LEN];
extern char WBMD_DBUS_INTERFACE[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_CREATE_WBRIDGE[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_SHOW_WBRIDGE_LIST[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_WBRIDGE[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_SET_WBRIDGE_SNMP[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_SHOW_WBRIDGE_BASIC_INFO[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_SHOW_WBRIDGE_RF_INFO[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_SHOW_WBRIDGE_MINT_INFO[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_SHOW_WBRIDGE_RUNNING_CONFIG[PATH_LEN];
extern char WBMD_DBUS_CONF_METHOD_DELETE_WBRIDGE[PATH_LEN];

enum wbmd_dbus_result_no_e {
	WBMD_DBUS_SUCCESS,
	WBMD_DBUS_ERROR, 
	WBMD_DBUS_ID_NO_EXIST,
	WBMD_DBUS_ID_EXIST,
	WBMD_DBUS_UNKNOWN_ID_FORMAT,
	WBMD_DBUS_NUM_OVER_MAX,
	WBMD_DBUS_OUT_OF_MEMORY,
	WBMD_DBUS_NOT_RUNNING
};

#endif
