#!/bin/bash
#echo "WE USE 1.3.6 CURRENTLY,which doesn't need config."
#exit 0
#[ -d mipsbuild ] || mkdir mipsbuild

#OCT_KERNEL_ROOT="`pwd`/src/kernel2.6.32.27cn"
#OCT_KERNEL_ROOT=${KERNEL_ROOT}
curdir=`pwd`
echo ${OCT_KERNET_ROOT}
cd ${BUILD_DIR}/${IPTABLES_MOD}/debsrc/iptables-1.4.20/
./configure --host=mips-linux-gnu --with-kernel=${OCT_KERNEL_ROOT} --prefix=/opt/  --with-xtlibdir=/opt/lib/iptables 
#--enable-static

cd $curdir
