#!/bin/bash
#echo "WE USE 1.3.6 CURRENTLY,which doesn't need config."
#exit 0
#[ -d mipsbuild ] || mkdir mipsbuild

OCT_KERNEL_ROOT="`pwd`/src/kernel2.6.32.27cn"
curdir=`pwd`

cd ./src/iptables/debsrc/iptables-1.4.6/
./configure --host=mips-linux-gnu --with-kernel=${OCT_KERNEL_ROOT} --with-xtlibdir=/opt/lib/iptables --enable-static

cd $curdir
