/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18.2.1 $ of : mfd-data-get.m2c,v $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot11RadioStatisticsTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dot11RadioStatisticsTable get routines.
 * TODO:240:M: Implement dot11RadioStatisticsTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11RadioStatisticsTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11RadioStatisticsTable is subid 4 of wtpRadio.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement dot11RadioStatisticsTable data context functions.
 */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatsEntry.wtpRadCurrID
 * wtpRadCurrID is subid 1 of dot11RadioStatsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.1.1.1
 * Description:
Current radio ID.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-wtpRadCurrID.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
wtpRadCurrID_radiostatistics_map(long *mib_wtpRadCurrID_val_ptr, long raw_wtpRadCurrID_val)
{
    netsnmp_assert(NULL != mib_wtpRadCurrID_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:wtpRadCurrID_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement wtpRadCurrID mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_wtpRadCurrID_val_ptr) = raw_wtpRadCurrID_val;

    return MFD_SUCCESS;
} /* wtpRadCurrID_map */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.bssid
 * bssid is subid 1 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.1
 * Description:
bssid.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-bssid.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
bssid_radiostatistics_map(long *mib_bssid_val_ptr, long raw_bssid_val)
{
    netsnmp_assert(NULL != mib_bssid_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:bssid_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement bssid mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_bssid_val_ptr) = raw_bssid_val;

    return MFD_SUCCESS;
} /* bssid_map */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dot11RadioStatisticsTable_indexes_set_tbl_idx(dot11RadioStatisticsTable_mib_index *tbl_idx, long wtpRadCurrID_val, long bssid_val)
{
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:dot11RadioStatisticsTable_indexes_set_tbl_idx","called\n"));

    /* wtpRadCurrID(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    tbl_idx->wtpRadCurrID = wtpRadCurrID_val;
    
    /* bssid(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    tbl_idx->bssid = bssid_val;
    

    return MFD_SUCCESS;
} /* dot11RadioStatisticsTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dot11RadioStatisticsTable_indexes_set(dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, long wtpRadCurrID_val, long bssid_val)
{
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:dot11RadioStatisticsTable_indexes_set","called\n"));

    if(MFD_SUCCESS != dot11RadioStatisticsTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , wtpRadCurrID_val
                                   , bssid_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != dot11RadioStatisticsTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* dot11RadioStatisticsTable_indexes_set */


/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.wirelessUpFlow
 * wirelessUpFlow is subid 2 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.2
 * Description:
Wireless up flow.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-wirelessUpFlow.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
wirelessUpFlow_map(unsigned long long *mib_wirelessUpFlow_val_ptr, unsigned long long raw_wirelessUpFlow_val)
{
    netsnmp_assert(NULL != mib_wirelessUpFlow_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:wirelessUpFlow_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement wirelessUpFlow mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_wirelessUpFlow_val_ptr) = raw_wirelessUpFlow_val;

    return MFD_SUCCESS;
} /* wirelessUpFlow_map */

/**
 * Extract the current value of the wirelessUpFlow data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param wirelessUpFlow_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
wirelessUpFlow_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * wirelessUpFlow_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != wirelessUpFlow_val_ptr );

/*
 * TODO:231:o: |-> copy wirelessUpFlow data.
 * get (* wirelessUpFlow_val_ptr ).low and (* wirelessUpFlow_val_ptr ).high from rowreq_ctx->data
 */
    //(* wirelessUpFlow_val_ptr ).high = rowreq_ctx->data.wirelessUpFlow.high;
    (* wirelessUpFlow_val_ptr ) = rowreq_ctx->data.wirelessUpFlow;


    return MFD_SUCCESS;
} /* wirelessUpFlow_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.wirelessDownFlow
 * wirelessDownFlow is subid 3 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.3
 * Description:
Wireless down flow.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-wirelessDownFlow.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
wirelessDownFlow_map(unsigned long long *mib_wirelessDownFlow_val_ptr, unsigned long long raw_wirelessDownFlow_val)
{
    netsnmp_assert(NULL != mib_wirelessDownFlow_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:wirelessDownFlow_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement wirelessDownFlow mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_wirelessDownFlow_val_ptr) = raw_wirelessDownFlow_val;

    return MFD_SUCCESS;
} /* wirelessDownFlow_map */

/**
 * Extract the current value of the wirelessDownFlow data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param wirelessDownFlow_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
wirelessDownFlow_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * wirelessDownFlow_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != wirelessDownFlow_val_ptr );

/*
 * TODO:231:o: |-> copy wirelessDownFlow data.
 * get (* wirelessDownFlow_val_ptr ).low and (* wirelessDownFlow_val_ptr ).high from rowreq_ctx->data
 */
    //(* wirelessDownFlow_val_ptr ).high = rowreq_ctx->data.wirelessDownFlow.high;
    (* wirelessDownFlow_val_ptr ) = rowreq_ctx->data.wirelessDownFlow;


    return MFD_SUCCESS;
} /* wirelessDownFlow_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelDownAllPkts
 * channelDownAllPkts is subid 4 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.4
 * Description:
All the packets of down channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelDownAllPkts.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelDownAllPkts_map(unsigned long long *mib_channelDownAllPkts_val_ptr, unsigned long long raw_channelDownAllPkts_val)
{
    netsnmp_assert(NULL != mib_channelDownAllPkts_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelDownAllPkts_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelDownAllPkts mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelDownAllPkts_val_ptr) = raw_channelDownAllPkts_val;

    return MFD_SUCCESS;
} /* channelDownAllPkts_map */

/**
 * Extract the current value of the channelDownAllPkts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelDownAllPkts_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelDownAllPkts_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllPkts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelDownAllPkts_val_ptr );

/*
 * TODO:231:o: |-> copy channelDownAllPkts data.
 * get (* channelDownAllPkts_val_ptr ).low and (* channelDownAllPkts_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelDownAllPkts_val_ptr ).high = rowreq_ctx->data.channelDownAllPkts.high;
    (* channelDownAllPkts_val_ptr ) = rowreq_ctx->data.channelDownAllPkts;


    return MFD_SUCCESS;
} /* channelDownAllPkts_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelDownAllDropPkts
 * channelDownAllDropPkts is subid 5 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.5
 * Description:
All the drop packets of down channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelDownAllDropPkts.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelDownAllDropPkts_map(unsigned long long *mib_channelDownAllDropPkts_val_ptr, unsigned long long raw_channelDownAllDropPkts_val)
{
    netsnmp_assert(NULL != mib_channelDownAllDropPkts_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelDownAllDropPkts_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelDownAllDropPkts mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelDownAllDropPkts_val_ptr) = raw_channelDownAllDropPkts_val;

    return MFD_SUCCESS;
} /* channelDownAllDropPkts_map */

/**
 * Extract the current value of the channelDownAllDropPkts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelDownAllDropPkts_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelDownAllDropPkts_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllDropPkts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelDownAllDropPkts_val_ptr );

/*
 * TODO:231:o: |-> copy channelDownAllDropPkts data.
 * get (* channelDownAllDropPkts_val_ptr ).low and (* channelDownAllDropPkts_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelDownAllDropPkts_val_ptr ).high = rowreq_ctx->data.channelDownAllDropPkts.high;
    (* channelDownAllDropPkts_val_ptr ) = rowreq_ctx->data.channelDownAllDropPkts;


    return MFD_SUCCESS;
} /* channelDownAllDropPkts_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelDownAllMacErrPkts
 * channelDownAllMacErrPkts is subid 6 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.6
 * Description:
All the mac error packets of down channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelDownAllMacErrPkts.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelDownAllMacErrPkts_map(unsigned long long *mib_channelDownAllMacErrPkts_val_ptr, unsigned long long raw_channelDownAllMacErrPkts_val)
{
    netsnmp_assert(NULL != mib_channelDownAllMacErrPkts_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelDownAllMacErrPkts_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelDownAllMacErrPkts mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelDownAllMacErrPkts_val_ptr) = raw_channelDownAllMacErrPkts_val;

    return MFD_SUCCESS;
} /* channelDownAllMacErrPkts_map */

/**
 * Extract the current value of the channelDownAllMacErrPkts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelDownAllMacErrPkts_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelDownAllMacErrPkts_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllMacErrPkts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelDownAllMacErrPkts_val_ptr );

/*
 * TODO:231:o: |-> copy channelDownAllMacErrPkts data.
 * get (* channelDownAllMacErrPkts_val_ptr ).low and (* channelDownAllMacErrPkts_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelDownAllMacErrPkts_val_ptr ).high = rowreq_ctx->data.channelDownAllMacErrPkts.high;
    (* channelDownAllMacErrPkts_val_ptr ) = rowreq_ctx->data.channelDownAllMacErrPkts;


    return MFD_SUCCESS;
} /* channelDownAllMacErrPkts_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelDownAllResPkts
 * channelDownAllResPkts is subid 7 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.7
 * Description:
All the resend packets of down channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelDownAllResPkts.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelDownAllResPkts_map(unsigned long long *mib_channelDownAllResPkts_val_ptr, unsigned long long raw_channelDownAllResPkts_val)
{
    netsnmp_assert(NULL != mib_channelDownAllResPkts_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelDownAllResPkts_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelDownAllResPkts mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelDownAllResPkts_val_ptr) = raw_channelDownAllResPkts_val;

    return MFD_SUCCESS;
} /* channelDownAllResPkts_map */

/**
 * Extract the current value of the channelDownAllResPkts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelDownAllResPkts_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelDownAllResPkts_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllResPkts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelDownAllResPkts_val_ptr );

/*
 * TODO:231:o: |-> copy channelDownAllResPkts data.
 * get (* channelDownAllResPkts_val_ptr ).low and (* channelDownAllResPkts_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelDownAllResPkts_val_ptr ).high = rowreq_ctx->data.channelDownAllResPkts.high;
    (* channelDownAllResPkts_val_ptr ) = rowreq_ctx->data.channelDownAllResPkts;


    return MFD_SUCCESS;
} /* channelDownAllResPkts_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelUpAllFrames
 * channelUpAllFrames is subid 8 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.8
 * Description:
All the frames of up channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelUpAllFrames.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelUpAllFrames_map(unsigned long long *mib_channelUpAllFrames_val_ptr, unsigned long long raw_channelUpAllFrames_val)
{
    netsnmp_assert(NULL != mib_channelUpAllFrames_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelUpAllFrames_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelUpAllFrames mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelUpAllFrames_val_ptr) = raw_channelUpAllFrames_val;

    return MFD_SUCCESS;
} /* channelUpAllFrames_map */

/**
 * Extract the current value of the channelUpAllFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelUpAllFrames_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelUpAllFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelUpAllFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelUpAllFrames_val_ptr );

/*
 * TODO:231:o: |-> copy channelUpAllFrames data.
 * get (* channelUpAllFrames_val_ptr ).low and (* channelUpAllFrames_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelUpAllFrames_val_ptr ).high = rowreq_ctx->data.channelUpAllFrames.high;
    (* channelUpAllFrames_val_ptr ) = rowreq_ctx->data.channelUpAllFrames;


    return MFD_SUCCESS;
} /* channelUpAllFrames_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelDownAllFrames
 * channelDownAllFrames is subid 9 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.9
 * Description:
All the frames of down channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelDownAllFrames.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelDownAllFrames_map(unsigned long long *mib_channelDownAllFrames_val_ptr, unsigned long long raw_channelDownAllFrames_val)
{
    netsnmp_assert(NULL != mib_channelDownAllFrames_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelDownAllFrames_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelDownAllFrames mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelDownAllFrames_val_ptr) = raw_channelDownAllFrames_val;

    return MFD_SUCCESS;
} /* channelDownAllFrames_map */

/**
 * Extract the current value of the channelDownAllFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelDownAllFrames_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelDownAllFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelDownAllFrames_val_ptr );

/*
 * TODO:231:o: |-> copy channelDownAllFrames data.
 * get (* channelDownAllFrames_val_ptr ).low and (* channelDownAllFrames_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelDownAllFrames_val_ptr ).high = rowreq_ctx->data.channelDownAllFrames.high;
    (* channelDownAllFrames_val_ptr ) = rowreq_ctx->data.channelDownAllFrames;


    return MFD_SUCCESS;
} /* channelDownAllFrames_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelDownAllErrFrames
 * channelDownAllErrFrames is subid 10 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.10
 * Description:
All the error frames of down channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelDownAllErrFrames.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelDownAllErrFrames_map(unsigned long long *mib_channelDownAllErrFrames_val_ptr, unsigned long long raw_channelDownAllErrFrames_val)
{
    netsnmp_assert(NULL != mib_channelDownAllErrFrames_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelDownAllErrFrames_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelDownAllErrFrames mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelDownAllErrFrames_val_ptr) = raw_channelDownAllErrFrames_val;

    return MFD_SUCCESS;
} /* channelDownAllErrFrames_map */

/**
 * Extract the current value of the channelDownAllErrFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelDownAllErrFrames_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelDownAllErrFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllErrFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelDownAllErrFrames_val_ptr );

/*
 * TODO:231:o: |-> copy channelDownAllErrFrames data.
 * get (* channelDownAllErrFrames_val_ptr ).low and (* channelDownAllErrFrames_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelDownAllErrFrames_val_ptr ).high = rowreq_ctx->data.channelDownAllErrFrames.high;
    (* channelDownAllErrFrames_val_ptr ) = rowreq_ctx->data.channelDownAllErrFrames;


    return MFD_SUCCESS;
} /* channelDownAllErrFrames_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelDownAllDropFrames
 * channelDownAllDropFrames is subid 11 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.11
 * Description:
All the drop frames of down channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelDownAllDropFrames.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelDownAllDropFrames_map(unsigned long long *mib_channelDownAllDropFrames_val_ptr, unsigned long long raw_channelDownAllDropFrames_val)
{
    netsnmp_assert(NULL != mib_channelDownAllDropFrames_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelDownAllDropFrames_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelDownAllDropFrames mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelDownAllDropFrames_val_ptr) = raw_channelDownAllDropFrames_val;

    return MFD_SUCCESS;
} /* channelDownAllDropFrames_map */

/**
 * Extract the current value of the channelDownAllDropFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelDownAllDropFrames_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelDownAllDropFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllDropFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelDownAllDropFrames_val_ptr );

/*
 * TODO:231:o: |-> copy channelDownAllDropFrames data.
 * get (* channelDownAllDropFrames_val_ptr ).low and (* channelDownAllDropFrames_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelDownAllDropFrames_val_ptr ).high = rowreq_ctx->data.channelDownAllDropFrames.high;
    (* channelDownAllDropFrames_val_ptr ) = rowreq_ctx->data.channelDownAllDropFrames;


    return MFD_SUCCESS;
} /* channelDownAllDropFrames_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelDownAllResFrames
 * channelDownAllResFrames is subid 12 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.12
 * Description:
All the resend frames of down channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelDownAllResFrames.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelDownAllResFrames_map(unsigned long long *mib_channelDownAllResFrames_val_ptr, unsigned long long raw_channelDownAllResFrames_val)
{
    netsnmp_assert(NULL != mib_channelDownAllResFrames_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelDownAllResFrames_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelDownAllResFrames mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelDownAllResFrames_val_ptr) = raw_channelDownAllResFrames_val;

    return MFD_SUCCESS;
} /* channelDownAllResFrames_map */

/**
 * Extract the current value of the channelDownAllResFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelDownAllResFrames_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelDownAllResFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllResFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelDownAllResFrames_val_ptr );

/*
 * TODO:231:o: |-> copy channelDownAllResFrames data.
 * get (* channelDownAllResFrames_val_ptr ).low and (* channelDownAllResFrames_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelDownAllResFrames_val_ptr ).high = rowreq_ctx->data.channelDownAllResFrames.high;
    (* channelDownAllResFrames_val_ptr ) = rowreq_ctx->data.channelDownAllResFrames;


    return MFD_SUCCESS;
} /* channelDownAllResFrames_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelUpAllDropFrames
 * channelUpAllDropFrames is subid 13 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.13
 * Description:
All the drop frames of up channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelUpAllDropFrames.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelUpAllDropFrames_map(unsigned long long *mib_channelUpAllDropFrames_val_ptr, unsigned long long raw_channelUpAllDropFrames_val)
{
    netsnmp_assert(NULL != mib_channelUpAllDropFrames_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelUpAllDropFrames_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelUpAllDropFrames mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelUpAllDropFrames_val_ptr) = raw_channelUpAllDropFrames_val;

    return MFD_SUCCESS;
} /* channelUpAllDropFrames_map */

/**
 * Extract the current value of the channelUpAllDropFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelUpAllDropFrames_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelUpAllDropFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelUpAllDropFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelUpAllDropFrames_val_ptr );

/*
 * TODO:231:o: |-> copy channelUpAllDropFrames data.
 * get (* channelUpAllDropFrames_val_ptr ).low and (* channelUpAllDropFrames_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelUpAllDropFrames_val_ptr ).high = rowreq_ctx->data.channelUpAllDropFrames.high;
    (* channelUpAllDropFrames_val_ptr ) = rowreq_ctx->data.channelUpAllDropFrames;


    return MFD_SUCCESS;
} /* channelUpAllDropFrames_get */

/*---------------------------------------------------------------------
 * DOT11-WTP-MIB::dot11RadioStatisticsEntry.channelUpAllResFrames
 * channelUpAllResFrames is subid 14 of dot11RadioStatisticsEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4.1.14
 * Description:
All the resend frames of up channel.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-channelUpAllResFrames.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
channelUpAllResFrames_map(unsigned long long *mib_channelUpAllResFrames_val_ptr, unsigned long long raw_channelUpAllResFrames_val)
{
    netsnmp_assert(NULL != mib_channelUpAllResFrames_val_ptr);
    
    DEBUGMSGTL(("verbose:dot11RadioStatisticsTable:channelUpAllResFrames_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement channelUpAllResFrames mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_channelUpAllResFrames_val_ptr) = raw_channelUpAllResFrames_val;

    return MFD_SUCCESS;
} /* channelUpAllResFrames_map */

/**
 * Extract the current value of the channelUpAllResFrames data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param channelUpAllResFrames_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
channelUpAllResFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelUpAllResFrames_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != channelUpAllResFrames_val_ptr );

/*
 * TODO:231:o: |-> copy channelUpAllResFrames data.
 * get (* channelUpAllResFrames_val_ptr ).low and (* channelUpAllResFrames_val_ptr ).high from rowreq_ctx->data
 */
    //(* channelUpAllResFrames_val_ptr ).high = rowreq_ctx->data.channelUpAllResFrames.high;
    (* channelUpAllResFrames_val_ptr ) = rowreq_ctx->data.channelUpAllResFrames;


    return MFD_SUCCESS;
} /* channelUpAllResFrames_get */



/** @} */
