/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18.2.1 $ of : mfd-data-get.m2c,v $
 *
 * $Id:$
 *
 * @file dot11RadioStatisticsTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef DOT11RADIOSTATISTICSTABLE_DATA_GET_H
#define DOT11RADIOSTATISTICSTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11RadioStatisticsTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * dot11RadioStatisticsTable is subid 4 of wtpRadio.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.1.4.4, length: 12
*/
    /*
     * indexes
     */
    int wtpRadCurrID_radiostatistics_map(long *mib_wtpRadCurrID_val_ptr, long raw_wtpRadCurrID_val);
    int bssid_radiostatistics_map(long *mib_bssid_val_ptr, long raw_bssid_val);

    int wirelessUpFlow_map(unsigned long long *mib_wirelessUpFlow_val_ptr, unsigned long long raw_wirelessUpFlow_val);
    int wirelessUpFlow_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * wirelessUpFlow_val_ptr );
    int wirelessDownFlow_map(unsigned long long *mib_wirelessDownFlow_val_ptr, unsigned long long raw_wirelessDownFlow_val);
    int wirelessDownFlow_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * wirelessDownFlow_val_ptr );
    int channelDownAllPkts_map(unsigned long long *mib_channelDownAllPkts_val_ptr, unsigned long long raw_channelDownAllPkts_val);
    int channelDownAllPkts_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllPkts_val_ptr );
    int channelDownAllDropPkts_map(unsigned long long *mib_channelDownAllDropPkts_val_ptr, unsigned long long raw_channelDownAllDropPkts_val);
    int channelDownAllDropPkts_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllDropPkts_val_ptr );
    int channelDownAllMacErrPkts_map(unsigned long long *mib_channelDownAllMacErrPkts_val_ptr, unsigned long long raw_channelDownAllMacErrPkts_val);
    int channelDownAllMacErrPkts_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllMacErrPkts_val_ptr );
    int channelDownAllResPkts_map(unsigned long long *mib_channelDownAllResPkts_val_ptr, unsigned long long raw_channelDownAllResPkts_val);
    int channelDownAllResPkts_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllResPkts_val_ptr );
    int channelUpAllFrames_map(unsigned long long *mib_channelUpAllFrames_val_ptr, unsigned long long raw_channelUpAllFrames_val);
    int channelUpAllFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelUpAllFrames_val_ptr );
    int channelDownAllFrames_map(unsigned long long *mib_channelDownAllFrames_val_ptr, unsigned long long raw_channelDownAllFrames_val);
    int channelDownAllFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllFrames_val_ptr );
    int channelDownAllErrFrames_map(unsigned long long *mib_channelDownAllErrFrames_val_ptr, unsigned long long raw_channelDownAllErrFrames_val);
    int channelDownAllErrFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllErrFrames_val_ptr );
    int channelDownAllDropFrames_map(unsigned long long *mib_channelDownAllDropFrames_val_ptr, unsigned long long raw_channelDownAllDropFrames_val);
    int channelDownAllDropFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllDropFrames_val_ptr );
    int channelDownAllResFrames_map(unsigned long long *mib_channelDownAllResFrames_val_ptr, unsigned long long raw_channelDownAllResFrames_val);
    int channelDownAllResFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelDownAllResFrames_val_ptr );
    int channelUpAllDropFrames_map(unsigned long long *mib_channelUpAllDropFrames_val_ptr, unsigned long long raw_channelUpAllDropFrames_val);
    int channelUpAllDropFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelUpAllDropFrames_val_ptr );
    int channelUpAllResFrames_map(unsigned long long *mib_channelUpAllResFrames_val_ptr, unsigned long long raw_channelUpAllResFrames_val);
    int channelUpAllResFrames_get( dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, unsigned long long * channelUpAllResFrames_val_ptr );


int dot11RadioStatisticsTable_indexes_set_tbl_idx(dot11RadioStatisticsTable_mib_index *tbl_idx, long wtpRadCurrID_val, long bssid_val);
int dot11RadioStatisticsTable_indexes_set(dot11RadioStatisticsTable_rowreq_ctx *rowreq_ctx, long wtpRadCurrID_val, long bssid_val);




#ifdef __cplusplus
}
#endif

#endif /* DOT11RADIOSTATISTICSTABLE_DATA_GET_H */
/** @} */
