#ifndef _ASD_DBUS_DEF1_H
#define _ASD_DBUS_DEF1_H

extern char ASD_DBUS_BUSNAME[PATH_LEN];
extern char ASD_DBUS_OBJPATH[PATH_LEN];
extern char ASD_DBUS_INTERFACE[PATH_LEN];


extern char ASD_DBUS_STA_OBJPATH[PATH_LEN];
extern char ASD_DBUS_STA_INTERFACE[PATH_LEN];

extern char ASD_DBUS_STA_METHOD_SHOWSTA[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_EXTEND_SHOWSTA[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_SHOWSTA_BYMAC[PATH_LEN];	/*ht add 091216*/
extern char ASD_DBUS_STA_METHOD_SHOW_INFO_BYWTPID[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_SHOW_INFO_BYWLANID[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_SHOW_RADIO_INFO_BYWTPID[PATH_LEN];	/*ht add 090428*/
extern char ASD_DBUS_STA_METHOD_SHOW_WAPI_INFO_BYWTPID[PATH_LEN];	/*ht add 090622*/
extern char ASD_DBUS_STA_METHOD_SHOW_CHANNEL_ACCESS_TIME[PATH_LEN];	/*ht add 090513*/

extern char ASD_DBUS_STA_METHOD_SHOW_MIB_INFO_BYRDID[PATH_LEN];	/*	xm0616*/
extern char ASD_DBUS_STA_METHOD_SHOW_WAPI_MIB_INFO_BYRDID[PATH_LEN];	/*	xm0623*/



extern char ASD_DBUS_STA_METHOD_SHOW_TRAFFIC_LIMIT_BYBSSINDEX[PATH_LEN];	/*	xm0723*/
extern char ASD_DBUS_STA_METHOD_SHOW_TRAFFIC_LIMIT_BYRADIO[PATH_LEN];	/*	xm0723*/


extern char ASD_DBUS_STA_METHOD_SET_AC_FLOW[PATH_LEN];  /*xm0714*/
extern char ASD_DBUS_STA_METHOD_SET_EXTERN_BALANCE[PATH_LEN];  /*xm0714*/



extern char ASD_DBUS_STA_METHOD_KICKSTA[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_SET_STA_ARP[PATH_LEN];

extern char ASD_DBUS_STA_METHOD_WLAN_ADD_MAC_LIST[PATH_LEN];/*xm add 08/11/07*/
extern char ASD_DBUS_STA_METHOD_WTP_ADD_MAC_LIST[PATH_LEN];/*ht add 08.12.15*/
extern char ASD_DBUS_STA_METHOD_BSS_ADD_MAC_LIST[PATH_LEN];/*ht add 08.12.15*/
extern char ASD_DBUS_STA_METHOD_WLAN_DEL_MAC_LIST[PATH_LEN];/*ht add 08.12.22*/
extern char ASD_DBUS_STA_METHOD_WTP_DEL_MAC_LIST[PATH_LEN];/*ht add 08.12.22*/
extern char ASD_DBUS_STA_METHOD_BSS_DEL_MAC_LIST[PATH_LEN];/*ht add 08.12.22*/

extern char ASD_DBUS_STA_METHOD_WLAN_USE_MAC_LIST[PATH_LEN];/*ht add 08.12.15*/
extern char ASD_DBUS_STA_METHOD_WTP_USE_MAC_LIST[PATH_LEN];/*ht add 08.12.15*/
extern char ASD_DBUS_STA_METHOD_BSS_USE_MAC_LIST[PATH_LEN];/*ht add 08.12.15*/
extern char ASD_DBUS_STA_METHOD_SHOW_ALL_WLAN_MAC_LIST[PATH_LEN];/*ht add 08.12.19*/
extern char ASD_DBUS_STA_METHOD_SHOW_ALL_WTP_MAC_LIST	[PATH_LEN];/*ht add 08.12.19*/
extern char ASD_DBUS_STA_METHOD_SHOW_ALL_BSS_MAC_LIST[PATH_LEN];/*ht add 08.12.19*/
extern char ASD_DBUS_STA_METHOD_SHOW_WLAN_MAC_LIST[PATH_LEN];/*ht add 08.12.22*/
extern char ASD_DBUS_STA_METHOD_SHOW_WTP_MAC_LIST[PATH_LEN];/*ht add 08.12.22*/
extern char ASD_DBUS_STA_METHOD_SHOW_BSS_MAC_LIST[PATH_LEN];/*ht add 08.12.22*/
extern char ASD_DBUS_STA_METHOD_WLAN_LIST_SHOW_RUNNING_CONFIG[PATH_LEN]; /*ht add 08.12.17*/
extern char ASD_DBUS_STA_METHOD_WTP_LIST_SHOW_RUNNING_CONFIG[PATH_LEN]; /*ht add 08.12.17*/
extern char ASD_DBUS_STA_METHOD_BSS_LIST_SHOW_RUNNING_CONFIG[PATH_LEN]; /*ht add 08.12.17*/
extern char ASD_DBUS_STA_METHOD_SHOW_WLAN_WIDS_MAC_LIST[PATH_LEN];/*ht add 09.07.14*/

extern char ASD_DBUS_STA_METHOD_STALIST[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_STALIST_NEW[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_GET_STA_INFO[PATH_LEN]; /* xm add 08/12/10*/

extern char ASD_DBUS_STA_METHOD_STA_SUMMARY[PATH_LEN];


extern char ASD_DBUS_STA_METHOD_WLAN_STALIST[PATH_LEN];

extern char ASD_DBUS_STA_METHOD_WTP_STALIST[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_EXTEND_WTP_STALIST[PATH_LEN];


extern char ASD_DBUS_STA_METHOD_ADD_DEL_STA[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_STA_TRAFFIC_LIMIT[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_STA_TRAFFIC_LIMIT_CANCEL[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_STA_SEND_TRAFFIC_LIMIT[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_STA_SEND_TRAFFIC_LIMIT_CANCEL[PATH_LEN];



extern char ASD_DBUS_SECURITY_OBJPATH[PATH_LEN];
extern char ASD_DBUS_SECURITY_INTERFACE[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_CONFIG_SECURITY[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_SHOW_SECURITY_LIST[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_SHOW_SECURITY[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_SHOW_RADIUS[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_ADD_DEL_SECURITY	[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_APPLY_WLAN[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_UPDATE_WTP_COUNT[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_SET_ACCT[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_SET_WAPI_AUTH[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_SET_WAPI_PATH[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_SET_WAPI_P12_CERT_PATH[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_SET_WAPI_MULTI_CERT[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_WPA_GROUP_REKEY_PERIOD[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_WPA_KEYUPDATE_TIMEOUT_PERIOD[PATH_LEN];


extern char ASD_DBUS_SECURITY_METHOD_SET_AUTH[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_SECONDARY_SET_AUTH[PATH_LEN]; /*xm 08/09/02*/
extern char ASD_DBUS_SECURITY_METHOD_EAP_REAUTH_PERIOD[PATH_LEN]; /*xm 08/09/02*/
extern char ASD_DBUS_SECURITY_METHOD_ACCT_INTERIM_INTERVAL[PATH_LEN]; /*xm 08/09/02*/
extern char ASD_DBUS_SECURITY_METHOD_SECONDARY_SET_ACCT[PATH_LEN]; /*xm 08/09/03*/
extern char ASD_DBUS_SECURITY_METHOD_QUIET_PERIOD[PATH_LEN]; /*ht 090727*/
extern char ASD_DBUS_SECURITY_METHOD_SECURITY_HOST_IP[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_SECURITY_TYPE[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_WAPI_UCAST_REKEY_METHOD[PATH_LEN];	/*	xm0701*/
extern char ASD_DBUS_SECURITY_METHOD_WAPI_REKEY_PARA[PATH_LEN];	/*	xm0701*/





extern char ASD_DBUS_SECURITY_METHOD_ENCRYPTION_TYPE[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_EXTENSIBLE_AUTH[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_RADIUS_SERVER_SELECT[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_SECURITY_WLAN_CHECK[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_SECURITY_SHOW_RUNNING_CONFIG[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_SECURITY_KEY[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_CONFIGURE_PORT_ENABLE[PATH_LEN];/*xm 08/09/01*/
extern char ASD_DBUS_SECURITY_METHOD_CONFIGURE_PORT[PATH_LEN];/*xm 08/09/01*/

extern char ASD_DBUS_SECURITY_METHOD_SET_PORT_VLAN_APPEND_SECURITY[PATH_LEN];/*sz20080825*/ 
extern char ASD_DBUS_SECURITY_METHOD_SET_PORT_VLAN_APPEND_ENABLE[PATH_LEN];/*sz20080825 */
extern char ASD_DBUS_SECURITY_METHOD_SET_VLAN_APPEND_SECURITY[PATH_LEN];/*sz20080825*/
extern char ASD_DBUS_SECURITY_METHOD_SET_VLAN_LIST_APPEND_ENABLE[PATH_LEN];/*sz20080825*/
extern char ASD_DBUS_SECURITY_METHOD_SET_ASD_DAEMONLOG_DEBUG[PATH_LEN];/*ht 08.12.01*/
extern char ASD_DBUS_SECURITY_METHOD_SET_ASD_LOGGER_PRINTFLAG[PATH_LEN];/*ht 08.12.04*/

extern char ASD_DBUS_SECURITY_METHOD_PRE_AUTHENTICATION[PATH_LEN];
extern char ASD_DBUS_MOBILE_OPEN[PATH_LEN];
extern char ASD_DBUS_NOTICE_STA_INFO_TO_PROTO_OPEN[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_ACCOUNTING_ON[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_RADIUS_EXTEND_ATTR[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_SECURITY_SET_AC[PATH_LEN];

/*xm add 09/02/13*/
extern char ASD_DBUS_SIG_STA_LEAVE[PATH_LEN];
extern char ASD_DBUS_SIG_STA_COME[PATH_LEN];
extern char ASD_DBUS_SIG_WTP_DENY_STA[PATH_LEN];
extern char ASD_DBUS_SIG_DE_WTP_DENY_STA[PATH_LEN];

//extern char ASD_DBUS_SIG_DENY_STA_NUM   "signal_deny_sta_num"
//ht add 090216
extern char ASD_DBUS_SIG_WAPI_TRAP[PATH_LEN];
extern char ASD_DBUS_SIG_STA_VERIFY[PATH_LEN];
extern char ASD_DBUS_SIG_STA_VERIFY_FAILED[PATH_LEN];
extern char ASD_DBUS_SIG_RADIUS_CONNECT_FAILED[PATH_LEN];
extern char ASD_DBUS_SIG_RADIUS_CONNECT_FAILED_CLEAN[PATH_LEN];
extern char ASD_DBUS_SIG_STA_JIANQUAN_FAILED[PATH_LEN];
extern char ASD_DBUS_SIG_STA_ASSOC_FAILED[PATH_LEN];



extern char ASD_DBUS_SIG_KEY_CONFLICT[PATH_LEN];
extern char ASD_DBUS_SIG_DE_KEY_CONFLICT[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_TRAP_OPEN[PATH_LEN];
extern char ASD_DBUS_SET_TRAP_ABLE[PATH_LEN];
extern char ASD_DBUS_SHOW_TRAP_STATE[PATH_LEN];

extern char ASD_DBUS_SET_STA_MAC_VLANID[PATH_LEN]; /*ht add 091028*/
extern char ASD_DBUS_CHECK_STA_BYMAC[PATH_LEN]; /*ht add 011014*/
extern char ASD_DBUS_SET_STA_STATIC_INFO[PATH_LEN]; /*ht add 011014*/
extern char ASD_DBUS_DEL_STA_STATIC_INFO[PATH_LEN]; /*ht add 011014*/
extern char ASD_DBUS_SHOW_STA_STATIC_INFO_BYMAC[PATH_LEN]; /*ht add 011014*/
extern char ASD_DBUS_SHOW_STA_STATIC_INFO[PATH_LEN]; /*ht add 011014*/
extern char ASD_DBUS_STA_METHOD_SHOW_STATIC_STA_RUNNING_CONFIG[PATH_LEN]; /*ht add 011014*/

extern char ASD_DBUS_SECURITY_METHOD_SHOW_SECURITY_WAPI_INFO[PATH_LEN] ;
extern char ASD_DBUS_SECURITY_METHOD_SHOW_WLAN_SECURITY_WAPI_CONF[PATH_LEN];/*nl 20100119*/
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_CERTIFICATE_UPDATE[PATH_LEN]; /*nl 09/11/02*/
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_MULTICAST_UPDATE[PATH_LEN]; /*nl 09/11/02*/
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_UNICAST_COUNT_UPDATE[PATH_LEN];/*nl 09/11/02*/
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_BKLIFETIME_UPDATE[PATH_LEN];/*nl 09/11/02*/
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_BKREAUTH_THREASHOLD_UPDATE[PATH_LEN];/*nl 09/11/02*/
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_SA_TIMEOUT_UPDATE[PATH_LEN];/*nl 09/11/02*/
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_MULTICAST_CIPHER[PATH_LEN];/*nl 09/11/02*/
extern char ASD_DBUS_SECURITY_METHOD_WEP_INDEX_PERIOD[PATH_LEN];/*nl 10/03/11*/


extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_WAPIPREAUTH_UPDATE[PATH_LEN];

extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_MUTICASEREKEYSTRICT_UPDATE[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_UNICASTCIPHERENABLED_UPDATE[PATH_LEN];
extern char ASD_DBUS_SECURITY_METHOD_WAPI_SUB_ATTR_AUTHENTICATIONSUITEENABLE_UPDATE[PATH_LEN];
extern char ASD_DBUS_SET_ASD_GET_STA_INFO_ABLE[PATH_LEN];	//ht add 091111
extern char ASD_DBUS_SET_ASD_GET_STA_INFO_TIME[PATH_LEN];
extern char ASD_DBUS_SET_ASD_PROCESS_80211N_ABLE[PATH_LEN];	//ht add 091111
extern char ASD_DBUS_SET_STA_STATIC_FDB_ABLE[PATH_LEN];	//ht add 100618

extern char ASD_DBUS_AC_GROUP_OBJPATH[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_INTERFACE[PATH_LEN];

extern char ASD_DBUS_AC_GROUP_METHOD_CREATE_GROUP[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_DELETE_GROUP[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_ADD_GROUP_MEMBER[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_DEL_GROUP_MEMBER[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_CONFIG[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_HOST_IP[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_SHOW_AC_GROUP_LIST[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_SHOW_AC_GROUP[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_SHOW_AC_GROUP_RUNNING_CONFIG[PATH_LEN];
extern char ASD_DBUS_AC_GROUP_METHOD_ROAMING_COUNT[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_SET_ASD_STA_ARP_LISTEN[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_SET_ASD_STA_STATIC_ARP[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_SET_ASD_STA_STATIC_ARP_IF_GROUP[PATH_LEN];

extern char ASD_DBUS_STA_METHOD_AC_ADD_MAC_LIST[PATH_LEN];	/*nl add 2010-08-28*/
extern char ASD_DBUS_STA_METHOD_AC_DEL_MAC_LIST[PATH_LEN];	/*nl add 2010-08-28*/
extern char ASD_DBUS_STA_METHOD_AC_USE_MAC_LIST[PATH_LEN];	/*nl add 2010-08-28*/
extern char ASD_DBUS_STA_METHOD_SHOW_AC_MAC_LIST[PATH_LEN]; /*nl add 2010-08-28*/


/*show  information for mib BEGIN*/
/*add for mib optimize in ASD by nl 20100707*/
/*----------------------------------------------------------------------------------------------*/
extern char ASD_DBUS_STA_METHOD_SHOW_BASIC_INFO_OF_ALL_WTP[PATH_LEN];	
extern char ASD_DBUS_STA_METHOD_SHOW_STATS_INFO_OF_ALL_WTP[PATH_LEN];
extern char ASD_DBUS_STA_METHOD_SHOW_STATS_INFO_BY_WLAN_OF_ALL_WTP[PATH_LEN];	
extern char ASD_DBUS_STA_METHOD_SHOW_SSID_STATS_INFO_BY_WLAN_OF_ALL_WTP[PATH_LEN];	
extern char ASD_DBUS_STA_METHOD_SHOW_WLAN_WAPI_BASIC_INFO_BY_WLAN_OF_ALL_WTP[PATH_LEN];	
extern char ASD_DBUS_STA_METHOD_SHOW_USER_LINK_INFO_OF_ALL_WTP[PATH_LEN];		
extern char ASD_DBUS_STA_METHOD_SHOW_WLAN_UNICAST_INFO_BY_WLAN_OF_ALL_WTP[PATH_LEN];	
extern char ASD_DBUS_STA_METHOD_SHOW_WLAN_WAPI_PERFORMANCE_STATS_INFO_OF_ALL_WLAN[PATH_LEN];	
extern char ASD_DBUS_STA_METHOD_SHOW_WLAN_WAPI_EXTEND_CONFIG_INFO_BY_WLAN_OF_ALL_WTP[PATH_LEN];	
extern char ASD_DBUS_STA_METHOD_SHOW_WLAN_WAPI_PERFORMANCE_BSS_INFO_OF_ALL_WLAN[PATH_LEN];	

extern char ASD_DBUS_STA_METHOD_SHOW_RADIO_WIRELESS_INFO_BYWTPID[PATH_LEN];		/*nl add 20100502*/
extern char ASD_DBUS_STA_METHOD_SHOW_RADIO_NEW_WIRELESS_INFO_BYWTPID[PATH_LEN];	/*nl add 20100607*/
extern char ASD_DBUS_STA_METHOD_SHOW_SECURITY_INFO_BYWTPID[PATH_LEN];	/*nl add 20100607*/
extern char ASD_DBUS_STA_METHOD_SHOW_ALL_WTP_INFORMATION[PATH_LEN];	/*nl add 20100622*/
/*----------------------------------------------------------------------------------------------*/
/*add for mib optimize in ASD by lzh 20100708*/
extern char ASD_DBUS_STA_METHOD_SHOW_TERMINAL_INFO_OF_ALL_WTP[PATH_LEN];		/*lzh add 20100512*/
extern char ASD_DBUS_STA_METHOD_SHOW_STA_INFO_OF_ALL_WTP[PATH_LEN];		 /*liuzhenhua append 2010-05-28*/
extern char ASD_DBUS_CONF_METHOD_SHOW_ALL_WLAN_SSID_CONFIG_INFORMATION[PATH_LEN];  /*liuzhenhua append 2010-05-21*/
extern char ASD_DBUS_STA_METHOD_SHOW_BSS_STA_NUM_BY_WLANID_AND_RADIOID[PATH_LEN];

/*show  information for mib END*/

enum asd_dbus_result {
	ASD_DBUS_SUCCESS,
	ASD_DBUS_ERROR,
	ASD_STA_NOT_EXIST,
	ASD_WLAN_NOT_EXIST,
	ASD_WAPI_WLAN_NOT_EXIST,
	ASD_WTP_NOT_EXIST,
	ASD_SECURITY_NOT_EXIST,
	ASD_RADIO_NOT_EXIST,				/*nl add for id check */
	ASD_SECURITY_BE_USED,	
	ASD_SECURITY_ACCT_NOT_EXIST,
	ASD_SECURITY_ACCT_BE_USED,	
	ASD_SECURITY_AUTH_NOT_EXIST,
	ASD_SECURITY_AUTH_BE_USED,
	ASD_SECURITY_TYPE_NOT_MATCH_ENCRYPTION_TYPE,
	ASD_SECURITY_TYPE_WITHOUT_8021X,
	ASD_SECURITY_TYPE_WITHOUT_WAPI_AUTH,
	ASD_SECURITY_PROFILE_NOT_INTEGRITY,
	ASD_SECURITY_PROFILE_NOT_BIND_WLAN,
	ASD_WLAN_HAS_BEEN_BINDED,
	ASD_SECURITY_KEY_NOT_PERMIT,
	ASD_SECURITY_KEY_LEN_NOT_PERMIT,
	ASD_SECURITY_KEY_LEN_NOT_PERMIT_HEX,
	ASD_SECURITY_KEY_HEX_FORMAT,
	ASD_SECURITY_KEY_HAS_BEEN_SET,
	ASD_SECURITY_WLAN_SHOULD_BE_DISABLE,
	ASD_BSS_NOT_EXIST,
	ASD_BSS_VALUE_INVALIDE,
	ASD_WLAN_VALUE_INVALIDE,
	ASD_UNKNOWN_ID,
	ASD_EXTENSIBLE_AUTH_NOT_SUPPORT,
	ASD_PRE_AUTH_NOT_SUPPORT,
	ASD_UPDATE_ERROR,	
	ASD_WTP_ID_LARGE_THAN_MAX,
	ASD_WLAN_ID_LARGE_THAN_MAX,			/*nl add for id check */
	ASD_RADIO_ID_LARGE_THAN_MAX,
	ASD_SECURITY_LARGE_THAN_MAX,		/*nl add for id check */
	ASD_BSS_ID_LARGE_THAN_MAX,	
	ASD_WIDS_OPEN,	
	ASD_MAC_ADD_ALREADY,
	ASD_SECURITY_TYPE_HAS_CHANGED,		/*nl  add 09/10/27*/	
	ASD_DBUS_MALLOC_FAIL,
	ASD_DBUS_SET_ERROR,
	ASD_AC_GROUP_ID_USED,
	ASD_AC_GROUP_ID_NOT_EXIST,
	ASD_AC_GROUP_ESSID_NOT_EXIST,
	ASD_AC_GROUP_MEMBER_EXIST,
	ASD_AC_GROUP_MEMBER_NOT_EXIST,
	ASD_IFNAME_NOT_EXIST,
	ASD_ARP_GROUP_EXIST,
	ASD_NEED_REBOOT
};

/*add for id check 20100804 by nl*/
enum asd_check_type {
	ASD_WTP_CHECK,
	ASD_WLAN_CHECK,
	ASD_RADIO_CHECK,
	ASD_SECURITY_CHECK,
	ASD_BSS_CHECK,

};

enum asd_security_type {
	OPEN,
	SHARED,
	IEEE8021X,
	WPA_P,
	WPA2_P,
	WPA_E,
	WPA2_E,
	MD5,
	WAPI_PSK,
	WAPI_AUTH  
};

enum asd_encryption_type {
	NONE,
	WEP,
	AES,
	TKIP,
	SMS4
};
enum { AUTH_REQUEST, 
	   AUTH_RESPONSE, 
	   AUTH_SUCCESS,
	   AUTH_FAIL,
	   AUTH_TIMEOUT,
	   AUTH_IDLE,
	   AUTH_INITIALIZE,
	   AUTH_IGNORE
} auth_state;

enum { PAE_INITIALIZE,
	   PAE_DISCONNECTED,
	   PAE_CONNECTING,
	   PAE_AUTHENTICATING,
	   PAE_AUTHENTICATED,
	   PAE_ABORTING,
	   PAE_HELD,
	   PAE_FORCE_AUTH,
	   PAE_FORCE_UNAUTH,
	   PAE_RESTART
} pae_state;

enum asd_static_sta_value_type {
	VLANID,
	LIMIT,
	SEND_LIMIT
};

#endif

