#ifndef _VERSION_18SP7_
#ifndef _PPPOE_DEF_H
#define _PPPOE_DEF_H

enum {
	PPPOEERR_SUCCESS	= 0x0,
	PPPOEERR_EINVAL		= -0x1,
	PPPOEERR_ENOMEM		= -0x2,
	PPPOEERR_EEXIST		= -0x3,
	PPPOEERR_ENOEXIST	= -0x4,
	PPPOEERR_ESEND		= -0x5,
	PPPOEERR_ERECV		= -0x6,
	PPPOEERR_ETIMEOUT	= -0x7,
	PPPOEERR_ELENGTH	= -0x8,
	PPPOEERR_EADDR		= -0x9,
	PPPOEERR_ESYSCALL	= -0xa,
	PPPOEERR_EDBUS		= -0xb,
	PPPOEERR_ESOCKET	= -0xc,
	PPPOEERR_EBIND		= -0xd,
	PPPOEERR_EPTHREAD	= -0xe,
	PPPOEERR_ESERVICE	= -0xf,
	PPPOEERR_ESTATE		= -0x10,
	PPPOEERR_ECONFIG	= -0x11,
	PPPOEERR_EOPEN		= -0x12,
	PPPOEERR_ETBUS		= -0x13,
	PPPOEERR_ELISTEN	= -0x14,
	PPPOEERR_ECONNECT	= -0x15,
	PPPOEERR_EAGAIN		= -0x16,
};

#define LOCAL_SLOTID_FILE   "/dbm/local_board/slot_id"
#define DISTRIBUTED_FILE    "/dbm/product/is_distributed"
#define SLOT_COUNT_FILE     "/dbm/product/slotcount"
#define BOARD_MASK_FILE     "/dbm/product/board_on_mask"

#define HANSI_REMOTE			0
#define HANSI_LOCAL				1
#define HANSI_MAX_ID			16
#define SLOT_MAX_NUM			16

#define PPPOE_LOG_DEBUG_OFF		0
#define PPPOE_LOG_DEBUG_ON		1		
//#define PPPOE_MAX_DEBUG_TOKENS	256

typedef enum {
	TOKEN_INSTANCE,
	TOKEN_BACKUP,
	TOKEN_NETLINK,
	TOKEN_THREAD,
	TOKEN_TBUS,
	TOKEN_METHOD,
	TOKEN_MANAGE,
	TOKEN_RADIUS,
	TOKEN_DISCOVER,
	TOKEN_CONTROL,
	TOKEN_LCP,
	TOKEN_CHAP,
	TOKEN_CCP,
	TOKEN_IPCP,
	TOKEN_RDC,
	TOKEN_NUMS,
}PPPOELogToken;


#endif /* !_PPPOE_DEF_H */
#endif /* !_VERSION_18SP7_ */

