/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot11ConfigSysLogServerTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dot11ConfigSysLogServerTable get routines.
 * TODO:240:M: Implement dot11ConfigSysLogServerTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11ConfigSysLogServerTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * DOT11-AC-MIB::dot11ConfigSysLogServerTable is subid 1 of dot11ConfigSysLogServerGroup.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.25.1, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement dot11ConfigSysLogServerTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param SyslogIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dot11ConfigSysLogServerTable_indexes_set_tbl_idx(dot11ConfigSysLogServerTable_mib_index *tbl_idx, long SyslogIndex_val)
{
    DEBUGMSGTL(("verbose:dot11ConfigSysLogServerTable:dot11ConfigSysLogServerTable_indexes_set_tbl_idx","called\n"));

    /* SyslogIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    tbl_idx->SyslogIndex = SyslogIndex_val;
    

    return MFD_SUCCESS;
} /* dot11ConfigSysLogServerTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dot11ConfigSysLogServerTable_indexes_set(dot11ConfigSysLogServerTable_rowreq_ctx *rowreq_ctx, long SyslogIndex_val)
{
    DEBUGMSGTL(("verbose:dot11ConfigSysLogServerTable:dot11ConfigSysLogServerTable_indexes_set","called\n"));

    if(MFD_SUCCESS != dot11ConfigSysLogServerTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , SyslogIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != dot11ConfigSysLogServerTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* dot11ConfigSysLogServerTable_indexes_set */


/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11ConfigSysLogServerEntry.SyslogServerIPPort
 * SyslogServerIPPort is subid 2 of dot11ConfigSysLogServerEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.25.1.1.2
 * Description:
SyslogServerIPAddr,config for IP:Port . Use MG-SOFT MIB browser and select Bits when set value . example,# 0xC0 0xA8 0xA8 0xA8 0xA8 0xA8.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  1 - 255;
 *
 * Its syntax is TAddress (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the SyslogServerIPPort data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param SyslogServerIPPort_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param SyslogServerIPPort_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by SyslogServerIPPort.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*SyslogServerIPPort_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update SyslogServerIPPort_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
SyslogServerIPPort_get( dot11ConfigSysLogServerTable_rowreq_ctx *rowreq_ctx, char **SyslogServerIPPort_val_ptr_ptr, size_t *SyslogServerIPPort_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != SyslogServerIPPort_val_ptr_ptr) && (NULL != *SyslogServerIPPort_val_ptr_ptr));
   netsnmp_assert( NULL != SyslogServerIPPort_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11ConfigSysLogServerTable:SyslogServerIPPort_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the SyslogServerIPPort data.
 * copy (* SyslogServerIPPort_val_ptr_ptr ) data and (* SyslogServerIPPort_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for SyslogServerIPPort data
     */
    if ((NULL == (* SyslogServerIPPort_val_ptr_ptr )) ||
        ((* SyslogServerIPPort_val_ptr_len_ptr ) <
         (rowreq_ctx->data.SyslogServerIPPort_len* sizeof(rowreq_ctx->data.SyslogServerIPPort[0])))) {
        /*
         * allocate space for SyslogServerIPPort data
         */
        (* SyslogServerIPPort_val_ptr_ptr ) = malloc(rowreq_ctx->data.SyslogServerIPPort_len* sizeof(rowreq_ctx->data.SyslogServerIPPort[0]));
        if(NULL == (* SyslogServerIPPort_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* SyslogServerIPPort_val_ptr_len_ptr ) = rowreq_ctx->data.SyslogServerIPPort_len* sizeof(rowreq_ctx->data.SyslogServerIPPort[0]);
    memcpy( (* SyslogServerIPPort_val_ptr_ptr ), rowreq_ctx->data.SyslogServerIPPort, rowreq_ctx->data.SyslogServerIPPort_len* sizeof(rowreq_ctx->data.SyslogServerIPPort[0]) );

    return MFD_SUCCESS;
} /* SyslogServerIPPort_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11ConfigSysLogServerEntry.SyslogRowStatus
 * SyslogRowStatus is subid 3 of dot11ConfigSysLogServerEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.25.1.1.3
 * Description:
This variable is used to create, modify, and/or delete a row
			        	 in this table.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * Its syntax is RowStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the SyslogRowStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param SyslogRowStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
SyslogRowStatus_get( dot11ConfigSysLogServerTable_rowreq_ctx *rowreq_ctx, u_long * SyslogRowStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != SyslogRowStatus_val_ptr );

    (* SyslogRowStatus_val_ptr ) = rowreq_ctx->data.SyslogRowStatus;

    return MFD_SUCCESS;
} /* SyslogRowStatus_get */



/** @} */
