/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "dot11NewConfigVlanGroupTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement dot11NewConfigVlanGroupTable get routines.
 * TODO:240:M: Implement dot11NewConfigVlanGroupTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table dot11NewConfigVlanGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * DOT11-AC-MIB::dot11NewConfigVlanGroupTable is subid 2 of dot11ConfigVlanGroup.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.31656.6.1.2.22.2, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement dot11NewConfigVlanGroupTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param NewVlanID_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
dot11NewConfigVlanGroupTable_indexes_set_tbl_idx(dot11NewConfigVlanGroupTable_mib_index *tbl_idx, long NewVlanID_val)
{
    DEBUGMSGTL(("verbose:dot11NewConfigVlanGroupTable:dot11NewConfigVlanGroupTable_indexes_set_tbl_idx","called\n"));

    /* NewVlanID(1)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/r/d/h */
    tbl_idx->NewVlanID = NewVlanID_val;
    

    return MFD_SUCCESS;
} /* dot11NewConfigVlanGroupTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
dot11NewConfigVlanGroupTable_indexes_set(dot11NewConfigVlanGroupTable_rowreq_ctx *rowreq_ctx, long NewVlanID_val)
{
    DEBUGMSGTL(("verbose:dot11NewConfigVlanGroupTable:dot11NewConfigVlanGroupTable_indexes_set","called\n"));

    if(MFD_SUCCESS != dot11NewConfigVlanGroupTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , NewVlanID_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != dot11NewConfigVlanGroupTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* dot11NewConfigVlanGroupTable_indexes_set */


/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11NewConfigVlanGroupEntry.NewPort
 * NewPort is subid 2 of dot11NewConfigVlanGroupEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.22.2.1.2
 * Description:
NewVlan  Port.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the NewPort data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param NewPort_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param NewPort_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by NewPort.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*NewPort_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update NewPort_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
NewPort_get( dot11NewConfigVlanGroupTable_rowreq_ctx *rowreq_ctx, char **NewPort_val_ptr_ptr, size_t *NewPort_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != NewPort_val_ptr_ptr) && (NULL != *NewPort_val_ptr_ptr));
   netsnmp_assert( NULL != NewPort_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11NewConfigVlanGroupTable:NewPort_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the NewPort data.
 * copy (* NewPort_val_ptr_ptr ) data and (* NewPort_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for NewPort data
     */
    if ((NULL == (* NewPort_val_ptr_ptr )) ||
        ((* NewPort_val_ptr_len_ptr ) <
         (rowreq_ctx->data.NewPort_len* sizeof(rowreq_ctx->data.NewPort[0])))) {
        /*
         * allocate space for NewPort data
         */
        (* NewPort_val_ptr_ptr ) = malloc(rowreq_ctx->data.NewPort_len* sizeof(rowreq_ctx->data.NewPort[0]));
        if(NULL == (* NewPort_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* NewPort_val_ptr_len_ptr ) = rowreq_ctx->data.NewPort_len* sizeof(rowreq_ctx->data.NewPort[0]);
    memcpy( (* NewPort_val_ptr_ptr ), rowreq_ctx->data.NewPort, rowreq_ctx->data.NewPort_len* sizeof(rowreq_ctx->data.NewPort[0]) );

    return MFD_SUCCESS;
} /* NewPort_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11NewConfigVlanGroupEntry.NewVlanName
 * NewVlanName is subid 3 of dot11NewConfigVlanGroupEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.22.2.1.3
 * Description:
NewVlan   Name.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the NewVlanName data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param NewVlanName_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param NewVlanName_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by NewVlanName.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*NewVlanName_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update NewVlanName_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
NewVlanName_get( dot11NewConfigVlanGroupTable_rowreq_ctx *rowreq_ctx, char **NewVlanName_val_ptr_ptr, size_t *NewVlanName_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != NewVlanName_val_ptr_ptr) && (NULL != *NewVlanName_val_ptr_ptr));
   netsnmp_assert( NULL != NewVlanName_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:dot11NewConfigVlanGroupTable:NewVlanName_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the NewVlanName data.
 * copy (* NewVlanName_val_ptr_ptr ) data and (* NewVlanName_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for NewVlanName data
     */
    if ((NULL == (* NewVlanName_val_ptr_ptr )) ||
        ((* NewVlanName_val_ptr_len_ptr ) <
         (rowreq_ctx->data.NewVlanName_len* sizeof(rowreq_ctx->data.NewVlanName[0])))) {
        /*
         * allocate space for NewVlanName data
         */
        (* NewVlanName_val_ptr_ptr ) = malloc(rowreq_ctx->data.NewVlanName_len* sizeof(rowreq_ctx->data.NewVlanName[0]));
        if(NULL == (* NewVlanName_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* NewVlanName_val_ptr_len_ptr ) = rowreq_ctx->data.NewVlanName_len* sizeof(rowreq_ctx->data.NewVlanName[0]);
    memcpy( (* NewVlanName_val_ptr_ptr ), rowreq_ctx->data.NewVlanName, rowreq_ctx->data.NewVlanName_len* sizeof(rowreq_ctx->data.NewVlanName[0]) );

    return MFD_SUCCESS;
} /* NewVlanName_get */

/*---------------------------------------------------------------------
 * DOT11-AC-MIB::dot11NewConfigVlanGroupEntry.NewConfigVlanRowStatus
 * NewConfigVlanRowStatus is subid 4 of dot11NewConfigVlanGroupEntry.
 * Its status is Current, and its access level is Create.
 * OID: .1.3.6.1.4.1.31656.6.1.2.22.2.1.4
 * Description:
This variable is used to create, modify, and/or delete a row
			        	 in this table.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 3/8. Values:  active(1), notInService(2), notReady(3), createAndGo(4), createAndWait(5), destroy(6)
 *
 * Its syntax is RowStatus (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the NewConfigVlanRowStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param NewConfigVlanRowStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
NewConfigVlanRowStatus_get( dot11NewConfigVlanGroupTable_rowreq_ctx *rowreq_ctx, u_long * NewConfigVlanRowStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != NewConfigVlanRowStatus_val_ptr );

    (* NewConfigVlanRowStatus_val_ptr ) = rowreq_ctx->data.NewConfigVlanRowStatus;

    return MFD_SUCCESS;
} /* NewConfigVlanRowStatus_get */



/** @} */
