#!/bin/sh
#
###########################################################################
#
#              Copyright (C) Autelan Technology
#
#This software file is owned and distributed by Autelan Technology 
#
############################################################################
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
#ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
#WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
#DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR 
#ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
#(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
#LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
#ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
#(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
#SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#
# eag_init
#
# CREATOR:
# autelan.software.qiaojie. team
# 
# DESCRIPTION: 
#     which init system default limit param
#############################################################################

PATH=/sbin:/bin:/usr/sbin:/usr/bin
. /lib/lsb/init-functions



CONFSTAT=/opt/services/status/limit_status.status
CONFIG=/etc/security/limits.conf
CONFXML=/opt/services/option/limit_option

write_config(){
echo " 
#@vtyadmin              hard    maxlogins       3
#@vtyview               hard    maxlogins       3
#%vtyview               hard    maxsyslogins    6
#%vtyadmin              hard    maxsyslogins    6
*                       hard    maxsyslogins    8
" > $CONFIG
           } 


write_xml(){
echo " 

<root>
<node attribute=\"1\">
<state>off</state>
<name>@vtyadmin</name>
<ruler>hard</ruler>
<device>maxlogins</device>
<number>3</number>
</node>
<node attribute=\"2\">
<state>off</state>
<name>@vtyview</name>
<ruler>hard</ruler>
<device>maxlogins</device>
<number>3</number>
</node>
<node attribute=\"3\">
<state>off</state>
<name>%vtyview</name>
<ruler>hard</ruler>
<device>maxsyslogins</device>
<number>6</number>
</node>
<node attribute=\"4\">
<state>off</state>
<name>%vtyadmin</name>
<ruler>hard</ruler>
<device>maxsyslogins</device>
<number>6</number>
</node>
<node attribute=\"5\">
<state>on</state>
<name>*</name>
<ruler>hard</ruler>
<device>maxsyslogins</device>
<number>8</number>
</node>
</root>
" > $CONFXML
           } 
           
write_stat(){  
     echo "1" > $CONFSTAT
     }    
           
create_config(){
    
                 if ! test -f $CONFIG; then
                        sudo touch $CONFIG 
                        sudo chmod 666 $CONFIG 
                        write_config
                   else
                    sudo chmod 666 $CONFIG
                 fi
             }        
           
create_xml(){
    
                 if ! test -f $CONFXML; then
                        touch $CONFXML 
                        chmod 666 $CONFXML 
                        write_xml
                   else
                    sudo chmod 666 $CONFXML
                 fi
             } 
             
create_stat(){
    
                 if ! test -f $CONFSTAT; then
                        touch $CONFSTAT 
                        chmod 666 $CONFSTAT 
                        write_stat
                   else
                    sudo chmod 666 $CONFSTAT
                 fi
             }
             
 create_config
 create_xml
 create_stat